.include "display/anim.asm"
.include "display/bkg_chr.asm"
.include "display/dialog.asm"
.include "display/img.asm"

.include "draw/close_packet.asm"
.include "draw/packet_res.asm"
.include "draw/packets.asm"
.include "draw/sprites.asm"

.include "fetch/anim.asm"
.include "fetch/img.asm"
.include "fetch/util.asm"

.include "rleinc.asm"
.include "snif_decode.asm"
.include "update/anim.asm"
.include "update/dialog.asm"
.include "update/image.asm"
.include "update/image2.asm"
