; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_3_data_pwaa_ost=music_3_data_pwaa_ost
.endif

music_3_data_pwaa_ost:
	.byte 6
	.word @instruments
	.word @samples-148
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6 ; 00 : Congratulations Everybody
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6 ; 01 : Light and Shadow of The Film Studio
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6 ; 02 : Steel Samuria
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,@song3ch5,@song3ch6 ; 03 : Case DL-6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,@song4ch5,@song4ch6 ; 04 : Investigation
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,@song5ch5,@song5ch6 ; 05 : Won the Case
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_3_data_pwaa_ost
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env4,@env5,@env0 ; 00 : Kick
	.word @env1,@env4,@env7,@env0 ; 01 : Lead
	.word @env9,@env4,@env6,@env0 ; 02 : Lead 2
	.word @env9,@env4,@env7,@env0 ; 03 : Lead quite
	.word @env2,@env4,@env6,@env0 ; 04 : String quite
	.word @env3,@env4,@env7,@env0 ; 05 : Wobble quite

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$0f,$7e	;37 (triangle volume)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $0a,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$00,$07,$c2,$c2,$c1,$c1,$c0,$00,$0e
@env2:
	.byte $00,$c5,$c4,$c3,$c2,$c2,$c1,$00,$06
@env3:
	.byte $00,$c3,$c2,$02,$c1,$03,$c2,$c2,$c2,$00,$01
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00
@env7:
	.byte $c1,$7f,$00,$00
@env8:
	.byte $00,$c7,$c4,$c2,$c0,$00,$04
@env9:
	.byte $08,$c5,$c4,$c4,$c3,$c3,$00,$05,$c2,$c2,$c1,$02,$c0,$00,$0c

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $cf
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $88
@song0ref8:
	.byte $0d, $97, $00, $97, $0d, $97, $00, $97, $0d, $97, $00, $97, $0d, $97, $00, $97, $47, $11, $97, $00, $97, $11, $97, $00
	.byte $97, $11, $97, $00, $97, $11, $97, $00, $97, $47, $12, $97, $00, $97, $12, $97, $00, $97, $12, $97, $00, $97, $12, $97
	.byte $00, $97, $47, $14, $97, $00, $97, $14, $97, $00, $97, $14, $97, $00, $97, $14, $97, $00, $97, $47
	.byte $41, $40
	.word @song0ref8
@song0ref79:
	.byte $47, $19, $ff, $99, $00, $97, $1b, $97, $47, $95, $00, $81, $19, $93, $00, $81, $1b, $93, $00, $9b, $1d, $ad, $00, $b5
	.byte $47, $1d, $93, $00, $81, $1e, $93, $00, $9b, $20, $ad, $00, $81, $19, $ad, $00, $81, $19, $97, $47, $95, $00, $81, $19
	.byte $93, $00, $81, $19, $93, $00, $9b, $1b, $ad, $00, $b5
	.byte $41, $0e
	.word @song0ref79
	.byte $20, $93, $00, $9b, $1d, $ad, $00, $b5, $47, $20, $df, $00, $83, $25, $8b, $25, $85, $00, $81, $25, $87, $00, $81, $25
	.byte $85, $00, $9b, $19, $97, $47, $00, $97, $1b, $f9, $00, $b7, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $cf
@song0ch1loop:
	.byte $86, $25, $97, $19, $93, $00, $81, $25, $97, $00, $8b, $25
@song0ref195:
	.byte $85, $00, $81, $25, $97, $1d, $93, $00, $81, $25, $97, $20, $97, $24, $97, $1d, $93, $00, $81, $24, $97, $00, $8b, $20
	.byte $85, $00, $81, $24, $93, $00, $81, $1d, $93, $00, $81, $24, $93, $00, $81, $1d, $93, $00, $81, $25, $93, $00, $81, $1e
	.byte $93, $00, $81, $25, $97, $00, $8b, $19, $85, $00, $81, $25, $93, $00, $81, $19, $93, $00, $81, $25, $93, $00, $81, $19
@song0ref267:
	.byte $93
@song0ref268:
	.byte $00, $81, $24, $93, $00, $81, $20, $93, $00, $81, $25, $97, $00, $8b, $1b, $85, $00, $81, $25, $93, $00, $81, $20
	.byte $41, $0d
	.word @song0ref267
	.byte $19, $93, $00, $81, $25, $97, $00, $8b, $20
	.byte $41, $53
	.word @song0ref195
	.byte $24, $97, $00, $8b, $1b, $85
	.byte $41, $0a
	.word @song0ref268
	.byte $24, $93, $00, $81, $20
@song0ref320:
	.byte $93, $00, $81, $16, $97, $1d, $c7, $00, $81, $1b, $e1, $00, $81, $14, $97, $1b, $97, $1e, $ad, $00, $81, $19, $cb, $1d
	.byte $93, $00, $81, $16, $97, $1d, $c7, $00, $81, $12, $cb, $1e, $93, $00, $81, $14, $97, $1b, $ff, $93, $00, $83, $1b
	.byte $41, $2d
	.word @song0ref320
	.byte $9d, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $cf
@song0ch2loop:
	.byte $82
@song0ref378:
	.byte $2c, $97, $00, $97, $2c, $97, $00, $97, $29, $97, $2a, $8b, $2a, $89, $00, $97, $2c, $97, $2c, $8b, $2c, $89, $25, $a5
	.byte $25, $89, $27, $a5, $27, $89, $29, $97, $25, $97, $25, $8b, $25, $89
	.byte $41, $16
	.word @song0ref378
@song0ref419:
	.byte $2a, $a5, $2a, $89, $29, $97, $27, $b1, $27, $8b, $27, $89, $00, $97
	.byte $41, $26
	.word @song0ref378
	.byte $41, $0b
	.word @song0ref378
@song0ref439:
	.byte $97, $2c, $97, $31, $8b, $31, $89, $31, $8b, $31, $89, $25, $a5, $25, $89, $2a, $a5, $2a, $89, $29, $97, $25, $97, $25
	.byte $8b, $25
@song0ref465:
	.byte $89, $20, $b1, $20, $8b, $20, $89, $20, $8b, $20, $89, $22, $b1, $22, $8b, $22, $89, $24, $97, $24, $8b, $24, $89, $22
	.byte $97, $24, $97, $24, $8b, $24, $89, $25, $b1, $25, $8b, $25, $89, $25, $8b, $25, $89, $25, $97, $27, $97, $27, $8b, $27
	.byte $89, $29, $97, $29, $8b, $29, $89, $25, $97, $25, $8b, $25, $89, $25, $97, $25, $8b, $25, $89, $20, $97, $27, $97, $00
	.byte $97, $25, $97, $25, $8b, $25, $89, $24, $97, $24, $8b, $24
	.byte $41, $2a
	.word @song0ref465
@song0ref552:
	.byte $b1, $25, $8b, $25, $89, $25, $8b, $25, $89, $2c, $97, $2c, $8b, $2c, $89, $00, $97, $22, $97, $00, $97, $24, $cb, $24
	.byte $8b, $24, $89, $24, $8b, $24, $89, $00, $b1, $42
	.word @song0ch2loop
@song0ch3:
	.byte $80, $13, $ad, $00, $81, $13, $ad, $00, $81, $13, $ad, $00, $81, $10, $8b, $00, $89, $10, $8b, $10, $89
@song0ch3loop:
	.byte $80
@song0ref611:
	.byte $0f
@song0ref612:
	.byte $97, $0d, $97, $0f, $ad, $00, $81, $0f, $ad, $00, $81, $0f, $97, $0d, $97
	.byte $41, $0d
	.word @song0ref611
	.byte $a1, $00, $81, $0d, $89, $0d
	.byte $41, $0f
	.word @song0ref612
	.byte $0d, $97, $00, $97, $0f, $ad, $00, $81, $0d, $97, $00, $8b, $0d, $85, $00, $81, $0f, $93, $00, $81, $0d, $93, $00, $81
	.byte $41, $10
	.word @song0ref611
	.byte $41, $0d
	.word @song0ref611
	.byte $a1, $00, $81, $0d, $89
	.byte $41, $10
	.word @song0ref611
	.byte $0f, $ad, $00, $81, $0f, $ad, $00, $81, $0d, $97, $00, $97, $0d, $97, $10, $93, $00, $81
@song0ref695:
	.byte $0d, $93, $00
@song0ref698:
	.byte $9b, $0f, $ad, $00, $81, $13, $8b, $00, $89
@song0ref707:
	.byte $0d, $93, $00, $81, $0f, $ad, $00, $81, $0d, $93, $00, $81, $0d, $93, $00, $81, $0f, $a1, $00, $81, $0f, $89, $00, $97
	.byte $41, $0b
	.word @song0ref707
	.byte $41, $21
	.word @song0ref698
	.byte $0d, $93, $00, $81, $0f, $97, $0f, $97
	.byte $41, $24
	.word @song0ref695
	.byte $41, $0b
	.word @song0ref707
	.byte $41, $21
	.word @song0ref698
	.byte $0d, $93, $00, $81, $0f, $97, $00, $97, $42
	.word @song0ch3loop
@song0ch4:
	.byte $25, $8b, $00, $ff, $bf
@song0ch4loop:
@song0ref771:
	.byte $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf
	.byte $41, $0a
	.word @song0ref771
	.byte $41, $0a
	.word @song0ref771
	.byte $ff, $cf, $42
	.word @song0ch4loop
@song0ch5:
	.byte $ff, $cf
@song0ch5loop:
	.byte $88, $1d
@song0ref797:
	.byte $97, $00, $97, $20, $97, $00, $97, $1d, $97, $00, $97, $20, $97, $00, $97, $1d, $97, $00, $97, $20
@song0ref817:
	.byte $97, $00, $97, $1d
@song0ref821:
	.byte $93, $00, $9b, $1d, $93, $00, $9b, $20, $93, $00, $9b, $1d, $97, $00, $97, $1e
	.byte $41, $0b
	.word @song0ref821
	.byte $1b, $97, $00, $97, $1b, $93, $00, $9b, $1b, $93, $00, $9b, $20, $97, $00, $97, $20
	.byte $41, $0b
	.word @song0ref797
	.byte $1d, $97, $00, $97, $1d
	.byte $41, $0f
	.word @song0ref817
	.byte $20, $97, $00, $97, $22, $93, $00, $9b, $20, $93, $00, $9b, $1e, $93, $00, $9b, $1e, $97, $00, $97, $1e, $93, $00, $9b
	.byte $1b, $93, $00, $9b, $b3, $14, $97
@song0ref899:
	.byte $18, $91, $00, $9d, $16, $97, $19, $97, $14, $93, $00, $81, $cd, $18, $91, $00, $83, $19
@song0ref917:
	.byte $97, $14, $97, $18, $ad, $00, $81, $b3, $14, $97, $19, $91, $00, $9d, $14, $97, $19, $ad, $00, $81, $b3, $16, $97, $19
	.byte $97, $1b
	.byte $41, $0a
	.word @song0ref917
	.byte $41, $29
	.word @song0ref899
	.byte $1b, $97, $20, $97, $1b, $97, $19, $97, $14, $93, $00, $81, $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $cf
@song0ch6loop:
	.byte $84
	.byte $41, $26
	.word @song0ref378
	.byte $41, $16
	.word @song0ref378
	.byte $41, $0e
	.word @song0ref419
	.byte $41, $26
	.word @song0ref378
	.byte $41, $0b
	.word @song0ref378
	.byte $41, $6e
	.word @song0ref439
	.byte $41, $2a
	.word @song0ref465
	.byte $41, $21
	.word @song0ref552
	.byte $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song1ref5:
	.byte $7b, $84, $25, $8d, $88, $25, $8d, $84, $28, $8d, $88, $28, $8d, $84, $27, $8d, $88, $27, $8d, $84, $28, $8d, $88, $28
	.byte $8d
@song1ref30:
	.byte $84, $2a, $8d, $88, $2a, $8d, $84, $28, $8d, $88, $28, $8d, $84, $27, $8d, $88, $27, $8d, $84, $28, $8d, $88, $28, $8d
	.byte $47
@song1ref55:
	.byte $84, $25, $8d, $88, $25, $8d, $84, $28, $8d, $88, $28, $8d, $84, $27, $8d, $88, $27, $8d, $84, $23, $8d, $88, $23, $8d
	.byte $78
	.byte $41, $10
	.word @song1ref55
@song1ref83:
	.byte $47
@song1ref84:
	.byte $77, $84, $25, $8d, $88, $25, $8d, $76, $84, $28, $8d, $88, $28, $8d, $75, $84, $27, $8d, $88, $27, $8d, $74, $84, $23
	.byte $8d, $88, $23, $8d, $72, $84, $25, $8d, $88, $25, $8d, $00, $dd, $47, $ff
	.byte $41, $10
	.word @song1ref5
	.byte $47
	.byte $41, $10
	.word @song1ref30
	.byte $41, $10
	.word @song1ref55
	.byte $47, $78
	.byte $41, $10
	.word @song1ref55
	.byte $41, $10
	.word @song1ref84
	.byte $47, $72, $84, $25, $8d, $88, $25, $8d, $00, $ff, $dd, $47
	.byte $41, $30
	.word @song1ref5
	.byte $78
	.byte $41, $10
	.word @song1ref55
	.byte $41, $17
	.word @song1ref83
	.byte $41, $10
	.word @song1ref5
	.byte $47
	.byte $41, $10
	.word @song1ref30
	.byte $41, $10
	.word @song1ref55
	.byte $47, $78
	.byte $41, $10
	.word @song1ref55
	.byte $41, $10
	.word @song1ref84
	.byte $47, $72, $84, $25, $8d, $88, $25, $8d, $00, $ff, $dd, $47, $ff, $ff, $47, $ff, $ff, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $86
@song1ref203:
	.byte $20, $ff, $fd, $bf, $1e, $bd, $20, $fd, $ff, $ff, $ff, $23, $fd, $ff, $bf, $1e, $bd, $20, $ff, $fd, $ff, $ff
	.byte $41, $16
	.word @song1ref203
	.byte $00, $ff, $fd, $ff, $1e, $fd, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $82
@song1ref239:
	.byte $19, $ff, $fd, $bf, $17, $bd, $15, $fd, $ff, $ff, $ff, $19, $fd, $ff, $bf, $17, $bd, $15, $ff, $fd, $ff, $ff
	.byte $41, $16
	.word @song1ref239
	.byte $00, $ff, $fd, $ff, $18, $fd, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $7c, $80, $0a, $97, $00, $ff, $e3, $df, $79, $0a, $97, $00, $83, $7c, $0a, $97, $00, $e3, $ff, $ff, $ff, $0a, $97, $00
	.byte $e3, $ff, $df, $79, $0a, $97, $00, $83, $7c, $0a, $97, $00, $ff, $e3, $ff, $df, $78, $0d, $85, $00, $85, $77, $0e, $85
	.byte $00, $85, $7c, $0a, $97, $00, $83, $79, $0a, $97, $00, $83, $78, $0d
@song1ref336:
	.byte $9d, $00, $bd
@song1ref339:
	.byte $7c
@song1ref340:
	.byte $0a, $97, $00, $83, $78, $0d, $9d, $00, $9d, $7c, $0a, $97, $00, $83, $79, $0a, $97, $00, $83, $78, $0d, $97, $00, $a3
@song1ref364:
	.byte $7c, $0a, $97, $00, $83, $79, $0a, $97, $00, $83, $78, $0d, $97, $00, $a3, $9f, $7c, $0a, $97, $00, $83, $78, $0d, $9d
	.byte $00, $8d, $76, $0d, $87, $00, $83
	.byte $41, $14
	.word @song1ref364
	.byte $9d, $7c, $0a, $97, $00, $83, $79, $0a, $97, $00, $83, $78, $0d, $9d, $00, $9d, $9f
	.byte $41, $13
	.word @song1ref339
	.byte $83, $79, $0a, $87, $00, $83, $78, $0d, $87, $00, $83, $7c, $0a, $97, $00, $83, $79, $0a, $97, $00, $83, $78, $0d, $97
	.byte $00, $c3, $79
	.byte $41, $13
	.word @song1ref340
	.byte $c3, $79
	.byte $41, $11
	.word @song1ref340
	.byte $41, $0f
	.word @song1ref336
	.byte $76, $0d, $85, $00, $85, $77, $0e, $85, $00, $85, $78, $0d, $97, $00, $93, $76, $0d, $85, $00, $a5, $7c, $0a, $97, $00
	.byte $83, $78, $0d, $9d, $00, $9d, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $25, $8d, $00, $ff, $ed
@song1ref495:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0f
	.word @song1ref495
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $79, $84
@song1ref519:
	.byte $19, $9d, $20, $9d, $25, $9d, $20, $9d, $78, $28, $9d, $79, $20, $9d, $78, $27, $9d, $79, $20, $9d, $19, $9d, $20, $9d
	.byte $23, $9d, $1e, $9d, $15, $9d, $1c, $9d, $21, $9d, $1c, $9d, $25, $9d, $1c, $9d, $21, $9d, $1c, $9d, $15, $fd, $bf, $00
	.byte $bd
	.byte $41, $20
	.word @song1ref519
	.byte $78, $28, $9d, $79, $1c, $9d, $25, $9d, $1c, $9d, $15, $ff, $bd, $00, $bd
	.byte $41, $2d
	.word @song1ref519
	.byte $41, $20
	.word @song1ref519
	.byte $78, $28, $9d, $79, $1c, $9d, $25, $9d, $1c, $9d, $15, $ff, $bd, $00, $bd, $ff, $ff, $ff, $ff, $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
@song1ref615:
	.byte $7b, $84, $19, $8d, $88, $19, $8d, $84, $1c, $8d, $88, $1c, $8d, $84, $1b, $8d, $88, $1b, $8d, $84, $1c, $8d, $88, $1c
	.byte $8d, $84, $1e, $8d, $88, $1e, $8d, $84, $1c, $8d, $88, $1c, $8d, $84, $1b, $8d, $88, $1b, $8d, $84, $1c, $8d, $88, $1c
	.byte $8d
@song1ref664:
	.byte $84, $19, $8d, $88, $19, $8d, $84, $1c, $8d, $88, $1c, $8d, $84, $1b, $8d, $88, $1b, $8d, $84, $17, $8d, $88, $17, $8d
	.byte $78
	.byte $41, $10
	.word @song1ref664
@song1ref692:
	.byte $77, $84, $19, $8d, $88, $19, $8d, $76, $84, $1c, $8d, $88, $1c, $8d, $75, $84, $1b, $8d, $88, $1b, $8d, $74, $84, $17
	.byte $8d, $88, $17, $8d, $72, $84, $19, $8d, $88, $19, $8d, $00, $dd, $ff
	.byte $41, $30
	.word @song1ref615
	.byte $78
	.byte $41, $10
	.word @song1ref664
	.byte $41, $15
	.word @song1ref692
	.byte $ff, $dd
	.byte $41, $30
	.word @song1ref615
	.byte $78
	.byte $41, $10
	.word @song1ref664
	.byte $41, $17
	.word @song1ref692
	.byte $41, $30
	.word @song1ref615
	.byte $78
	.byte $41, $10
	.word @song1ref664
	.byte $41, $15
	.word @song1ref692
	.byte $ff, $dd, $ff, $ff, $ff, $ff, $42
	.word @song1ch6loop
@song2ch0:
	.byte $ff, $cf
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7c, $82, $25, $8b, $78, $25, $89, $7c, $27, $8b, $78, $27
	.byte $81, $77, $27, $89, $00, $93, $7c, $28, $a5, $79, $28, $89, $7c, $25, $8b, $79, $25, $89, $7c, $28, $8b, $76, $28, $89
	.byte $75, $28, $8b, $74, $28, $89, $47, $7c, $2a, $8b, $79, $2a, $89, $7c, $28, $8b, $79, $28, $89, $7c, $2a, $8b, $79, $2a
	.byte $89, $7b, $2c, $ff, $47, $b3, $78, $2c, $8b, $76, $2c, $89, $00, $97, $7b, $2f, $cb, $78, $2f, $8b, $77, $2f, $89, $47
	.byte $7b, $31, $a9, $00, $ff, $a1, $47, $ff, $cf, $47, $ff, $cf, $47, $ff, $cf, $47, $b3, $2f, $a5, $00, $bd, $31, $a5, $00
	.byte $89, $47, $ff, $cf, $47, $ff, $cf, $47, $ff, $cf, $47, $25, $e5, $2c, $e5, $47, $2a, $b1, $28, $97, $27, $8b, $00, $a3
	.byte $23, $b1, $77, $23, $8b, $76, $23, $89, $47, $7b, $25, $b1, $28, $b1, $27, $b1, $23, $b1, $47, $20, $ff, $99, $00, $b1
	.byte $47, $25, $e5, $2c, $e5, $47, $2a, $e5, $2d, $a5, $2c, $a3, $2a, $97, $47, $2c, $b1, $2a, $b1, $28, $b1, $27, $b1, $47
	.byte $25, $ff, $99, $00, $b1, $47, $27, $e5, $2a, $e5, $47, $28, $e5, $2c, $e5, $47, $2d, $b1, $2c, $b1, $2d, $b1, $2f, $b1
	.byte $47, $2c, $ff, $99, $00, $b1, $47, $31, $b1, $00, $b1, $31, $b1, $00, $b1, $47, $2f, $b1, $2d, $97, $2c, $97, $00, $97
	.byte $2a, $b1, $00, $97, $47, $28, $b1, $2a, $b1, $2c, $b1, $2d, $b1, $47, $2c, $ff, $99, $00, $b1, $47, $25, $e5, $28, $cb
	.byte $25, $97, $47, $27, $97, $28, $97, $00, $97, $2a, $ff, $47, $28, $b1, $2a, $97, $28, $97, $27, $97, $23, $b1, $20, $97
	.byte $47, $25, $ff, $cd, $42
	.word @song2ch0loop
@song2ch1:
	.byte $ff, $cf
@song2ch1loop:
	.byte $7c, $82, $2c, $8b, $00, $89, $2f, $8b, $00, $a3, $31, $a5, $00, $89, $2c, $8b, $00, $89, $2f, $8b, $75, $2f, $89, $74
	.byte $2f, $8b, $2f, $89, $7a, $2d, $97, $2c, $8b, $00, $89, $2d, $8b, $00, $89, $7c, $2f, $ff, $b3, $77, $2f, $8b, $75, $2f
	.byte $89, $00, $97, $7c, $2c, $cb, $77, $2c, $8b, $75, $2c, $89, $7c, $31, $b1, $00, $ff, $99, $ff, $cf, $ff, $cf, $ff, $cf
	.byte $b3, $23, $a5, $00, $bd, $25, $a5, $00, $89, $ff, $cf, $ff, $cf, $ff, $cf, $7e
@song2ref381:
	.byte $25, $93, $00, $9b, $25, $93, $00, $9b, $25, $a1, $00, $81, $25, $9f
@song2ref395:
	.byte $00, $81, $25, $93, $00, $81, $23, $93, $00, $9b, $23, $93, $00, $9b, $23, $a1, $00, $81, $23, $9f, $00, $81, $23, $93
	.byte $00, $81
@song2ref421:
	.byte $21, $ad, $00, $81, $21
@song2ref426:
	.byte $ad, $00, $81, $23, $ad, $00, $81, $23, $ad, $00, $81, $28, $93, $00, $9b, $28, $93, $00, $9b, $27, $a1, $00, $81, $23
	.byte $9f, $00, $81, $20, $93, $00, $81
	.byte $41, $38
	.word @song2ref381
	.byte $41, $15
	.word @song2ref381
	.byte $41, $0b
	.word @song2ref426
	.byte $23
@song2ref467:
	.byte $ad, $00, $81, $1c, $ad, $00, $81, $1c
	.byte $41, $08
	.word @song2ref467
@song2ref478:
	.byte $ad, $00, $81, $1e, $ad, $00, $81, $1e
	.byte $41, $08
	.word @song2ref478
@song2ref489:
	.byte $ad, $00, $81, $20, $ad, $00, $81, $20
	.byte $41, $08
	.word @song2ref489
	.byte $ad, $00, $81, $25, $ad, $00, $b5, $25, $ad, $00, $b5
	.byte $41, $08
	.word @song2ref421
	.byte $41, $08
	.word @song2ref421
	.byte $1e
	.byte $41, $08
	.word @song2ref478
	.byte $ad, $00, $81, $1e
	.byte $41, $08
	.word @song2ref489
	.byte $41, $08
	.word @song2ref489
	.byte $ad, $00, $81
	.byte $41, $38
	.word @song2ref381
	.byte $41, $14
	.word @song2ref381
	.byte $42
	.word @song2ch1loop
@song2ch2:
	.byte $ff, $cf
@song2ch2loop:
	.byte $7e, $82, $14, $97, $17, $b1, $19, $b1, $14, $89, $00, $14, $89, $17, $b1, $15, $97, $14, $97, $15, $97, $17, $ff, $78
	.byte $14, $85, $77, $14, $83, $00, $76, $14, $85, $00, $75, $14, $85, $14, $83, $00, $14, $85, $00, $76, $14, $85, $14, $83
	.byte $00, $77, $14, $85, $00, $14, $85, $78, $14, $83, $00, $14, $85, $00, $79, $14, $85, $14, $83, $00, $7a, $14, $85, $00
	.byte $14, $85, $7b, $14, $83, $00, $14, $85, $00, $7c, $14, $85, $14, $83, $00, $7d, $14, $85, $00, $14, $85, $7e, $14, $83
	.byte $00, $14, $87, $19, $ff, $cd, $ff, $b5, $14, $95, $00, $14, $ff, $cd, $ff, $cf, $b3, $17, $e5, $19, $b1, $ff, $cf, $ff
	.byte $cf, $75, $17, $97, $76, $12, $97, $77, $17, $97, $79, $12, $97, $7a, $17, $97, $7b, $12, $97, $7d, $17, $97, $7e, $12
	.byte $97, $19, $ff, $cd, $ff, $cf, $ff, $cf, $7d, $1c, $97, $7c, $17, $97, $1c, $97, $7b, $17, $97, $7d, $1b, $97, $7e, $14
	.byte $97, $7d, $1b, $97, $7e, $14, $89, $00, $7d, $14, $89, $7e, $19, $ff, $cd, $ff, $cf, $ff, $b5, $7d
@song2ref734:
	.byte $17, $97, $7c, $19, $97, $7b, $14, $97, $7d, $19, $97, $7c, $14, $97, $7d, $19, $97, $7c, $14, $97, $7e, $19, $97, $7d
	.byte $14, $97, $7e, $17, $ff, $cd, $ff, $cf, $ff, $cf, $14, $95, $00, $14, $af, $00, $14, $89, $00, $14, $87, $00, $14, $95
	.byte $00, $14, $af, $00, $14, $97
@song2ref788:
	.byte $19, $b1, $7d, $14, $89, $00, $7c, $14, $87, $00, $7d, $14, $97, $7e
	.byte $41, $0a
	.word @song2ref788
	.byte $15, $ff, $cd, $12, $95, $00, $7c, $12, $95, $00, $7b, $12, $95, $00, $79, $12, $95, $00, $7a, $12, $95, $00, $12, $95
	.byte $00, $7b, $12, $95, $00, $12, $97, $14, $97, $7c, $1b, $97, $14, $97, $7d, $1b, $97, $14, $97, $1b, $97, $7e, $14, $97
	.byte $1b, $97, $19, $ff, $cd, $ff, $b5, $7d, $17, $89, $00, $7c, $17, $89, $7d, $15, $c9, $00, $15, $97, $17, $af, $00, $17
	.byte $89, $00, $17, $87, $00
	.byte $41, $12
	.word @song2ref734
	.byte $42
	.word @song2ch2loop
@song2ch3:
	.byte $99, $79, $80, $19, $8b, $19, $89
@song2ref895:
	.byte $19, $93, $00, $81, $19, $93, $00, $81
	.byte $41, $08
	.word @song2ref895
	.byte $41, $08
	.word @song2ref895
@song2ch3loop:
	.byte $ff, $cf, $ff, $cf, $99, $7a, $80, $10, $8b, $00, $89, $7b, $10, $8b, $00, $a3, $10, $8b, $00, $97, $7a, $10, $89, $7b
	.byte $0d, $8b, $00, $89, $10, $8b, $00
@song2ref941:
	.byte $89, $7e, $0d, $8b, $00, $a3, $0d, $8b, $00
@song2ref950:
	.byte $97, $79
@song2ref952:
	.byte $19, $89
@song2ref954:
	.byte $7e
@song2ref955:
	.byte $0d, $8b, $00, $89, $79, $19, $8b, $00, $89, $7e, $0d, $8b, $00, $89, $79, $19, $8b
	.byte $41, $0a
	.word @song2ref952
	.byte $19, $8b, $00, $97
	.byte $41, $0a
	.word @song2ref952
	.byte $19, $8b, $00, $a3
	.byte $41, $0b
	.word @song2ref954
	.byte $41, $11
	.word @song2ref950
	.byte $41, $0d
	.word @song2ref952
	.byte $97, $79, $19, $89, $7e, $0d, $8b, $00, $89, $0d, $8b, $00, $89, $0d, $8b, $00, $89, $79, $19, $8b, $19
	.byte $41, $08
	.word @song2ref941
	.byte $a3, $0d, $8b, $00, $a3, $0d, $8b, $00, $89, $79, $19, $8b, $7a
	.byte $41, $0d
	.word @song2ref952
	.byte $41, $0e
	.word @song2ref950
	.byte $a3
	.byte $41, $0b
	.word @song2ref955
	.byte $41, $11
	.word @song2ref950
	.byte $41, $0d
	.word @song2ref952
	.byte $41, $0f
	.word @song2ref950
	.byte $0d, $8b, $00, $89
@song2ref1055:
	.byte $0d, $8d, $00, $a1
@song2ref1059:
	.byte $0d, $8d, $00, $a1
@song2ref1063:
	.byte $0d, $8d, $00, $a1, $7b, $10, $8b, $00, $a3, $7e
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $08
	.word @song2ref1063
@song2ref1082:
	.byte $7e, $0d, $8d, $00, $87, $79, $19, $8b, $19
@song2ref1091:
	.byte $89
@song2ref1092:
	.byte $7e, $0d, $8d, $00, $87
@song2ref1097:
	.byte $79
@song2ref1098:
	.byte $19, $8b, $00, $89, $19, $8b, $00, $89, $19, $8b, $00
	.byte $41, $09
	.word @song2ref1091
	.byte $7e
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1059
	.byte $41, $08
	.word @song2ref1082
	.byte $41, $08
	.word @song2ref1098
	.byte $7e, $0d, $8d, $00, $87, $79, $19, $8b, $7e, $0d, $89
	.byte $41, $08
	.word @song2ref1097
@song2ref1145:
	.byte $7e, $0d, $8d, $00, $bb, $0d, $8d, $00, $87, $7b, $10, $8b, $00, $bd, $79, $10, $8b, $00, $89, $7e
	.byte $41, $0b
	.word @song2ref1059
@song2ref1168:
	.byte $89
@song2ref1169:
	.byte $78, $11, $8b, $79, $10, $89, $7e, $0d, $8d, $00, $87, $7b, $10, $8b, $00, $89
	.byte $41, $10
	.word @song2ref1145
	.byte $7e
	.byte $41, $0b
	.word @song2ref1055
	.byte $87
	.byte $41, $08
	.word @song2ref1169
	.byte $79, $10, $8b, $00, $89
@song2ref1201:
	.byte $7e, $0d, $8d, $00, $87, $7b, $0d, $8d, $00, $87, $10, $8b, $00, $a3
	.byte $41, $0c
	.word @song2ref1201
	.byte $41, $10
	.word @song2ref1145
	.byte $7e
	.byte $41, $0b
	.word @song2ref1059
	.byte $41, $0d
	.word @song2ref1168
	.byte $7e
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1055
	.byte $41, $0c
	.word @song2ref1059
	.byte $7e
	.byte $41, $08
	.word @song2ref1063
	.byte $7e
	.byte $41, $08
	.word @song2ref1063
	.byte $41, $10
	.word @song2ref1082
	.byte $41, $0f
	.word @song2ref1092
	.byte $89, $42
	.word @song2ch3loop
@song2ch4:
	.byte $25, $81, $00, $ff, $c9
@song2ch4loop:
@song2ref1265:
	.byte $ff, $cf, $ff, $cf, $ff, $cf, $ff, $cf
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $ff, $cf, $ff, $cf, $ff, $cf, $42
	.word @song2ch4loop
@song2ch5:
	.byte $ff, $cf
@song2ch5loop:
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $41, $08
	.word @song2ref1265
	.byte $ff, $cf, $ff, $cf, $ff, $cf, $42
	.word @song2ch5loop
@song2ch6:
	.byte $ff, $cf
@song2ch6loop:
	.byte $7c, $84, $20, $93, $74, $20, $81, $7c, $23, $93, $74, $23, $8b, $00, $8d, $7c, $25, $ad, $74, $25, $81, $7c, $20, $8b
	.byte $74, $20, $89, $7c, $25, $a1, $74, $25, $89, $00, $81, $7c, $25, $93, $00, $81, $25, $93, $00, $81, $25, $8b, $74, $25
	.byte $89, $7c, $27, $ff, $e3, $00, $81, $2c, $e1
@song2ref1393:
	.byte $00, $81, $20, $87, $00, $81, $25, $85, $00, $81, $2a, $87, $00, $81, $2c, $85
@song2ref1409:
	.byte $00, $81
@song2ref1411:
	.byte $2a, $93, $00
@song2ref1414:
	.byte $81, $28, $93, $00, $81, $25, $93, $00, $81, $23, $ad
@song2ref1425:
	.byte $00, $81, $20, $87, $00, $81, $1e, $85, $00, $81, $20, $93
	.byte $41, $0c
	.word @song2ref1425
@song2ref1440:
	.byte $00, $81, $23, $93, $00, $81, $23, $00, $89, $23, $00, $87, $20, $c7
	.byte $41, $0e
	.word @song2ref1393
	.byte $28, $85, $00, $81, $2a, $93, $00, $81, $2c, $93, $00, $81, $28, $93
	.byte $41, $0c
	.word @song2ref1440
	.byte $25, $93
	.byte $41, $0f
	.word @song2ref1409
	.byte $93, $00, $81, $25, $97, $2c, $8b, $2f, $89, $31, $97, $2f, $97
@song2ref1492:
	.byte $2a, $87, $00, $81, $28, $85, $00, $81, $25, $93, $00, $9b
	.byte $41, $08
	.word @song2ref1411
	.byte $23, $93, $00, $9b, $25, $93, $00, $81
	.byte $41, $08
	.word @song2ref1492
	.byte $2a, $93, $00, $81, $20, $93, $00, $81, $23, $93, $00, $81, $25, $97, $2c, $97, $2f, $97, $31, $97, $20, $93, $00, $81
	.byte $23, $87, $00, $81, $23, $85
	.byte $41, $09
	.word @song2ref395
	.byte $41, $08
	.word @song2ref1414
	.byte $9b, $25, $93, $00, $81, $28, $93, $00, $81, $27, $93
	.byte $41, $08
	.word @song2ref1440
	.byte $95, $25, $e1, $00, $81, $ff, $cf, $ff, $cf, $7e, $2c, $b1, $76, $2c, $97, $00, $97, $7e, $33, $b1, $76, $33, $97, $00
	.byte $97, $2a, $8b, $2c, $89, $2f, $97, $2a, $8b, $2c, $89, $2f, $97, $2a, $8b, $2c, $89, $2f, $8b, $2a, $97, $2c, $89, $2f
	.byte $97, $83, $00, $ff, $c9, $ff, $cf, $7e, $2f, $b1, $28, $b1, $76, $28, $97, $00, $97, $7e, $2a, $b1, $2c, $ff, $99, $76
	.byte $2c, $97, $00, $97
@song2ref1644:
	.byte $23, $8b, $2a, $89, $2c, $8b, $31, $89, $36, $8b, $31, $89, $2f, $8b, $2a, $89
	.byte $41, $10
	.word @song2ref1644
@song2ref1663:
	.byte $1c, $8b, $23, $89, $25, $8b, $2a, $89, $2f, $8b, $2a, $89, $28, $8b, $23, $89
	.byte $41, $10
	.word @song2ref1663
@song2ref1682:
	.byte $1e
@song2ref1683:
	.byte $8b, $25, $89, $27, $8b, $2c, $89, $31, $8b, $2c, $89, $2a, $8b, $25, $89
	.byte $41, $10
	.word @song2ref1682
	.byte $20
	.byte $41, $09
	.word @song2ref1683
	.byte $33, $89, $38, $8b, $33, $89, $31, $8b, $20, $89, $25, $8b, $27, $89, $2c, $8b, $31, $89, $33, $8b, $38, $89, $83, $00
	.byte $ff, $c9, $7f, $31, $ff, $cd, $31, $b1, $77, $31, $97, $00, $97, $7f, $34, $b1, $77, $34, $97, $00, $97, $36, $97, $00
	.byte $cb, $7f, $33, $e5, $77, $33, $97, $00, $ff, $b3, $ff, $cf, $7f, $31, $b1, $77, $31, $97, $33, $97, $31, $97, $2f, $97
	.byte $00, $97, $7f, $2a, $97, $2c, $ff, $cd, $42
	.word @song2ch6loop
@song3ch0:
@song3ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $84
@song3ref6:
	.byte $0d, $f5, $0d, $f5, $0d, $f5, $0d, $f5, $47, $0c, $f5, $0c, $f5, $0c, $f5, $0c, $f5, $47, $06, $f5, $06, $f5, $06, $f5
	.byte $06, $f5, $47, $08, $f5, $08, $f5, $08, $f5, $08, $f5, $47
	.byte $41, $20
	.word @song3ref6
	.byte $47, $09, $f5, $09, $f5, $09, $f5, $09, $f5, $47, $0b, $f5, $0b, $f5, $0b, $f5, $0b, $f5
@song3ref63:
	.byte $47, $0d, $ff, $ff, $ff, $a1, $0b, $b9, $47, $09, $ff, $ff, $ff, $a1, $0b, $b9
	.byte $41, $0e
	.word @song3ref63
	.byte $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $88
@song3ref87:
	.byte $19, $f5, $19, $f5, $19, $f5, $19, $f5, $18, $f5, $18, $f5, $18, $f5, $18, $f5, $12, $f5, $12, $f5, $12, $f5, $12, $f5
	.byte $14, $f5, $14, $f5, $14, $f5, $14, $f5
	.byte $41, $20
	.word @song3ref87
	.byte $15, $f5, $15, $f5, $15, $f5, $15, $f5, $17, $f5, $17, $f5, $17, $f5, $17, $f5
@song3ref138:
	.byte $19, $ff, $ff, $ff, $a1, $17, $b9, $15, $ff, $ff, $ff, $a1, $17, $b9
	.byte $41, $0e
	.word @song3ref138
	.byte $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $bb, $82, $19, $b3, $00, $83, $1c, $b3, $00, $83, $23, $ef
@song3ref171:
	.byte $00, $83, $21, $b3
@song3ref175:
	.byte $00, $83, $20, $b3, $00, $83, $1c, $b3, $00, $83, $1b, $b3, $00, $83, $1e, $b3, $00, $83, $23, $ff, $ab
	.byte $41, $0a
	.word @song3ref171
	.byte $1e, $b3, $00, $83, $bb, $19, $b3, $00, $83, $1c, $b3, $00, $83, $21, $ef
	.byte $41, $0a
	.word @song3ref175
	.byte $19, $b3, $00, $83, $19, $b3, $00, $83, $1b, $b3, $00, $83, $17, $ff, $ab, $00, $83, $17, $b3, $00, $83, $1b, $b3, $00
	.byte $83, $20, $b3, $00, $83, $25, $ff, $ff, $ff, $d3, $00, $87, $20, $ef, $00, $83, $27, $ef, $00, $83, $2a, $ef, $00, $83
	.byte $28, $b3, $00, $83, $27, $b3, $00, $83, $27, $ef, $00, $83, $25, $ff, $ff, $9f, $00, $87, $23, $b3, $00, $83, $20, $ef
	.byte $00, $83, $27, $ff, $e5, $00, $85, $23, $ef, $00, $83, $23, $ef, $00, $83, $25, $ff, $ff, $db, $00, $87, $28, $ff, $e7
	.byte $00, $83, $27, $ff, $e7, $00, $83, $00, $b9
@song3ref322:
	.byte $25, $9b, $20, $9b
@song3ref326:
	.byte $23
@song3ref327:
	.byte $9b, $20, $9b, $00, $b9, $25, $9b, $20, $9b, $25, $9b, $20, $9b, $00, $b9, $23, $9b, $20, $9b, $25, $9b, $20, $9b
	.byte $41, $14
	.word @song3ref322
	.byte $27
	.byte $41, $09
	.word @song3ref327
	.byte $41, $18
	.word @song3ref326
	.byte $41, $12
	.word @song3ref322
	.byte $27, $9b, $20, $9b, $27, $b1, $00, $85, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
@song3ref375:
	.byte $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
	.byte $41, $0c
	.word @song3ref375
	.byte $41, $0c
	.word @song3ref375
	.byte $41, $0c
	.word @song3ref375
	.byte $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $25, $85, $00, $ff, $ff, $ff, $d5
	.byte $41, $0c
	.word @song3ref375
	.byte $41, $0c
	.word @song3ref375
	.byte $41, $0c
	.word @song3ref375
	.byte $41, $0c
	.word @song3ref375
	.byte $ff, $ff, $ff, $df, $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $bb, $88, $31, $b3, $00, $83, $34, $b3, $00, $83
@song3ref445:
	.byte $3b, $ef
@song3ref447:
	.byte $00, $83, $39, $b3
@song3ref451:
	.byte $00, $83, $38, $b3, $00, $83, $34, $b3, $00, $83, $33, $b3, $00, $83, $36, $b3, $00, $83, $3b, $ff, $ab
	.byte $41, $0a
	.word @song3ref447
@song3ref475:
	.byte $36
@song3ref476:
	.byte $b3, $00, $83, $bb, $31, $b3, $00, $83, $34, $b3, $00, $83, $39, $ef
	.byte $41, $0a
	.word @song3ref451
@song3ref493:
	.byte $31, $b3, $00, $83, $31, $b3, $00, $83, $33, $b3, $00, $83, $2f, $ff, $ab, $00, $83, $2f, $b3, $00, $83, $33, $b3, $00
	.byte $83, $2f
	.byte $41, $0c
	.word @song3ref476
	.byte $41, $1b
	.word @song3ref445
	.byte $00, $83, $3d, $b3, $00, $83, $38, $b3, $00, $83
	.byte $41, $0f
	.word @song3ref475
	.byte $41, $0a
	.word @song3ref451
	.byte $41, $0e
	.word @song3ref493
	.byte $e5, $00, $85, $2c, $ed, $00, $85, $33, $ed, $00, $85, $31, $ff, $ff, $db, $00, $87, $34, $ff, $e3, $00, $87, $33, $ff
	.byte $e3, $00, $87
@song3ref571:
	.byte $28, $8b, $28, $8d, $20, $8b, $20, $8d
@song3ref579:
	.byte $27, $8b, $27, $8d, $20, $8b, $20, $8d, $00, $b9, $2a, $8b, $2a
@song3ref592:
	.byte $8d, $20, $8b, $20
@song3ref596:
	.byte $8d, $28, $8b, $28, $8d, $20, $8b, $20, $8d, $00, $b9, $27, $8b, $27
	.byte $41, $0d
	.word @song3ref592
	.byte $41, $27
	.word @song3ref571
	.byte $8d, $28, $8b, $28, $8d, $2f, $8b, $2f, $8d, $2f, $8b, $00
	.byte $41, $09
	.word @song3ref596
	.byte $41, $1f
	.word @song3ref579
	.byte $41, $0d
	.word @song3ref592
	.byte $41, $24
	.word @song3ref571
	.byte $20, $8b, $20, $8d, $20, $8b, $00, $8d, $27, $8b, $27, $8d, $27, $8b, $00, $8d, $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
@song3ref660:
	.byte $00, $b9, $84, $25, $9b, $88, $25, $9b, $84, $28, $9b, $88, $28, $9b, $84, $2f, $9b, $88, $2f, $9b, $2f, $9b, $2f, $9b
	.byte $84, $2d, $9b, $88
@song3ref688:
	.byte $2d, $9b, $84, $2c, $9b, $88, $2c, $9b, $84, $28, $9b, $88, $28, $9b, $84, $27, $9b, $88, $27, $9b, $84, $2a, $9b, $88
	.byte $2a, $9b, $84, $2f, $9b, $88, $2f, $9b, $2f, $9b, $2f, $d7, $84, $2d, $9b, $88, $2d
@song3ref729:
	.byte $9b, $84, $2c, $9b, $88, $2c, $9b, $84, $2a, $9b, $88, $2a, $9b, $2a, $9b, $2a, $9b, $84, $25, $9b, $88, $25, $9b, $84
	.byte $28, $9b, $88, $28, $9b, $84, $2d, $9b, $88, $2d, $9b, $2d, $9b
	.byte $41, $0a
	.word @song3ref688
@song3ref769:
	.byte $84, $25, $9b, $88, $25, $9b, $84, $25, $9b, $88, $25
@song3ref780:
	.byte $9b, $84, $27, $9b, $88, $27, $9b, $84, $23, $9b, $88, $23, $9b, $23, $9b, $23, $d7, $84, $23, $9b, $88, $23
	.byte $41, $09
	.word @song3ref780
	.byte $41, $2e
	.word @song3ref660
	.byte $84, $31, $9b, $88, $31
	.byte $41, $1b
	.word @song3ref729
	.byte $41, $0a
	.word @song3ref688
	.byte $41, $0d
	.word @song3ref769
	.byte $ff, $e5, $00, $85, $20, $ed, $00, $85, $27, $ed, $00, $85, $25, $ff, $ff, $db, $00, $87, $28, $ff, $e3, $00, $87, $27
	.byte $ff, $e3, $00, $87
@song3ref850:
	.byte $31, $8b, $31, $8d, $2c, $8b, $2c, $8d
@song3ref858:
	.byte $2f, $8b, $2f, $8d, $2c, $8b, $2c, $8d, $00, $b9, $31, $8b, $31
@song3ref871:
	.byte $8d, $2c, $8b, $2c
@song3ref875:
	.byte $8d, $31, $8b, $31, $8d, $2c, $8b, $2c, $8d, $00, $b9, $2f, $8b, $2f
	.byte $41, $0d
	.word @song3ref871
	.byte $41, $23
	.word @song3ref850
	.byte $d7, $2c, $8b, $2c, $8d, $33, $8b, $33, $8d, $33, $8b, $33
	.byte $41, $09
	.word @song3ref875
	.byte $41, $1f
	.word @song3ref858
	.byte $41, $0d
	.word @song3ref871
	.byte $41, $24
	.word @song3ref850
	.byte $27, $8b, $27, $8d, $27, $8b, $27, $8d, $2c, $8b, $2c, $8d, $2c, $8b, $2c, $85, $00, $85, $42
	.word @song3ch6loop
@song4ch0:
@song4ref1:
	.byte $71, $8a, $21, $8d, $72, $8d, $73, $8f, $74, $8d, $75, $8f, $76, $9d, $77, $bb, $78, $bb, $79, $89, $00, $81
@song4ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $bb, $7c, $86
@song4ref30:
	.byte $21, $8d, $24, $8b, $26, $8d, $00, $8b, $1f, $8d
@song4ref40:
	.byte $21, $8b, $24, $8d, $26, $8b, $00, $8d, $21, $8b
@song4ref50:
	.byte $24, $8d, $26, $8b
@song4ref54:
	.byte $47
@song4ref55:
	.byte $29, $8d, $28, $8b, $24, $8d, $26, $8b
	.byte $41, $0e
	.word @song4ref30
	.byte $00, $8b, $26, $8d, $00, $a9
	.byte $41, $08
	.word @song4ref54
	.byte $41, $0a
	.word @song4ref30
	.byte $7b
	.byte $41, $0a
	.word @song4ref40
	.byte $79
	.byte $41, $08
	.word @song4ref50
@song4ref86:
	.byte $77, $24, $8d, $26, $8b, $21, $8d, $24, $8b, $00, $ff, $93
@song4ref98:
	.byte $47, $ff, $ef, $47, $ff, $ef, $47, $ff, $ef, $47, $ff, $ef
	.byte $41, $08
	.word @song4ref98
	.byte $47, $ff, $ef, $47, $ff, $ef, $47, $bb, $7c
	.byte $41, $20
	.word @song4ref30
	.byte $41, $0e
	.word @song4ref30
	.byte $00, $8b, $26, $8d, $00, $a9
	.byte $41, $08
	.word @song4ref54
	.byte $41, $1a
	.word @song4ref30
@song4ref140:
	.byte $2b, $8b, $28, $8d, $29, $8b, $29, $8d, $28, $8b, $24, $8d, $21, $8b, $00, $8d, $24, $8b, $00, $9b, $26, $8d, $00, $a9
	.byte $47
@song4ref165:
	.byte $2b, $8d, $29, $8b, $28, $8d, $24, $8b
	.byte $41, $20
	.word @song4ref30
	.byte $41, $0e
	.word @song4ref30
	.byte $00, $8b, $26, $8d, $00, $a9
	.byte $41, $08
	.word @song4ref54
	.byte $41, $1a
	.word @song4ref30
	.byte $41, $1e
	.word @song4ref140
	.byte $29, $8b, $00, $ff, $b1, $47, $ff, $ef, $47, $ff, $ef, $47
	.byte $41, $0c
	.word @song4ref1
	.byte $42
	.word @song4ch0loop
@song4ch1:
@song4ref212:
	.byte $71, $8a, $34, $9b, $72, $9d, $74, $9d, $76, $9d, $78, $9d, $7a, $9d, $7c, $9d, $7e, $99, $7f, $83
@song4ch1loop:
	.byte $f1, $00, $fb, $ff, $ef, $ff, $ef, $ff, $ef, $88
@song4ref243:
	.byte $29, $ff, $ed, $28, $ff, $ed, $24, $ff, $ed, $21, $ff, $e9, $00, $81
	.byte $41, $09
	.word @song4ref243
	.byte $26, $ff, $e9, $00, $81, $ff, $ef, $ff, $ef
@song4ref269:
	.byte $26, $ff, $e9, $00, $81, $2d, $ff, $ed, $28, $ff, $ed, $24, $ff, $e9, $00, $81
	.byte $41, $08
	.word @song4ref269
	.byte $2b, $ff, $ed, $30
@song4ref292:
	.byte $ff, $ed, $f7, $00, $f5, $ff, $ef, $ff, $ef
	.byte $41, $09
	.word @song4ref212
	.byte $7f, $00, $81, $42
	.word @song4ch1loop
@song4ch2:
	.byte $ff, $ef
@song4ch2loop:
@song4ref313:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $ff, $ef, $ff, $ef, $82, $32, $ff, $ed, $39, $ff, $ed, $34, $ff, $ed, $30, $ff, $e9, $00, $81, $32, $ff, $ed, $39, $ff
	.byte $ed, $37, $ff, $ed, $3c
	.byte $41, $09
	.word @song4ref292
	.byte $ff, $ef, $42
	.word @song4ch2loop
@song4ch3:
	.byte $ff, $ef
@song4ch3loop:
	.byte $ff, $ef, $ff, $b3, $7e, $80, $0d, $8d, $00, $8b, $7c
@song4ref378:
	.byte $10, $89, $00, $81, $79, $11, $87, $00, $81, $f7, $7c
@song4ref389:
	.byte $10
@song4ref390:
	.byte $9b, $79, $13, $8d, $11, $8b, $10, $8d, $0e, $8b
@song4ref400:
	.byte $77, $0f, $9b
@song4ref403:
	.byte $7e, $0d, $8d, $00, $8b, $7b, $10, $9b, $7e, $0d, $8d, $00, $a9, $7b, $10, $9b, $00, $9b, $7e, $0d, $8d, $00, $8b, $7b
	.byte $41, $08
	.word @song4ref378
@song4ref430:
	.byte $7e, $0d, $8d, $00, $8b, $79, $13, $89, $00, $81, $11, $87, $00, $81, $10, $89, $00, $81
@song4ref448:
	.byte $11, $87, $00, $81, $0f, $87, $00, $91, $7b, $10, $9b, $00, $b9
@song4ref461:
	.byte $77, $0f, $89, $00, $81, $79, $10, $87, $00, $81
	.byte $41, $0d
	.word @song4ref403
	.byte $d7
@song4ref475:
	.byte $7e, $0d, $8d, $79, $10, $87, $00, $81, $11, $89, $00, $8f, $7e, $0d, $8d, $00, $a9, $7b
	.byte $41, $15
	.word @song4ref389
	.byte $8b, $77, $10, $8d, $0e, $87, $00, $81, $7b, $10, $9b, $00, $9b, $79, $10, $8d, $00, $8b, $77, $13, $8d, $79, $11, $8b
	.byte $41, $0c
	.word @song4ref430
	.byte $7e, $0d, $8d, $79
	.byte $41, $14
	.word @song4ref448
	.byte $41, $09
	.word @song4ref403
	.byte $9b, $75, $10, $83, $00, $81, $7b, $10, $9b, $00, $db
	.byte $41, $0d
	.word @song4ref475
	.byte $8b, $77, $13, $89, $00, $81, $13, $87, $00, $81, $7b
	.byte $41, $15
	.word @song4ref389
	.byte $8b, $77, $10, $8d, $0e, $85, $00, $83, $7b, $10, $9b, $00, $9b, $77, $10, $8d, $00, $8b, $13, $8d, $79, $11, $8b
	.byte $41, $14
	.word @song4ref430
	.byte $10, $87, $00, $91, $7b, $0f, $ab, $00, $a9
	.byte $41, $08
	.word @song4ref461
	.byte $41, $09
	.word @song4ref403
	.byte $9b, $77, $0e, $87, $00, $81, $7b, $0f, $9b, $79, $11, $89, $00, $81, $0e, $87, $00, $81, $77, $10, $89, $00, $81, $79
	.byte $10, $87, $00, $81, $7b, $10, $89, $00, $81, $7c
@song4ref636:
	.byte $10, $87, $00, $81
@song4ref640:
	.byte $7e, $0d, $8d, $00, $8b, $79, $0d, $89, $00, $81
@song4ref650:
	.byte $11, $87, $00, $81, $7b, $10, $9b
@song4ref657:
	.byte $00, $8d, $79, $10, $87, $00, $81, $7e, $0d, $8d, $7b, $10, $87, $00, $81, $79, $0d, $8d, $00, $8b, $7b, $10, $9b, $79
	.byte $11, $89, $00, $81
	.byte $41, $08
	.word @song4ref636
@song4ref688:
	.byte $7b, $10, $9b
@song4ref691:
	.byte $7e, $0d, $8d, $00, $8b, $79, $11, $89, $00, $81, $77, $0e, $87, $00, $81, $7b, $10, $9b, $00, $8d, $77, $13, $87, $00
	.byte $81, $79, $11, $89, $00, $81, $10, $87, $00, $81, $17, $9b
	.byte $41, $20
	.word @song4ref640
	.byte $41, $08
	.word @song4ref657
	.byte $00, $8b, $7b, $10, $9b, $7e, $0d, $8d, $00, $9b, $79
	.byte $41, $08
	.word @song4ref650
	.byte $79, $13, $87, $00, $81, $17, $9b, $77, $0e, $89, $00, $81, $79
	.byte $41, $24
	.word @song4ref636
	.byte $00, $8d, $77
	.byte $41, $08
	.word @song4ref636
	.byte $41, $20
	.word @song4ref688
	.byte $41, $20
	.word @song4ref640
	.byte $00, $8d, $77
	.byte $41, $08
	.word @song4ref636
	.byte $41, $12
	.word @song4ref688
	.byte $79, $13, $87, $00, $81, $17, $9b, $77, $13, $89, $00, $8f, $7e, $0d, $8d, $00, $a9, $0d, $8d, $00, $a9, $7c, $0f, $ab
	.byte $00, $a9
	.byte $41, $0c
	.word @song4ref400
	.byte $7c, $0f, $b9, $00, $b9
	.byte $41, $08
	.word @song4ref691
	.byte $10, $87, $00, $81, $7e, $0d, $8d, $00, $a9, $7c, $0f
	.byte $41, $14
	.word @song4ref390
	.byte $8b, $79, $10, $89, $00, $81, $0e, $87, $00, $81, $7b, $0f, $ab, $00, $c7, $42
	.word @song4ch3loop
@song4ch4:
	.byte $25, $8d, $00, $ff, $dd
@song4ch4loop:
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $ff, $ef, $ff, $ef, $42
	.word @song4ch4loop
@song4ch5:
	.byte $ff, $ef
@song4ch5loop:
	.byte $7d, $84
@song4ref889:
	.byte $1a, $89, $00, $81, $1d, $87, $00, $81, $1f, $89, $00, $81, $1a, $87, $00, $81, $7e
@song4ref906:
	.byte $24, $89, $00, $81, $1a
@song4ref911:
	.byte $87, $00, $81
@song4ref914:
	.byte $1d, $89, $00, $81, $1c, $87, $00, $81
@song4ref922:
	.byte $21, $89, $00, $81, $24, $87, $00, $81, $1a, $89, $00, $81, $1c
	.byte $41, $0b
	.word @song4ref911
@song4ref938:
	.byte $24, $89, $00, $81, $1c, $87, $00, $81
	.byte $41, $10
	.word @song4ref889
	.byte $41, $08
	.word @song4ref938
@song4ref952:
	.byte $1d, $89, $00, $81, $1f, $87, $00, $81, $1a, $89, $00, $ad, $2e, $89, $00, $81, $2d, $87, $00, $81, $2b, $89, $00, $81
	.byte $2d, $87, $00, $81
	.byte $41, $10
	.word @song4ref889
	.byte $41, $1d
	.word @song4ref906
	.byte $41, $0b
	.word @song4ref911
	.byte $41, $08
	.word @song4ref938
	.byte $41, $10
	.word @song4ref889
	.byte $41, $08
	.word @song4ref938
	.byte $41, $0c
	.word @song4ref952
	.byte $7b, $2e, $8d, $79, $2d, $8b, $77, $2b, $8d, $79, $2d, $8b, $7d
	.byte $41, $2d
	.word @song4ref889
	.byte $41, $0b
	.word @song4ref911
	.byte $41, $08
	.word @song4ref938
	.byte $41, $10
	.word @song4ref889
	.byte $41, $08
	.word @song4ref914
@song4ref1029:
	.byte $1a, $89, $00, $81, $21, $87, $00, $81, $1c, $89, $00, $ad, $7b
	.byte $41, $08
	.word @song4ref165
	.byte $7e
	.byte $41, $0b
	.word @song4ref889
	.byte $8f
	.byte $41, $08
	.word @song4ref906
	.byte $1c, $89, $00, $8f
	.byte $41, $0d
	.word @song4ref922
	.byte $87, $00, $81
	.byte $41, $08
	.word @song4ref952
@song4ref1066:
	.byte $1c, $89, $00, $81, $1d, $87, $00, $81
	.byte $41, $0c
	.word @song4ref889
@song4ref1077:
	.byte $1d, $87, $00, $81, $1c, $89, $00, $81, $24, $87, $00, $81, $21, $89, $00, $81, $1c, $87, $00, $81, $1a, $89, $00, $ad
	.byte $7b, $2e, $8d, $2d, $8b, $2b, $8d, $2d, $87, $00, $81, $7d
	.byte $41, $2d
	.word @song4ref889
	.byte $41, $0b
	.word @song4ref911
	.byte $41, $08
	.word @song4ref938
	.byte $41, $10
	.word @song4ref889
	.byte $41, $08
	.word @song4ref914
	.byte $41, $0c
	.word @song4ref1029
	.byte $7b
	.byte $41, $08
	.word @song4ref165
	.byte $7e
	.byte $41, $0b
	.word @song4ref889
	.byte $8f
	.byte $41, $08
	.word @song4ref906
	.byte $1c, $89, $00, $8f
	.byte $41, $0d
	.word @song4ref922
	.byte $87, $00, $81
	.byte $41, $08
	.word @song4ref952
	.byte $41, $08
	.word @song4ref1066
	.byte $41, $0c
	.word @song4ref889
	.byte $41, $17
	.word @song4ref1077
	.byte $e9, $ff, $ef, $ff, $ef
@song4ref1170:
	.byte $7d, $1a, $9b, $7b, $1a, $8d, $1a, $8b, $7d, $1a, $9b, $7b, $1a, $8d, $1a, $8b
	.byte $41, $08
	.word @song4ref1170
	.byte $7b, $21, $8d, $7a
@song4ref1193:
	.byte $21
@song4ref1194:
	.byte $8b, $7d, $22, $9b, $7b, $22, $8d, $22, $8b, $7d, $22, $9b, $7b, $22, $8d, $22
	.byte $41, $0c
	.word @song4ref1194
@song4ref1213:
	.byte $8b, $7d, $1f, $9b, $7b, $1f, $8d, $1f, $8b, $7d, $1f, $9b, $7b, $1f, $8d, $1f
	.byte $41, $0c
	.word @song4ref1213
@song4ref1232:
	.byte $8b
@song4ref1233:
	.byte $7d, $21, $9b, $7b, $21, $8d, $21, $8b, $7d, $21, $9b, $7b, $21, $8d, $21, $8b, $7d, $24, $9b, $7b, $24, $8d, $24, $8b
	.byte $7d, $24, $9b, $7b, $24, $8d, $24, $8b
	.byte $41, $0c
	.word @song4ref1170
	.byte $7d, $1a, $9b, $7b, $1a, $8d, $1a, $8b, $7d, $21, $9b, $7b, $21, $8d
	.byte $41, $0d
	.word @song4ref1193
	.byte $41, $0c
	.word @song4ref1194
	.byte $41, $0c
	.word @song4ref1213
	.byte $41, $0c
	.word @song4ref1213
	.byte $41, $0d
	.word @song4ref1232
	.byte $41, $0c
	.word @song4ref1233
	.byte $00, $ff, $ed, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song4ch5loop
@song4ch6:
	.byte $ff, $ef
@song4ch6loop:
	.byte $7c, $82
@song4ref1317:
	.byte $21, $8d, $24, $8b
@song4ref1321:
	.byte $26, $8f, $00, $89, $1f, $8d
@song4ref1327:
	.byte $21, $8b, $24, $8d, $26, $8d, $00, $8b, $21, $8b, $24, $8d, $26, $8b
	.byte $41, $08
	.word @song4ref55
	.byte $41, $0d
	.word @song4ref1317
	.byte $8f, $00, $89, $26, $9b, $00, $9b
	.byte $41, $08
	.word @song4ref55
	.byte $41, $0a
	.word @song4ref1317
	.byte $7b
	.byte $41, $0a
	.word @song4ref1327
	.byte $79, $24, $8d, $26, $8b, $29, $8d, $28, $8b
	.byte $41, $08
	.word @song4ref86
	.byte $75
	.byte $41, $09
	.word @song4ref1321
	.byte $8f, $00, $ff, $81
	.byte $41, $08
	.word @song4ref313
	.byte $41, $08
	.word @song4ref313
	.byte $ff, $ef, $ff, $ef, $7c
	.byte $41, $18
	.word @song4ref1317
	.byte $41, $08
	.word @song4ref55
	.byte $41, $0d
	.word @song4ref1317
	.byte $8f, $00, $89, $26, $8f, $00, $a7
	.byte $41, $08
	.word @song4ref55
	.byte $41, $18
	.word @song4ref1317
	.byte $29, $8d
	.byte $41, $0d
	.word @song4ref140
@song4ref1422:
	.byte $8d, $00, $8b, $24, $8d, $00, $99, $26, $8f, $00, $a7
	.byte $41, $08
	.word @song4ref165
	.byte $41, $18
	.word @song4ref1317
	.byte $41, $08
	.word @song4ref55
	.byte $41, $0d
	.word @song4ref1317
	.byte $8f, $00, $89, $26, $8f, $00, $a7
	.byte $41, $08
	.word @song4ref55
	.byte $41, $18
	.word @song4ref1317
	.byte $29, $8d
	.byte $41, $0d
	.word @song4ref140
	.byte $41, $0b
	.word @song4ref1422
	.byte $2b, $8d, $29, $8b, $28, $8d, $29, $8b, $81, $00, $ff, $eb, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song4ch6loop
@song5ch0:
	.byte $ff, $ff, $df
@song5ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $df, $47, $ff, $ff, $df, $47, $ff, $ff, $df, $47
	.byte $ff, $ff, $df, $47, $84, $29, $ff, $f9, $00, $89, $27, $9d, $00, $89, $2c, $9d, $00, $89, $47, $25, $ff, $cb, $00, $8b
	.byte $24, $9d, $00, $89, $25, $9d, $00, $89, $2c, $9d, $00, $89, $47, $2c, $ff, $f9, $00, $89, $25, $c9, $00, $89, $47, $27
	.byte $ff, $f9, $00, $89, $24
@song5ref73:
	.byte $c9, $00, $89, $47
@song5ref77:
	.byte $1e, $ff, $9f, $00, $8b, $20, $ff, $9f, $00, $8b, $47, $25, $ff, $f7, $00, $8b, $1d
	.byte $41, $13
	.word @song5ref73
	.byte $41, $0d
	.word @song5ref73
	.byte $47
@song5ref101:
	.byte $22, $ff, $f7, $00, $8b, $1d, $c9, $00, $89, $47, $1e, $ff, $ff, $d1, $00, $89, $47, $20, $ff, $d9, $00, $ff, $81, $42
	.word @song5ch0loop
@song5ch1:
	.byte $ff, $af, $84, $25, $ff, $ad
@song5ch1loop:
	.byte $ff, $ff, $df
@song5ref137:
	.byte $00, $ff, $ff, $dd
@song5ref141:
	.byte $ff, $ff, $df, $ff, $ff, $df, $ff, $ff, $df
	.byte $41, $09
	.word @song5ref141
	.byte $ab, $84
@song5ref155:
	.byte $2a, $a9, $2e, $a9, $2a, $9d, $00, $b5, $2c
@song5ref164:
	.byte $c7, $00, $8b, $2c, $9d, $00, $89, $2c, $a9, $29, $a9, $2c, $a9, $29, $9d, $00, $89, $2c, $9d, $00, $89, $2c, $eb, $29
	.byte $87, $00, $89, $2a, $a9, $25, $a9, $2e, $a9, $25, $9d, $00, $89, $2c, $a9, $27
	.byte $41, $15
	.word @song5ref164
@song5ref207:
	.byte $25, $93, $2c, $b3, $00, $89, $2c, $93, $25, $87, $00, $89, $ab
	.byte $41, $10
	.word @song5ref155
	.byte $29, $a9, $25, $9d, $00, $89, $2e, $a9, $25, $9d, $00, $89, $29, $9d, $00, $89, $25, $93, $2c, $b3, $00, $89, $2c, $9d
	.byte $00, $89, $2a, $93, $2e, $f5, $00, $f7, $2e, $c9, $00, $89, $2c, $ff, $a1, $00, $89, $2c, $a9
	.byte $41, $0c
	.word @song5ref207
	.byte $42
	.word @song5ch1loop
@song5ch2:
	.byte $ff, $ff, $df
@song5ch2loop:
	.byte $84
@song5ref277:
	.byte $25, $ff, $ff, $85, $24, $d5, $22, $ff, $ff, $85, $20, $d5, $1e, $ff, $ff, $dd, $20, $ff, $ad, $20, $d5, $20, $d5
	.byte $41, $17
	.word @song5ref277
	.byte $41, $0a
	.word @song5ref77
@song5ref306:
	.byte $25, $ff, $f7, $00, $8b, $1d, $c9, $00, $89
	.byte $41, $0a
	.word @song5ref77
	.byte $41, $09
	.word @song5ref306
	.byte $41, $0a
	.word @song5ref77
	.byte $41, $09
	.word @song5ref101
	.byte $1e, $ff, $ff, $d1, $00, $89, $20, $ff, $d9, $00, $ff, $81, $42
	.word @song5ch2loop
@song5ch3:
	.byte $ff, $ff, $df
@song5ch3loop:
	.byte $41, $09
	.word @song5ref141
	.byte $41, $09
	.word @song5ref141
	.byte $ff, $ff, $df, $ff, $ff, $df, $80, $12, $a3, $00, $83
@song5ref363:
	.byte $12, $93, $12, $93, $12
@song5ref368:
	.byte $a3, $00, $83
@song5ref371:
	.byte $12, $93
@song5ref373:
	.byte $12, $93, $12, $a9, $12, $93, $12, $93, $12, $a9
	.byte $41, $0c
	.word @song5ref371
@song5ref386:
	.byte $12, $93, $12, $93, $12, $93, $00, $93, $12, $93, $00, $93, $0f, $a9, $12, $8f, $00, $81, $12, $8f, $00, $81, $12, $93
	.byte $00, $93
	.byte $41, $0a
	.word @song5ref386
	.byte $12, $93, $12, $93, $00, $93
	.byte $41, $0a
	.word @song5ref386
	.byte $41, $0a
	.word @song5ref373
	.byte $41, $09
	.word @song5ref363
	.byte $a3, $00, $83, $0f, $a9
	.byte $41, $0d
	.word @song5ref363
	.byte $41, $0f
	.word @song5ref368
	.byte $41, $0c
	.word @song5ref371
	.byte $41, $09
	.word @song5ref363
	.byte $a3, $00, $83, $0f, $a9
	.byte $41, $0d
	.word @song5ref363
	.byte $41, $0f
	.word @song5ref368
	.byte $41, $0c
	.word @song5ref371
	.byte $12, $93, $12, $93, $12, $93, $00, $eb, $12, $93, $12, $93, $42
	.word @song5ch3loop
@song5ch4:
	.byte $25, $83, $00, $ff, $ff, $d7
@song5ch4loop:
	.byte $41, $09
	.word @song5ref141
	.byte $41, $09
	.word @song5ref141
	.byte $41, $09
	.word @song5ref141
	.byte $41, $09
	.word @song5ref141
	.byte $41, $09
	.word @song5ref141
	.byte $ff, $ff, $df, $42
	.word @song5ch4loop
@song5ch5:
	.byte $ff, $af, $82, $38, $d5, $36, $d5
@song5ch5loop:
	.byte $82, $35
@song5ref514:
	.byte $87, $00, $89, $2c, $87, $00, $89
@song5ref521:
	.byte $31, $87, $00, $89, $2c, $87, $00, $89, $33
@song5ref530:
	.byte $87, $00, $89, $2c, $87
@song5ref535:
	.byte $00, $89, $35, $87, $00, $89, $2c, $87, $00, $89, $36
	.byte $41, $0f
	.word @song5ref530
	.byte $41, $18
	.word @song5ref521
	.byte $41, $10
	.word @song5ref521
@song5ref555:
	.byte $38, $87, $00, $89, $2c, $87, $00, $89, $36
	.byte $41, $0f
	.word @song5ref530
	.byte $41, $18
	.word @song5ref521
	.byte $41, $19
	.word @song5ref521
	.byte $41, $0f
	.word @song5ref530
	.byte $41, $10
	.word @song5ref521
	.byte $31
	.byte $41, $0b
	.word @song5ref514
@song5ref583:
	.byte $33, $87, $00, $89, $38, $87, $00, $89, $31, $87, $00, $89, $33, $87, $00, $89, $38, $87, $00, $89, $35, $b1, $00, $8b
	.byte $33, $81, $00, $31, $81, $00, $89, $33, $9d, $00, $89, $30, $9d
	.byte $41, $0a
	.word @song5ref535
	.byte $41, $19
	.word @song5ref521
	.byte $41, $0f
	.word @song5ref530
	.byte $41, $18
	.word @song5ref521
	.byte $41, $10
	.word @song5ref521
	.byte $41, $09
	.word @song5ref555
	.byte $41, $0f
	.word @song5ref530
	.byte $41, $18
	.word @song5ref521
	.byte $41, $19
	.word @song5ref521
	.byte $41, $0f
	.word @song5ref530
	.byte $41, $10
	.word @song5ref521
	.byte $31
	.byte $41, $0b
	.word @song5ref514
	.byte $41, $23
	.word @song5ref583
	.byte $2c, $9d, $00, $89
@song5ref664:
	.byte $31, $ff, $9f, $00, $8b, $33, $f3, $00, $8b, $2c, $87, $00, $89, $33, $87, $00, $89, $35, $9d, $00, $89, $36, $9d, $00
	.byte $89, $35, $9d, $00, $89, $31, $9d, $00, $89, $31, $b3, $00, $9f, $33, $c9, $00, $89, $31, $f3, $00, $8b, $2c, $87, $00
	.byte $89, $31, $87, $00, $89, $33, $c9, $00, $89, $38, $c9, $00, $89, $35, $ff, $f9, $00, $e1
	.byte $41, $22
	.word @song5ref664
	.byte $c9, $00, $89, $38, $c9, $00, $89, $38, $ff, $f9, $00, $89, $31, $c9, $00, $89, $31, $f3, $00, $8b, $30, $87, $00, $89
	.byte $2e, $87, $00, $89, $30, $a9, $25, $93, $2c, $93, $31, $93, $30, $93, $2c, $93, $25, $93, $42
	.word @song5ch5loop
@song5ch6:
	.byte $ff, $af, $86, $24, $d5, $27, $d5
@song5ch6loop:
	.byte $86
@song5ref787:
	.byte $20, $93, $25, $93, $27, $93, $25, $93, $2c, $93, $25, $93, $27, $93, $29, $93
	.byte $41, $0e
	.word @song5ref787
	.byte $2c, $93
	.byte $41, $10
	.word @song5ref787
	.byte $41, $0e
	.word @song5ref787
	.byte $2c, $93
	.byte $41, $10
	.word @song5ref787
@song5ref819:
	.byte $20, $93, $25, $93, $27, $93, $20, $93, $2a, $93, $29, $93, $25, $93, $20, $93, $20, $93, $25, $93, $2c, $93, $24, $93
	.byte $25, $93, $20, $93, $24, $93, $25, $93, $2a
@song5ref852:
	.byte $d5, $27, $93, $27, $93, $27, $93, $27, $93
	.byte $41, $10
	.word @song5ref787
	.byte $41, $0e
	.word @song5ref787
	.byte $2c, $93
	.byte $41, $10
	.word @song5ref787
	.byte $41, $0e
	.word @song5ref787
	.byte $2c, $93
	.byte $41, $10
	.word @song5ref787
	.byte $41, $20
	.word @song5ref819
	.byte $27
	.byte $41, $09
	.word @song5ref852
	.byte $41, $0d
	.word @song5ref137
	.byte $41, $09
	.word @song5ref141
	.byte $ff, $ff, $df, $42
	.word @song5ch6loop
