; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; DPCM Delta Counter effect is used, you must set FAMISTUDIO_USE_DELTA_COUNTER = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_pwaa_music_v2_5=music_data_pwaa_music_v2_5
.endif

music_data_pwaa_music_v2_5:
	.byte 3
	.word @instruments
	.word @samples-5
; 00 : Courtroom Lounge
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Light and Shadow of the Film Studio
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Class Trial
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_pwaa_music_v2_5
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env5,@env6,@env0 ; 00 : Lead 2
	.word @env1,@env5,@env6,@env2 ; 01 : Lead 1
	.word @env4,@env5,@env6,@env0 ; 02 : Fade
	.word @env7,@env5,@env6,@env0 ; 03 : Kick

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ce,$cd,$cc,$00,$04
@env2:
	.byte $00,$c0,$c1,$c2,$02,$c1,$c0,$bf,$be,$02,$bf,$00,$01
@env3:
	.byte $00,$cb,$cd,$cf,$cc,$00,$04
@env4:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $7f,$00,$00
@env7:
	.byte $00,$cf,$ca,$c6,$c3,$c1,$c0,$00,$06

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $74, $51, $01, $b0, $4f, $01, $82, $19, $ff, $ff, $8d
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref16:
	.byte $7b, $20, $8f, $1e, $8d, $20, $8f, $23, $8d, $22, $8f, $1e, $8d, $20, $c1, $51, $ff, $70, $e5, $48, $ff, $ff, $89, $00
	.byte $7b, $83, $48, $ff, $ff, $8f, $48, $ff, $cb, $76, $51, $03, $b0, $1b, $c1, $48
@song0ref56:
	.byte $20, $8f, $1e, $8d, $23, $8f, $25, $8d, $22, $8f, $1e, $8d, $20, $c1, $51, $ff, $70, $e5, $48, $ff, $ff, $89, $00, $83
	.byte $48, $7b, $ff, $ff, $8f, $48, $76, $51, $01, $b0, $19, $ff, $85, $1b, $ff, $85
@song0ref96:
	.byte $48
@song0ref97:
	.byte $20, $8f, $1e, $8d, $20, $8f, $25, $8d, $20, $8f, $1e, $8d, $20, $8f, $1e, $8d, $20, $8f, $23, $8d, $22, $8f, $1e, $8d
	.byte $20, $c1, $48, $51, $ff, $70, $ff, $cb, $7b, $00, $c1
	.byte $41, $1e
	.word @song0ref96
	.byte $48, $ff, $ff, $8f, $48, $74, $51, $01, $b0, $4f, $01, $19, $ff, $ff, $8d, $42
	.word @song0ch0loop
@song0ch1:
	.byte $74, $51, $01, $b0, $4f, $01, $82, $20, $ff, $ff, $8d
@song0ch1loop:
	.byte $7b
@song0ref166:
	.byte $1b, $8f, $19, $8d, $1b, $8f, $20, $8d, $1e, $8f, $1b, $8d, $19, $c1, $51, $ff, $70, $e5, $ff, $ff, $89, $00, $7b, $83
	.byte $ff, $ff, $8f, $ff, $cb, $76, $51, $03, $b0, $20, $c1
	.byte $41, $17
	.word @song0ref166
	.byte $76, $51, $01, $b0, $1e, $ff, $85, $20, $ff, $85, $00
@song0ref215:
	.byte $8f
@song0ref216:
	.byte $19, $8d, $1b, $8f, $20, $8d, $1b, $8f, $19, $8d, $1b, $8f, $19, $8d, $1b, $8f, $1e, $8d, $20, $8f, $19, $8d, $19, $c1
	.byte $51, $ff, $70, $ff, $cb, $7b, $00, $c1, $1b
	.byte $41, $1d
	.word @song0ref215
	.byte $ff, $ff, $8f, $74, $51, $01, $b0, $4f, $01, $20, $ff, $ff, $8d, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $8f
@song0ch2loop:
	.byte $82, $20, $8f, $23, $8d, $25, $8f, $20, $8d, $1e, $8f, $23, $8d, $21, $ff, $a1, $00, $83, $21, $8f, $23, $8d, $25, $8f
	.byte $1e, $8d, $00, $8f, $20, $8d, $23
@song0ref303:
	.byte $8f, $25, $8d, $23, $8f, $25, $8d, $28, $8f, $00, $8d, $26, $27, $bf, $00, $ff, $ff, $8d, $ff, $ff, $8f, $20, $8f, $23
	.byte $8d, $25, $8f, $1e, $8d, $23, $8f, $25, $8d, $1e, $ff, $a1, $00, $83, $23, $8f, $25, $8d, $28, $8f, $2a, $8d, $00, $8f
	.byte $27, $83, $28, $87, $27
	.byte $41, $15
	.word @song0ref303
	.byte $21, $e3, $23, $e3, $25, $bb, $00, $83, $25, $8f, $28, $8d, $2a, $8f, $25, $91, $00, $df, $2a, $8f, $28, $8d, $27, $8f
	.byte $23, $8d, $20, $9f, $1e, $dd, $00, $83, $20, $e3, $21, $c1, $ff, $c5, $00, $c7, $ff, $ff, $8f, $ff, $ff, $8f, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $8f
@song0ch3loop:
	.byte $7c, $86
@song0ref414:
	.byte $09, $8f, $00, $af, $09, $8f, $00, $af, $09, $8f, $00, $af, $09, $8f, $00, $af
	.byte $41, $10
	.word @song0ref414
	.byte $41, $0f
	.word @song0ref414
	.byte $8d, $78, $0f, $8f, $00, $8d, $7c, $09, $8f, $00, $af, $09, $8f, $00, $af, $09, $8f, $74, $0f, $8d, $78, $11, $9f, $0f
	.byte $8f, $00, $af, $7c
	.byte $41, $10
	.word @song0ref414
	.byte $41, $10
	.word @song0ref414
	.byte $09, $8f, $77, $09, $8d, $00, $9f, $7c, $09, $8f, $00, $8d, $78, $0f, $8f, $00, $8d, $7c, $09, $8f, $74, $0f, $8d, $78
	.byte $11, $9f, $0f, $8f, $00, $af, $7c, $09, $8f, $00, $af, $09, $8f, $00, $af, $09, $8f, $00, $8d, $79, $0c, $8f, $00, $8d
	.byte $7c, $09, $8f, $00, $8d, $0c, $89, $00, $83, $79, $0c, $87, $00, $83
@song0ref532:
	.byte $7c, $09, $8f, $00, $af, $09, $8f, $00, $af, $09, $8f, $00, $af, $0c, $89, $76, $0c, $8b, $00, $a7
	.byte $41, $11
	.word @song0ref532
	.byte $85, $7a, $09, $8f, $00, $8d
	.byte $41, $12
	.word @song0ref532
	.byte $41, $12
	.word @song0ref532
	.byte $7c
	.byte $41, $10
	.word @song0ref414
	.byte $41, $0f
	.word @song0ref414
	.byte $8d, $7a, $0c, $89, $00, $83, $75, $0c, $87, $00, $83, $42
	.word @song0ch3loop
@song0ch4:
	.byte $52, $80, $ff, $ff, $8f
@song0ch4loop:
@song0ref594:
	.byte $ff, $ff, $8f, $ff, $ff, $8f, $ff, $ff, $8f, $ff, $ff, $8f, $ff, $ff, $8f
	.byte $41, $0f
	.word @song0ref594
	.byte $ff, $ff, $8f, $ff, $ff, $8f, $ff, $ff, $8f, $ff, $ff, $8f, $42
	.word @song0ch4loop
@song0ch5:
	.byte $74, $51, $01, $b0, $4f, $01, $80, $14, $ff, $ff, $8d
@song0ch5loop:
	.byte $41, $0f
	.word @song0ref16
	.byte $ff, $ff, $89, $00, $7b, $83, $ff, $ff, $8f, $ff, $ff, $8f
	.byte $41, $0f
	.word @song0ref56
	.byte $ff, $ff, $89, $00, $83, $7b, $ff, $ff, $8f, $ff, $ff, $8f
	.byte $41, $1a
	.word @song0ref97
	.byte $51, $ff, $70, $ff, $cb, $7b, $00, $c1
	.byte $41, $1a
	.word @song0ref97
	.byte $51, $ff, $70, $ff, $cb, $7b, $00, $c1, $ff, $ff, $8f, $74, $51, $01, $b0, $4f, $01, $14, $ff, $ff, $8d, $42
	.word @song0ch5loop
@song0ch6:
	.byte $ff, $ff, $8f
@song0ch6loop:
	.byte $7b, $80
	.byte $41, $18
	.word @song0ref166
	.byte $ff, $8f
	.byte $41, $18
	.word @song0ref166
	.byte $ff, $8f, $91
	.byte $41, $1d
	.word @song0ref216
	.byte $41, $1d
	.word @song0ref215
	.byte $ff, $ff, $8f, $ff, $ff, $8f, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7f, $4f, $01, $84
@song1ref9:
	.byte $19, $9d, $1c, $9d, $1b, $9d, $1c, $9b, $1e, $9d, $1c, $9d, $1b, $9d, $1c, $9b, $48, $19, $9d, $1c, $9d, $1b, $9d, $17
	.byte $9b, $78, $19, $9d, $1c, $9d, $1b, $9d, $17, $9b, $48, $77, $19, $9d, $76, $1c, $9d, $75, $1b, $9d, $74, $17, $9b, $72
	.byte $19, $9d, $00, $db, $48, $fd, $7f, $19, $9d, $1c, $9d, $1b, $9d, $1c, $9b, $48, $1e, $9d, $1c, $9d, $1b, $9d, $1c, $9b
	.byte $19, $9d, $1c, $9d, $1b, $9d, $17, $9b, $48, $78, $19, $9d, $1c, $9d, $1b, $9d, $17, $9b, $77, $19, $9d, $76, $1c, $9d
	.byte $75, $1b, $9d, $74, $17, $9b, $48, $72, $19, $9d, $00, $ff, $d9, $48, $7f, $4f, $01
	.byte $41, $5a
	.word @song1ref9
	.byte $48, $ff, $fb, $48, $ff, $fb, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $79, $4f, $02, $84
@song1ref139:
	.byte $19, $9d, $20, $9d, $25, $9d, $20, $9b, $78, $28, $9d, $79, $20, $9d, $78, $27, $9d, $79, $20, $9b, $19, $9d, $20, $9d
	.byte $23, $9d, $1e, $9b, $15, $9d, $1c, $9d, $21, $9d, $1c, $9b, $25, $9d, $1c, $9d, $21, $9d, $1c, $9b, $15, $fb, $bf, $00
	.byte $bb
	.byte $41, $20
	.word @song1ref139
@song1ref191:
	.byte $78, $28, $9d, $79, $1c, $9d, $25, $9d, $1c, $9b, $15, $ff, $bb, $00, $bb, $4f, $02
	.byte $41, $2d
	.word @song1ref139
	.byte $41, $20
	.word @song1ref139
	.byte $41, $0d
	.word @song1ref191
	.byte $ff, $fb, $ff, $fb, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80
@song1ref226:
	.byte $19, $ff, $f9, $bf, $17, $bb, $15, $fb, $ff, $fb, $bf, $00, $bb, $19, $fb, $ff, $bd, $17, $bb, $15, $ff, $f9, $ff, $bd
	.byte $00, $bb
	.byte $41, $1a
	.word @song1ref226
	.byte $ff, $fb, $fd, $18, $fb, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $7f, $86, $05, $99, $00, $ff, $dd, $df, $7c, $05, $97, $00, $81, $7f, $05, $99, $00, $df, $ff, $fb, $fd, $05, $99, $00
	.byte $df, $ff, $dd, $7c, $05, $97, $00, $81, $7f, $05, $99, $00, $ff, $dd, $ff, $dd, $7b, $0e, $87, $00, $83, $7a, $0d, $85
	.byte $00, $83, $7f, $05, $99, $00, $81, $7c, $05, $99, $00, $81, $7b, $0e
@song1ref326:
	.byte $9d, $00, $bb
@song1ref329:
	.byte $7f
@song1ref330:
	.byte $05, $99, $00, $81, $7b, $0e, $9d, $00, $9b
@song1ref339:
	.byte $7f, $05, $99, $00, $81, $7c, $05, $99, $00, $81, $7b, $0e, $99, $00, $9f
	.byte $41, $0c
	.word @song1ref339
	.byte $9f, $7f, $05, $99, $00, $81, $7b, $0e, $9d, $00, $8d, $79, $0e, $87, $00, $81
	.byte $41, $0c
	.word @song1ref339
	.byte $9f
	.byte $41, $11
	.word @song1ref329
	.byte $9d, $00, $9b, $9f
	.byte $41, $13
	.word @song1ref329
	.byte $81, $7c, $05, $89, $00, $81, $7b, $0e, $87, $00, $81
	.byte $41, $0b
	.word @song1ref339
	.byte $bf, $7c
	.byte $41, $13
	.word @song1ref330
	.byte $bf, $7c
	.byte $41, $11
	.word @song1ref330
	.byte $41, $0f
	.word @song1ref326
	.byte $79, $0e, $87, $00, $83, $7a, $0d, $87, $00, $83, $7b, $0e, $99, $00, $91, $79, $0e, $85, $00, $a3, $7f, $05, $99, $00
	.byte $81, $7b, $0e, $9d, $00, $9b, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $52, $80
@song1ref450:
	.byte $ff, $fb, $ff, $fb, $fd
@song1ref455:
	.byte $52, $80, $8b, $52, $88, $8d, $52, $90, $89, $52, $98, $8b, $52, $a0, $8d, $52, $a8, $8b, $52, $b0, $89, $52, $b8, $8b
	.byte $52, $c0, $8d, $52, $c8, $89, $52, $d0, $85, $83
@song1ref489:
	.byte $52, $d8, $8b, $52, $e0, $8d, $52, $e8, $8b, $52, $f0, $89, $52, $f8, $8b, $52, $ff, $83, $52, $f8, $85, $52, $f0, $83
	.byte $52, $e6, $81, $52, $e0, $83, $52, $d8, $85, $52, $d0, $83, $52, $c6, $81, $52, $c0, $83, $52, $b8, $85, $52, $b0, $83
	.byte $52, $a6, $81, $52, $a0, $83, $52, $98, $83, $52, $90, $83, $52, $88, $81, $52, $80, $fd, $ff, $fb, $ff, $fb
	.byte $41, $0a
	.word @song1ref455
	.byte $52, $d0, $89
	.byte $41, $13
	.word @song1ref489
	.byte $52, $90, $81, $52, $88, $81, $52, $80, $81
	.byte $41, $2b
	.word @song1ref450
	.byte $41, $0a
	.word @song1ref455
	.byte $52, $d0, $89
	.byte $41, $13
	.word @song1ref489
	.byte $52, $90, $81, $52, $88, $81, $52, $80, $81, $ff, $fb, $ff, $fb, $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $78, $4f, $02, $82
@song1ref610:
	.byte $20, $ff, $f9, $bf, $1e, $bb, $20, $fb, $51, $ff, $00, $ff, $fb, $fd, $78, $23, $fb, $ff, $bd, $1e, $bb, $20, $fb, $51
	.byte $ff, $00, $fd, $ff, $fb, $78
	.byte $41, $16
	.word @song1ref610
	.byte $78, $00, $ff, $f9, $fd, $1e, $fb, $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $78, $4f, $02, $82
@song1ref658:
	.byte $19, $ff, $f9, $bf, $17, $bb, $19, $fb, $51, $ff, $00, $ff, $fb, $fd, $78, $1e, $fb, $ff, $bd, $1c, $bb, $19, $fb, $51
	.byte $ff, $00, $fd, $ff, $fb, $78
	.byte $41, $16
	.word @song1ref658
	.byte $78, $00, $ff, $f9, $fd, $1b, $fb, $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $75, $51, $02, $c0, $84
@song2ref10:
	.byte $25, $9b, $00, $83, $28, $9b, $00, $83, $2a, $9b, $00, $83, $20, $91, $89, $00, $83
@song2ref27:
	.byte $28, $9b, $00, $83, $2a, $9b, $00, $83, $23, $8f, $51, $fe, $50, $8b, $00, $83, $28, $9b, $00, $83, $48
@song2ref48:
	.byte $27, $9b, $00, $83, $28
@song2ref53:
	.byte $9b, $00, $83, $25, $9b, $00, $83, $51, $02, $c0, $28, $9b, $00, $83
@song2ref67:
	.byte $2a, $9b, $00, $83, $20, $9b, $00, $83, $28, $9b, $00, $83, $2a, $9b, $00, $83, $48
@song2ref84:
	.byte $24, $8f, $51, $fe, $50, $8b, $00, $83, $28, $9b, $00, $83, $27, $9b, $00, $83, $24
	.byte $41, $13
	.word @song2ref53
	.byte $48
	.byte $41, $11
	.word @song2ref27
	.byte $41, $10
	.word @song2ref48
	.byte $48
	.byte $41, $10
	.word @song2ref67
	.byte $41, $0e
	.word @song2ref84
	.byte $9b, $00, $83, $48, $51, $02, $c0
	.byte $41, $50
	.word @song2ref10
	.byte $41, $13
	.word @song2ref53
	.byte $48
	.byte $41, $11
	.word @song2ref27
	.byte $41, $10
	.word @song2ref48
	.byte $48
	.byte $41, $10
	.word @song2ref67
	.byte $41, $0e
	.word @song2ref84
	.byte $9b, $00, $83, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $78, $4f, $02, $80, $20, $ff, $d5, $1e, $c5, $c7, $1c, $ff, $d5, $1b, $ff, $8d, $1c, $ff, $8d, $c7, $1b, $ff, $8d, $17
	.byte $c5, $ff, $8f, $18, $ff, $8d, $20, $ff, $d5, $1e, $c5, $c7, $23, $ff, $d5, $21, $ff, $8d, $20, $ff, $8d, $c7, $1e, $ff
	.byte $8d, $1c, $c5, $ff, $8f, $1b, $ff, $8d, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
@song2ref212:
	.byte $80
@song2ref213:
	.byte $19, $ff, $d5, $14, $c5, $c7, $15, $ff, $d5, $18, $ff, $8d, $19, $ff, $8d, $c7, $14, $ff, $8d, $15, $c5, $ff, $8f, $14
	.byte $ff, $8d
	.byte $41, $17
	.word @song2ref213
	.byte $18, $ff, $8d, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref249:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0f
	.word @song2ref249
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $52, $80
	.byte $41, $0f
	.word @song2ref249
	.byte $41, $0f
	.word @song2ref249
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $78, $4f, $01
	.byte $41, $1a
	.word @song2ref212
	.byte $41, $17
	.word @song2ref213
	.byte $18, $ff, $8d, $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $72, $51, $02, $90, $4e, $02, $4f, $01, $84
@song2ref308:
	.byte $19, $9b, $00, $83, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $14, $91, $89, $00, $83, $1c, $9b, $00, $83, $1e, $9b, $00
	.byte $83
@song2ref333:
	.byte $17, $8f, $51, $fe, $20, $8b, $00, $83, $1c, $9b, $00, $83, $1b, $9b, $00, $83, $1c
@song2ref350:
	.byte $9b, $00, $83, $19, $9b, $00, $83, $51, $02, $90, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $14, $9b, $00, $83, $1c, $9b
	.byte $00, $83, $1e, $9b, $00, $83, $18, $8f, $51, $fe, $20, $8b, $00, $83, $1c, $9b, $00, $83, $1b, $9b, $00, $83, $18
	.byte $41, $1b
	.word @song2ref350
	.byte $41, $37
	.word @song2ref333
	.byte $9b, $00, $83, $51, $02, $90, $4e, $02, $4f, $01
	.byte $41, $50
	.word @song2ref308
	.byte $41, $1b
	.word @song2ref350
	.byte $41, $37
	.word @song2ref333
	.byte $9b, $00, $83, $42
	.word @song2ch6loop
