; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; DPCM Delta Counter effect is used, you must set FAMISTUDIO_USE_DELTA_COUNTER = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_pwaa_music_v2_0=music_data_pwaa_music_v2_0
.endif

music_data_pwaa_music_v2_0:
	.byte 6
	.word @instruments
	.word @samples-5
; 00 : Trial
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Investigation
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Maya Fey
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Heartbroken Maya
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word @song3ch5
	.word @song3ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Light and Shadow of the Film Studio
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word @song4ch5
	.word @song4ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 05 : Class Trial
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word @song5ch5
	.word @song5ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_pwaa_music_v2_0
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env8,@env9,@env0 ; 00 : Kick
	.word @env5,@env8,@env9,@env0 ; 01 : Fade Loud
	.word @env6,@env8,@env9,@env0 ; 02 : Fade
	.word @env3,@env8,@env9,@env2 ; 03 : Lead 1
	.word @env1,@env8,@env9,@env0 ; 04 : Lead 2
	.word @env10,@env8,@env9,@env0 ; 05 : Long Fade
	.word @env7,@env8,@env9,@env0 ; 06 : Echo
	.word @env11,@env8,@env9,@env0 ; 07 : Arc In

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c6,$c7,$c8,$c6,$00,$04
@env2:
	.byte $00,$c0,$c1,$c2,$02,$c1,$c0,$bf,$be,$02,$bf,$00,$01
@env3:
	.byte $00,$c8,$c7,$c7,$c6,$00,$04
@env4:
	.byte $00,$cf,$ca,$c6,$c4,$c2,$c0,$00,$06
@env5:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env6:
	.byte $00,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$0e
@env7:
	.byte $00,$c8,$c7,$c7,$c6,$c6,$c5,$c0,$02,$c5,$c5,$c4,$c4,$c3,$c3,$c0,$02,$c3,$c2,$c2,$c1,$c1,$c0,$00,$16
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $00,$c8,$c8,$c7,$03,$c6,$03,$c5,$03,$c4,$03,$c3,$03,$c2,$02,$c1,$00,$0f
@env11:
	.byte $00,$c4,$c4,$c5,$03,$c6,$06,$c7,$09,$c8,$00,$09

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $7f, $51, $f8, $80, $4f, $02, $86, $12, $99, $cf, $7f, $51, $f9, $80, $14, $9d, $51, $ff, $50, $ff, $93, $48, $ff, $d7
	.byte $00, $8f, $7c, $84, $14, $8f, $17, $8f, $18, $8f, $48
	.byte $41, $09
	.word @song0ref5
	.byte $7c, $84
@song0ref45:
	.byte $21, $8f, $20, $8f, $1c, $8f, $17, $8f, $48, $12, $b1, $00, $12, $8b, $00, $a5, $7f, $51, $f9, $80, $86, $14, $a1, $51
	.byte $ff, $50, $ff, $8f, $48, $7c, $84
@song0ref76:
	.byte $14, $8f, $17, $8f, $19, $8f, $00, $a1, $12, $8f, $14, $8f, $17, $8f, $00, $b3, $1b, $8f, $1b, $8f, $17, $8f, $12, $a1
	.byte $48, $12, $a1, $19, $a1, $12, $a1, $7f, $51, $f9, $80, $86, $14, $a1, $51, $ff, $50, $ff, $8f, $48, $7c, $84
@song0ref122:
	.byte $14, $8f, $12, $8f, $00, $c5, $14, $8f, $17, $8f, $00, $b3, $17, $8f
	.byte $41, $43
	.word @song0ref45
	.byte $41, $08
	.word @song0ref45
@song0ref142:
	.byte $48, $19, $8b, $00, $81, $19, $8b, $00, $c9, $12, $8b, $00, $81, $12, $8b, $00, $ed, $7f, $51, $f9, $80, $86, $14, $a1
	.byte $48, $ff, $a1, $7c, $84
@song0ref171:
	.byte $14, $8f, $17, $8f, $19, $8f, $1c, $8f, $1b, $8f, $17, $8f, $12, $8f
	.byte $41, $12
	.word @song0ref142
	.byte $48, $c7, $7c, $84
@song0ref192:
	.byte $17, $a1, $14, $a1, $17, $a1, $19, $a1, $1b, $c5
	.byte $41, $1e
	.word @song0ref142
	.byte $1c, $8f, $1e, $8f
	.byte $41, $13
	.word @song0ref142
	.byte $8f, $73, $51, $02, $80, $19, $ff, $8b, $00, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7f, $51, $f8, $80, $4f, $02, $86
@song0ref232:
	.byte $1c, $99, $cf, $7f, $51, $f9, $80, $1e, $9d, $51, $ff, $50, $ff, $93, $ff, $d7, $00, $c5, $7f, $51, $f8, $80, $4f, $02
	.byte $41, $0b
	.word @song0ref232
	.byte $7f, $51, $f8, $80, $4f, $02
	.byte $41, $0b
	.word @song0ref232
	.byte $7f, $51, $f8, $80, $4f, $02
	.byte $41, $0b
	.word @song0ref232
	.byte $7f, $51, $f8, $80, $4f, $02
	.byte $41, $0b
	.word @song0ref232
	.byte $7f, $51, $f8, $80, $4f, $02
	.byte $41, $0b
	.word @song0ref232
	.byte $7a, $4f, $01
@song0ref298:
	.byte $84
@song0ref299:
	.byte $20, $8b, $00, $81, $20, $8b, $00, $c9, $21, $8b, $00, $81, $21, $8b, $00, $ed, $7f, $51, $f9, $80, $86, $23, $9d, $51
	.byte $ff, $50, $83, $ff, $d7, $00, $c5, $7a
	.byte $41, $10
	.word @song0ref298
	.byte $7f, $51, $f9, $80, $86, $1e, $9d, $51, $ff, $50, $83, $ff, $fb, $7a, $84, $1e, $8f, $1e, $8f, $4f, $01
	.byte $41, $17
	.word @song0ref299
	.byte $7a
	.byte $41, $10
	.word @song0ref298
	.byte $7f, $51, $f9, $80, $86, $1e, $9d, $51, $ff, $50, $83, $ff, $8f, $73, $51, $02, $80, $4f, $02, $ff, $8d, $00, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $86, $12, $e9, $14, $ff, $b1, $ff, $d7, $00, $8f, $14, $8f, $17, $8f, $18, $8f, $12, $e9, $14, $ff, $b1, $ff, $d7
	.byte $41, $08
	.word @song0ref45
@song0ref414:
	.byte $12, $b1, $00, $12, $8b, $00, $a5, $14, $ff, $af, $00
	.byte $41, $10
	.word @song0ref76
@song0ref428:
	.byte $1c, $8f, $1b, $8f, $17, $8f, $12, $9f, $00, $12, $a1, $19, $a1, $12, $a1, $14, $ff, $af, $00
	.byte $41, $0e
	.word @song0ref122
	.byte $41, $08
	.word @song0ref45
	.byte $41, $0b
	.word @song0ref414
	.byte $41, $10
	.word @song0ref76
	.byte $41, $13
	.word @song0ref428
	.byte $41, $0e
	.word @song0ref122
	.byte $41, $08
	.word @song0ref45
	.byte $00, $81
@song0ref470:
	.byte $19, $8d, $00, $19, $8b, $00, $c9, $12, $8d, $00, $12, $8b, $00, $ed, $14, $9d, $ff, $a5
	.byte $41, $0d
	.word @song0ref171
	.byte $8b, $83
	.byte $41, $10
	.word @song0ref470
	.byte $cb
	.byte $41, $09
	.word @song0ref192
	.byte $c1, $83
	.byte $41, $12
	.word @song0ref470
	.byte $41, $0a
	.word @song0ref171
	.byte $1c, $8f, $1e, $8b, $83
	.byte $41, $11
	.word @song0ref470
	.byte $ff, $00, $9d, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $00, $c5, $80
@song0ref526:
	.byte $11, $c5, $00, $c5, $11, $c5, $00, $c5
	.byte $41, $08
	.word @song0ref526
	.byte $11, $c5, $00, $c5, $11, $c5, $00, $ff, $b1, $11, $8f, $11, $8f, $78, $82, $0e, $a1, $7b, $80, $11, $8f, $79
@song0ref559:
	.byte $0a, $8f, $7e, $06, $c5
@song0ref564:
	.byte $79, $11, $8f, $00, $8f
@song0ref569:
	.byte $7e, $06, $c5, $00, $a1, $7b, $0a, $c5, $7e, $06, $c5, $7b, $0a, $a1
	.byte $41, $0a
	.word @song0ref569
	.byte $7e, $06, $c5, $00, $a1, $7b
@song0ref592:
	.byte $0a, $c5, $7e, $06
@song0ref596:
	.byte $8f, $7b, $06, $a1, $00, $8f
@song0ref602:
	.byte $0a, $a1, $7e, $06, $8f, $7b, $06, $a1, $00, $8f, $79, $11, $8f, $11, $8f, $78, $82, $0e, $a1, $79, $80, $11, $8f
	.byte $41, $12
	.word @song0ref559
	.byte $41, $08
	.word @song0ref569
	.byte $41, $0b
	.word @song0ref564
	.byte $41, $0d
	.word @song0ref596
	.byte $7e, $06, $8f, $7b, $06, $8f, $0a, $a1, $79, $0a, $8f, $0a, $8f, $7e, $06, $8f, $7b, $06, $a1, $00, $8f, $78
	.byte $41, $08
	.word @song0ref602
	.byte $7e, $06, $a1, $78, $0a, $a1, $7e, $06, $a1, $a3, $00, $a1, $78, $0a, $c5, $00, $a1, $7e, $06, $a1, $78
	.byte $41, $08
	.word @song0ref592
	.byte $78
	.byte $41, $08
	.word @song0ref602
@song0ref690:
	.byte $7e, $06, $8f, $7b, $06, $8f
@song0ref696:
	.byte $78, $0a, $a1, $7e, $06, $a1, $00, $a1, $06, $a1, $78, $0a, $c5, $00, $a1, $7e, $06, $8f, $7b, $06, $8f, $78, $0a, $a1
	.byte $41, $08
	.word @song0ref602
	.byte $78
	.byte $41, $08
	.word @song0ref602
	.byte $7e, $06, $a1
	.byte $41, $09
	.word @song0ref696
	.byte $b3, $0a, $a1, $00, $8f, $7e, $06, $8f, $7b, $06, $8f, $78
	.byte $41, $08
	.word @song0ref592
	.byte $78
	.byte $41, $08
	.word @song0ref602
	.byte $41, $0b
	.word @song0ref690
	.byte $8f, $7b, $06, $8f, $78, $0a, $b3, $76, $0a, $8f, $00, $a1, $7e, $06, $a1, $78, $0a, $b3, $00, $8f, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $52, $ff
@song0ref781:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $09
	.word @song0ref781
	.byte $41, $09
	.word @song0ref781
	.byte $41, $09
	.word @song0ref781
	.byte $41, $09
	.word @song0ref781
	.byte $41, $09
	.word @song0ref781
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $7f, $51, $f8, $80, $4f, $02, $86
@song0ref822:
	.byte $19, $99, $cf, $7f, $51, $f9, $80, $1b, $9d, $51, $ff, $50, $ff, $93, $ff, $d7, $00, $c5, $7f, $51, $f8, $80, $4f, $02
	.byte $41, $0b
	.word @song0ref822
	.byte $7f, $51, $f8, $80, $4f, $02
@song0ref855:
	.byte $19, $99, $cf, $7f, $51, $f9, $80, $1b, $9d, $51, $ff, $50, $ff, $93, $51, $01, $a0, $4f, $01, $84
@song0ref875:
	.byte $33, $8f, $34, $8f, $33, $8f, $34, $8f
	.byte $41, $08
	.word @song0ref875
	.byte $33, $8f, $51, $fe, $50, $34, $8f
	.byte $41, $08
	.word @song0ref875
	.byte $33, $8f, $34, $8f, $7f, $51, $f8, $80, $4f, $02, $86
	.byte $41, $0f
	.word @song0ref855
	.byte $41, $08
	.word @song0ref875
	.byte $33, $8f, $51, $fe, $50, $34, $8f
	.byte $41, $08
	.word @song0ref875
	.byte $33, $8f, $34, $8f, $7f, $51, $f8, $80, $4f, $02, $86, $19, $99, $cf, $7f, $51, $f9, $80, $1b, $9d, $51, $ff, $50, $ff
	.byte $93, $51, $01, $90
@song0ref951:
	.byte $4f, $01, $84, $31, $8f, $34, $8f, $36, $8f, $31, $8f, $34, $8f, $36, $8f, $31, $8f, $34, $8f, $36, $8f, $51, $fe, $50
	.byte $2c, $8f, $2f, $8f, $31, $8f
	.byte $41, $08
	.word @song0ref875
	.byte $7f, $51, $f8, $80, $4f, $02, $86, $19, $99, $cf, $7f, $51, $f9, $80, $1b, $9d, $51, $ff, $50, $ff, $93
	.byte $41, $08
	.word @song0ref951
	.byte $77, $34, $8f, $36, $8f, $31, $8f, $78, $34, $8f, $36, $8f, $31, $8f, $79, $34, $8f, $36, $8f, $34, $8f, $7a, $33, $8f
	.byte $2f, $8f, $28, $8f
@song0ref1036:
	.byte $7d
@song0ref1037:
	.byte $28, $8f, $28, $8f, $75, $28, $8f, $00, $b3, $7d, $28, $8f, $28, $8f, $75, $28, $8f, $00, $d7, $7f, $51, $f9, $80, $86
	.byte $2a, $9d, $51, $ff, $50, $83, $ff, $d7, $84, $2a, $a1, $00, $a1
	.byte $41, $10
	.word @song0ref1036
	.byte $7f, $51, $f9, $80, $86, $27, $9d, $51, $ff, $50, $83, $ff, $d7, $84, $27, $a1, $7d, $27, $8f, $27, $8f
	.byte $41, $19
	.word @song0ref1037
	.byte $41, $10
	.word @song0ref1036
	.byte $7f, $51, $f9, $80, $86, $27, $9d, $51, $ff, $50, $83, $ff, $d7, $00, $c5, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $ff, $ff, $9f, $ff, $d7, $7c, $4f, $01, $84, $28, $8f, $27, $8f, $23, $8f, $1e, $8f
@song0ref1140:
	.byte $19, $8f, $20, $8f, $25, $8f, $77, $25, $8f, $7c, $20, $8f, $19
@song0ref1153:
	.byte $8f, $1b, $8f, $22, $8f, $27, $b3, $76, $27, $b3, $73, $27, $a1, $91, $00, $ff, $ff, $8b, $7c, $19, $8f, $20, $8f, $25
	.byte $a1, $19, $8f, $00
	.byte $41, $0b
	.word @song0ref1153
	.byte $74, $51, $01, $a0
@song0ref1188:
	.byte $1b, $8f, $27, $8f, $1b, $8f, $27, $8f
	.byte $41, $08
	.word @song0ref1188
	.byte $41, $08
	.word @song0ref1188
	.byte $41, $08
	.word @song0ref1188
	.byte $7c
	.byte $41, $18
	.word @song0ref1140
	.byte $8f, $7b, $24, $83, $7c, $25, $9b, $23, $c5, $23, $c5, $27, $a1, $28, $a1, $19, $8f, $1c, $8f, $28, $8f, $77, $28, $8f
	.byte $7c, $1c, $8f, $00, $8f, $23, $8f, $2a, $b3, $76, $2a, $b3, $73, $2a, $b3, $74, $51, $01, $a0
@song0ref1252:
	.byte $2a, $8f, $1e, $8f, $2a, $8f, $1e, $8f
	.byte $41, $08
	.word @song0ref1252
	.byte $41, $08
	.word @song0ref1252
	.byte $41, $08
	.word @song0ref1252
	.byte $7c
	.byte $41, $16
	.word @song0ref1140
	.byte $76, $1e, $8b, $00, $81, $43, $1e, $8b, $00, $81, $43, $1e, $8b, $00, $81, $1e, $8b, $00, $81, $78, $20, $8b, $00, $81
	.byte $43, $20, $8b, $00, $81, $43, $20, $8b, $00, $81, $20, $8b, $00, $81, $7a, $23, $8b, $00, $81, $43, $23, $8b, $00, $81
	.byte $43, $23, $8b, $00, $81, $23, $8b, $00, $81, $7c, $27, $8b, $00, $81, $43, $27, $8b, $00, $81, $43, $27, $8b, $00, $81
	.byte $27, $8b, $00, $81, $7a
@song0ref1350:
	.byte $23, $8b, $00, $81, $23, $8b, $00, $c9, $23, $8b, $00, $81, $23, $8b, $00, $ed, $7f, $51, $f9, $80, $86, $27, $9d, $51
	.byte $ff, $50, $83, $ff, $d7, $00, $c5, $7a, $84
	.byte $41, $10
	.word @song0ref1350
	.byte $7f, $51, $f9, $80, $86, $23, $9d, $51, $ff, $50, $83, $ff, $d7, $00, $a1, $7a, $84, $23, $8f, $23, $8f
	.byte $41, $17
	.word @song0ref1350
	.byte $7a, $84
	.byte $41, $10
	.word @song0ref1350
	.byte $7f, $51, $f9, $80, $86, $23, $9d, $51, $ff, $50, $83, $ff, $d7, $00, $c5, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7c, $4f, $02, $8c
@song1ref9:
	.byte $2d, $a1, $74, $26, $b3, $00, $b3, $2f, $b3, $00, $8f, $79, $36, $b3, $00, $8f, $48, $7b, $34, $a1, $74, $2a, $b3, $00
	.byte $8f, $79, $31, $a1, $73, $2d, $b3, $00, $d7, $48, $7c, $2d, $b3, $00, $d7, $74, $2f, $b3, $00, $8f, $79, $36, $b3, $00
	.byte $8f, $48, $7b, $31, $a1, $74, $2a, $b3, $00, $8f, $7b, $34, $a1, $74, $2d, $b3, $00, $d7, $48, $7c, $4f, $02
	.byte $41, $32
	.word @song1ref9
	.byte $48, $7b, $28, $a1, $73, $32, $b3, $00, $8f, $79, $34, $a1, $73, $2a, $b3, $00, $d7, $48, $7b, $2b, $a1, $72, $36, $b3
	.byte $00, $ff, $c3, $48, $79, $32, $a1, $73, $28, $b3, $00, $8f, $7b, $2a, $a1, $73, $34, $b3, $00, $d7, $48, $78, $36, $a1
	.byte $73, $2c, $b3, $00, $ff, $c3, $48, $79, $84
@song1ref139:
	.byte $2f, $a1, $72, $32, $a1, $78, $32, $a1, $73, $2f, $a1, $79, $2d, $a1, $72, $31, $8f, $78, $31, $a1, $73, $2d, $8f, $79
	.byte $2d, $a1, $48, $72, $31, $b3, $00, $ff, $e7, $48, $78, $32, $a1, $73, $2f, $a1, $79, $2f, $a1, $72, $32, $a1, $78, $34
	.byte $a1, $73, $31, $8f, $79, $31, $a1, $72, $34, $8f, $77, $36, $a1, $48, $73, $33, $b3, $00, $ff, $e7, $48, $79
	.byte $41, $2e
	.word @song1ref139
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $7f, $4f, $02, $84
@song1ref220:
	.byte $13, $8f, $13, $97, $00, $f3, $13, $97, $00, $99, $13, $a9, $00, $99
@song1ref234:
	.byte $12, $8f, $12, $97, $00, $f3, $12, $97, $00, $99, $12, $a9, $00, $99, $13, $8f, $13, $97, $00, $f3, $13, $8f, $7d, $1a
	.byte $8f, $7f, $13, $8f, $10, $8f, $00, $8f, $7d, $15, $8f, $00, $8f, $7f
	.byte $41, $0e
	.word @song1ref234
	.byte $4f, $02
	.byte $41, $28
	.word @song1ref220
	.byte $7d, $1e, $8f, $00, $8f, $7f, $10, $8f, $11, $8f, $12, $8f, $12, $97, $00, $bd, $12, $8f, $12, $97, $00, $bd, $12, $a9
	.byte $00, $99
@song1ref306:
	.byte $10, $8f, $10, $97, $00, $bd, $12, $8f, $12, $97, $00, $87, $12, $a1, $00, $8f, $12, $a9, $00, $99, $13, $8f, $13, $97
	.byte $00, $ff, $85, $13, $a1, $00, $8f, $13, $a1, $00, $8f
	.byte $41, $14
	.word @song1ref306
	.byte $14, $a9, $00, $ff, $85, $14, $a1, $00, $8f, $14, $a1, $00, $8f
@song1ref357:
	.byte $0e, $a1, $00, $a1, $0e, $a1, $0b, $a1, $0d, $a1, $00, $8f, $10, $a1, $00, $8f, $12, $a1, $00, $ff, $b1, $10, $a1, $00
	.byte $8f, $12, $a1, $00, $8f, $0e, $a1, $00, $a1, $0e, $a1, $00, $a1, $0d, $a1, $00, $8f, $0d, $a1, $00, $8f, $0b, $a1, $00
	.byte $c5, $0b, $a1, $00, $a1, $0b, $a1, $00, $8f, $0b, $a1, $00, $8f, $0d, $a1
	.byte $41, $14
	.word @song1ref357
	.byte $8d, $12, $a1, $00, $8f, $12, $a1, $00, $8f, $12, $a1, $0e, $a1, $00, $a1, $7d, $1a, $a1, $00, $a1, $19, $a1, $00, $8f
	.byte $19, $a1, $15, $8f, $17, $a1, $00, $c5, $17, $a1, $00, $a1, $17, $a1, $00, $8f, $17, $a1, $00, $8f, $15, $a1, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $88
@song1ref474:
	.byte $19, $89, $00, $83, $19, $89, $00, $cb
@song1ref482:
	.byte $19
@song1ref483:
	.byte $89, $00, $a7, $19, $89, $00, $a7, $19, $89, $00, $b9
@song1ref494:
	.byte $17, $89, $00, $83, $17, $89, $00, $cb, $17, $89, $00, $a7, $17, $89, $00, $a7, $17, $89, $00, $a7, $17, $89, $00, $83
	.byte $41, $27
	.word @song1ref474
	.byte $b9
	.byte $41, $27
	.word @song1ref474
	.byte $b9
	.byte $41, $13
	.word @song1ref474
	.byte $a7, $19, $89, $00, $83
	.byte $41, $0b
	.word @song1ref494
	.byte $83, $17, $89, $00, $cb, $17, $89, $00, $b9
@song1ref546:
	.byte $15, $89, $00, $83, $15, $89, $00, $cb, $17, $89, $00, $83, $17, $89, $00, $a7, $17, $89, $00, $95, $17, $89, $00, $b9
	.byte $19, $89, $00, $83, $19, $89, $00, $ff, $93, $19, $89, $00, $a7, $19, $89, $00, $a7
	.byte $41, $1b
	.word @song1ref546
	.byte $ff, $a5
	.byte $41, $0c
	.word @song1ref482
@song1ref595:
	.byte $19, $89, $00, $b9, $17, $89, $00, $a7, $17, $89, $00, $a7, $19, $89, $00, $95, $ff, $b3, $17
	.byte $41, $0b
	.word @song1ref483
	.byte $41, $10
	.word @song1ref595
@song1ref620:
	.byte $c7, $19, $89, $00, $95, $1b, $89, $00, $95, $1b, $89, $00, $a7, $1b, $89, $00, $cb, $19, $89, $00, $b9
	.byte $41, $11
	.word @song1ref595
	.byte $8f
	.byte $41, $0b
	.word @song1ref482
	.byte $95, $19, $89, $00, $b9
	.byte $41, $10
	.word @song1ref595
	.byte $41, $11
	.word @song1ref620
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $7e, $80
@song1ref665:
	.byte $04, $8f, $7b, $04, $8f, $00, $a1, $7d, $0e, $8f, $00, $8f, $7e, $04, $8f, $00, $b3
@song1ref682:
	.byte $77, $82, $11, $9d, $00, $81
@song1ref688:
	.byte $7d, $80, $10, $8f, $00, $b3, $7e, $04, $8f, $00, $8f, $04, $8f, $00, $8f, $7d, $0e, $8f, $00
@song1ref707:
	.byte $8f, $7e, $04, $8f, $00, $b3, $77, $82, $11, $8f, $80, $0f, $8f, $7d, $10, $8f, $00, $b3, $7e
	.byte $41, $20
	.word @song1ref665
	.byte $77, $0e
	.byte $41, $0d
	.word @song1ref707
	.byte $7e
	.byte $41, $0f
	.word @song1ref665
	.byte $9b, $00, $83
	.byte $41, $1c
	.word @song1ref688
	.byte $7e
	.byte $41, $0f
	.word @song1ref665
	.byte $9b, $00, $83
@song1ref751:
	.byte $7d, $80, $10, $8f, $00, $b3, $7e, $04, $8f, $7b, $04, $8f, $00, $a1, $7d, $0e, $8f, $76, $0e, $8f, $7e, $04, $8f, $00
	.byte $8f, $7a, $0e, $8f, $00, $85, $77, $0e, $87, $82, $11, $8f, $80, $0f, $8f, $7d, $10, $9b, $00, $a7, $7e
	.byte $41, $0c
	.word @song1ref665
	.byte $7b, $04, $8f, $00, $a1
	.byte $41, $0c
	.word @song1ref682
	.byte $79, $0f, $8f, $00, $8f, $0f, $8f, $00, $8f
@song1ref816:
	.byte $0f, $8f, $00, $8f, $7e, $04, $8f, $00, $8f, $77, $82, $11, $9d, $00, $81
	.byte $41, $0c
	.word @song1ref751
	.byte $00, $8f, $0e, $8f, $7a, $0e, $8f, $00, $a1, $77, $82, $11, $8f, $75, $80, $0e, $81, $77, $0e, $83, $79, $0e, $85, $7d
	.byte $10, $8f, $00, $b3, $7e, $04, $8f, $00, $8f, $79, $0f, $8f, $00, $8f, $7d, $0e, $8f, $00, $8f, $79
	.byte $41, $0c
	.word @song1ref816
	.byte $7d, $80, $10, $8f, $00, $b3
@song1ref887:
	.byte $79, $0f, $8f, $00, $a1, $7b, $04, $8f, $7d, $0e, $8f, $00, $8f, $7e, $04
@song1ref902:
	.byte $8f, $00, $8f, $79, $0f, $8f, $00, $8f, $7e, $04, $8f, $00, $8f, $7d, $10, $8f, $00, $b3, $79, $0f, $8f, $7b, $04, $8f
	.byte $00, $a1, $79, $0f, $8f, $00, $8f, $7e, $0e
	.byte $41, $0b
	.word @song1ref902
	.byte $79, $0f, $8f, $7e, $0e, $8f, $00, $8f, $7b, $04, $8f
	.byte $41, $24
	.word @song1ref887
	.byte $7d, $0e, $8f, $00, $8f, $79, $0f, $8f, $00, $8f, $7e, $04, $8b, $00, $93, $79, $0f, $8f, $75, $0e, $81, $77, $0e, $83
	.byte $79, $0e, $83, $00, $7d, $0e, $8f, $00, $8f
	.byte $41, $14
	.word @song1ref887
	.byte $7b, $04, $8f, $7d, $10, $8f, $00, $b3, $79, $0f, $8f, $7d, $0e, $8f, $00, $a1, $0e, $8f, $00, $a1, $7a, $0e, $85, $79
	.byte $0e, $87, $0f, $8f, $00, $8f, $7a, $0e, $8f, $00, $8f, $79, $0f, $8f, $7b, $04, $8f, $0e
	.byte $41, $0b
	.word @song1ref902
	.byte $7d, $0e, $8f, $00, $b3, $79, $0f, $8f, $00, $8f, $7e, $04, $8f, $7b, $04, $8f, $7d, $10, $8f, $00, $b3, $77, $84, $11
	.byte $9b, $00, $ef, $79, $80, $0f, $8f, $00, $8f, $7e, $04, $8f, $00, $8f, $7c, $0e, $8f, $00, $8f, $7a, $0e, $8f, $7c, $0e
	.byte $8f, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $52, $ff
@song1ref1088:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0c
	.word @song1ref1088
	.byte $41, $0c
	.word @song1ref1088
	.byte $41, $0c
	.word @song1ref1088
	.byte $41, $0c
	.word @song1ref1088
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $7c, $4f, $02, $84
@song1ref1120:
	.byte $25, $89, $00, $83, $25, $89, $00, $cb
@song1ref1128:
	.byte $25
@song1ref1129:
	.byte $89, $00, $a7, $25, $89, $00, $a7, $25, $89, $00, $b9
@song1ref1140:
	.byte $23, $89, $00, $83, $23, $89, $00, $cb, $23, $89, $00, $a7, $23, $89, $00, $a7, $23, $89, $00, $a7, $23, $89, $00, $83
	.byte $4f, $02
	.byte $41, $27
	.word @song1ref1120
	.byte $b9, $4f, $02
	.byte $41, $27
	.word @song1ref1120
	.byte $b9
	.byte $41, $13
	.word @song1ref1120
	.byte $a7, $25, $89, $00, $83
	.byte $41, $0b
	.word @song1ref1140
	.byte $83, $23, $89, $00, $cb, $23, $89, $00, $b9
@song1ref1196:
	.byte $21, $89, $00, $83, $21, $89, $00, $cb, $23, $89, $00, $83, $23, $89, $00, $a7, $23, $89, $00, $95, $23, $89, $00, $b9
	.byte $25, $89, $00, $83, $25, $89, $00, $ff, $93, $25, $89, $00, $a7, $25, $89, $00, $a7
	.byte $41, $1b
	.word @song1ref1196
	.byte $ff, $a5
	.byte $41, $0c
	.word @song1ref1128
@song1ref1245:
	.byte $25, $89, $00, $b9, $23, $89, $00, $a7, $23, $89, $00, $a7, $25, $89, $00, $95, $ff, $b3, $23
	.byte $41, $0b
	.word @song1ref1129
	.byte $41, $10
	.word @song1ref1245
@song1ref1270:
	.byte $c7, $25, $89, $00, $95, $27, $89, $00, $95, $27, $89, $00, $a7, $27, $89, $00, $cb, $25, $89, $00, $b9
	.byte $41, $11
	.word @song1ref1245
	.byte $8f
	.byte $41, $0b
	.word @song1ref1128
	.byte $95, $25, $89, $00, $b9
	.byte $41, $10
	.word @song1ref1245
	.byte $41, $11
	.word @song1ref1270
	.byte $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $7c, $4f, $01, $84
@song1ref1317:
	.byte $2a, $89, $00, $83, $2a, $89, $00, $cb
@song1ref1325:
	.byte $2a
@song1ref1326:
	.byte $89, $00, $a7, $2a, $89, $00, $a7, $2a, $89, $00, $b9
@song1ref1337:
	.byte $28, $89, $00, $83, $28, $89, $00, $cb, $28, $89, $00, $a7, $28, $89, $00, $a7, $28, $89, $00, $b9, $4f, $01
	.byte $41, $28
	.word @song1ref1317
	.byte $4f, $01
	.byte $41, $28
	.word @song1ref1317
	.byte $41, $13
	.word @song1ref1317
	.byte $a7, $2a, $89, $00, $83
	.byte $41, $0b
	.word @song1ref1337
	.byte $83, $28, $89, $00, $cb, $28, $89, $00, $b9
@song1ref1387:
	.byte $26, $89, $00, $83, $26, $89, $00, $cb, $28, $89, $00, $83, $28, $89, $00, $a7, $28, $89, $00, $95, $28, $89, $00, $b9
	.byte $2a, $89, $00, $83, $2a, $89, $00, $ff, $93, $2a, $89, $00, $a7, $2a, $89, $00, $a7
	.byte $41, $1b
	.word @song1ref1387
	.byte $ff, $a5, $28
	.byte $41, $0b
	.word @song1ref1326
@song1ref1437:
	.byte $2a, $89, $00, $b9, $28, $89, $00, $a7, $28, $89, $00, $a7, $2a, $89, $00, $95, $ff, $b3, $28
	.byte $41, $0b
	.word @song1ref1326
	.byte $41, $10
	.word @song1ref1437
	.byte $c7, $2a, $89, $00, $95, $2a, $89, $00, $95
@song1ref1471:
	.byte $2a, $89, $00, $a7, $2a, $89, $00, $a7, $28, $89, $00, $95, $2a, $89, $00, $b9
	.byte $41, $11
	.word @song1ref1437
	.byte $8f
	.byte $41, $0b
	.word @song1ref1325
	.byte $95, $2a, $89, $00, $b9
	.byte $41, $10
	.word @song1ref1437
	.byte $c7, $2a, $89, $00, $b9
	.byte $41, $0c
	.word @song1ref1471
	.byte $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $91, $76, $4f, $02, $88
@song2ref10:
	.byte $25, $8b, $00, $81, $26, $89, $00, $81, $28, $ad, $00, $81, $28, $8b, $00, $a3, $21, $ad, $00, $93, $73, $24, $81, $76
	.byte $25, $9b, $23, $8f, $48, $8d, $00, $81, $21, $9b, $00, $81, $20, $9d, $00, $81, $21, $9b, $00, $81, $23, $8b, $00, $91
	.byte $21, $e1, $00, $93, $48, $91
	.byte $41, $21
	.word @song2ref10
@song2ref67:
	.byte $23, $ad, $00, $81, $28, $8b, $00, $a3, $25, $e1, $00, $93, $48, $91
	.byte $41, $32
	.word @song2ref10
	.byte $41, $10
	.word @song2ref10
	.byte $2d, $ad, $00, $81, $25, $81, $26, $9d, $25, $9f, $48, $8d, $00, $81, $21, $9b, $00, $81
@song2ref105:
	.byte $1c, $9d, $00, $81, $21, $9b, $00, $81, $20, $9b, $00, $81, $21, $e1, $00, $93, $48, $91
	.byte $41, $32
	.word @song2ref10
	.byte $41, $21
	.word @song2ref10
	.byte $41, $0d
	.word @song2ref67
	.byte $41, $32
	.word @song2ref10
	.byte $41, $10
	.word @song2ref10
	.byte $2d, $ad, $00, $93, $21, $b1, $48, $ad, $00, $83
	.byte $41, $0d
	.word @song2ref105
	.byte $f7, $48, $ad, $00, $83, $28, $ab, $00, $83
@song2ref160:
	.byte $28, $8b, $00, $a3, $28, $bf, $00, $81, $25, $81, $26, $9b, $25, $8f, $48, $8d, $00, $81, $23, $8b, $00, $81, $21, $89
	.byte $00, $81, $23, $ab, $00, $83, $25, $8b, $00, $a3
@song2ref194:
	.byte $21, $9d, $00, $81, $23, $bd, $00, $81, $25, $8f, $48, $af, $00, $81, $28, $ab, $00, $83
@song2ref212:
	.byte $28, $8b, $00, $a3, $2c, $81, $2d, $bf, $21, $b1, $48, $8d, $00, $81, $25, $81, $26, $bb, $00, $81, $25, $bd, $00, $81
	.byte $21, $bf, $00, $81, $23, $b1, $48, $8d, $00, $81, $25, $8b, $00, $81, $26, $89, $00, $81, $26, $81, $28, $ad
	.byte $41, $1a
	.word @song2ref160
	.byte $ad, $00, $81, $25, $ad, $00, $81
	.byte $41, $0d
	.word @song2ref194
	.byte $26, $81, $28, $ad
	.byte $41, $20
	.word @song2ref212
	.byte $21, $8b, $00, $81, $7b, $84, $26, $e1, $00, $81, $26
@song2ref289:
	.byte $ff, $87, $48, $9f, $00, $81, $26, $e1, $00, $81, $26, $ff, $87, $48, $9f, $00, $81, $26, $e1, $00, $81, $26, $ff, $87
	.byte $48, $9f, $00, $81, $25, $e1, $00, $81, $25
	.byte $41, $10
	.word @song2ref289
	.byte $89, $00, $81, $76, $26, $8b, $00, $a3, $26, $7b, $8b, $00, $81, $76, $26, $8b, $00, $c5, $7b, $26, $8b, $00, $81, $76
	.byte $26, $8b, $00, $81, $7b, $26, $9f, $48, $9f, $00, $81, $51, $ff, $00, $26, $ff, $ef, $48, $ff, $ff, $00, $93, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $93, $00, $8d, $7a, $4f, $01, $88
@song2ref382:
	.byte $0d, $ab, $00, $83, $0d, $89, $00, $a5, $0e, $ff, $87, $93, $00, $8d
@song2ref396:
	.byte $10, $ab, $00, $83, $11, $89, $00, $a5, $12, $ff, $87, $93, $00, $8d, $4f, $01
	.byte $41, $18
	.word @song2ref382
	.byte $81, $00, $83, $15, $8b, $00, $81, $17, $8b, $00, $81
	.byte $41, $1c
	.word @song2ref382
	.byte $4f, $01
	.byte $41, $17
	.word @song2ref382
	.byte $ad, $00, $81, $74, $14, $89, $00, $81, $76, $15, $8b, $00, $81, $79, $17, $8b, $00, $81, $7a, $1c, $9b, $00, $81, $10
	.byte $8b, $00, $93
@song2ref461:
	.byte $0d, $9b, $00, $81, $19, $8b, $00, $81, $0d, $89, $00, $a5, $0e, $df, $00, $a5, $15, $9d, $00, $81
	.byte $41, $0e
	.word @song2ref396
	.byte $41, $11
	.word @song2ref461
@song2ref487:
	.byte $8b, $00, $81, $1c
@song2ref491:
	.byte $8b, $00, $81, $10, $ab, $00, $83, $11, $89, $00, $a5, $12, $ff, $81, $00, $83, $15, $8b, $00, $81, $17, $8b, $00, $81
	.byte $41, $11
	.word @song2ref461
	.byte $8b, $00, $81, $1a
	.byte $41, $0d
	.word @song2ref491
	.byte $87, $93, $00, $8d
	.byte $41, $11
	.word @song2ref461
	.byte $41, $10
	.word @song2ref487
	.byte $ad, $00, $81, $74, $14, $89, $00, $81, $77, $15, $8b, $00, $81, $7a, $17, $8b, $00, $81, $10, $9b, $00, $81, $1c, $8b
	.byte $00, $93, $0d, $ab, $00, $83, $0d, $89, $00, $a5, $12, $ff, $81, $00, $83, $12, $8b, $00, $93, $10, $ab, $00, $83, $10
	.byte $89, $00, $a5, $09, $bd, $00, $81, $10, $9d, $00, $81, $0b
@song2ref595:
	.byte $9f, $9f, $00, $81, $0d, $ab, $00, $83, $0d, $89, $00, $a5, $0e, $df, $00, $83, $0e, $89, $00, $93, $10, $ff, $b9, $00
	.byte $81, $1c, $89, $00, $81, $10, $8b, $00, $93, $10
	.byte $41, $0c
	.word @song2ref595
	.byte $12, $ad, $00, $81, $12, $89, $00, $a5, $12, $9f, $8d, $00, $93, $10, $ad, $00, $81, $10, $89, $00, $a5, $10, $89, $00
	.byte $93, $15, $bf, $00, $81, $09, $9b, $00, $81, $0b, $9d, $00, $81, $0d, $ab, $00, $83, $0d, $89, $00, $a5, $0e, $ad, $00
	.byte $81, $0e, $89, $00, $a5, $0e, $9b, $00, $81, $10, $ff, $eb, $00, $83, $12, $9f, $9f
@song2ref697:
	.byte $00, $81, $13, $ab, $00, $83, $13, $89, $00, $a5, $13, $ab, $00, $83, $1f, $89, $00, $81, $13, $9d, $00, $81, $1a, $9b
	.byte $00, $81, $1f, $9d, $00, $81, $12, $ab, $00, $83, $12, $89, $00, $a5, $12, $9b, $00, $a3, $12, $9d, $00, $81, $1e, $9b
	.byte $00, $81, $12, $9d
	.byte $41, $27
	.word @song2ref697
	.byte $bd, $00, $81, $19, $9d, $00, $81, $1e, $9b, $00, $81, $19, $9d, $00, $81, $11, $ab, $00, $83, $11, $89, $00, $a5, $11
	.byte $bd, $00, $81, $18, $9d, $00, $81, $1d, $9b, $00, $81, $18, $9d, $00, $81, $13, $89, $00, $b5, $13, $8b, $00, $d7, $13
	.byte $8b, $00, $93, $13, $89, $00, $93, $a3, $78, $13, $ff, $ef, $51, $f8, $00, $9f, $00, $81, $ff, $f1, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $a3, $78, $84
@song2ref827:
	.byte $1e, $89, $00, $a5, $1e, $89, $00, $a5, $1c, $89, $00, $93, $1e, $8b, $00, $a3, $1e, $8b, $00, $a3, $1e, $8b, $00, $93
	.byte $1c, $89, $00, $a5, $1d, $89, $00, $a5, $1e, $89, $00, $93, $1e, $8b, $00, $a3, $1e, $8b, $00, $a3, $1c, $8b, $00, $93
	.byte $41, $30
	.word @song2ref827
	.byte $41, $30
	.word @song2ref827
	.byte $41, $30
	.word @song2ref827
	.byte $41, $30
	.word @song2ref827
	.byte $41, $30
	.word @song2ref827
	.byte $41, $30
	.word @song2ref827
	.byte $41, $18
	.word @song2ref827
	.byte $79, $2c, $81, $2d, $89, $2c, $8b, $00, $81, $76, $2c, $8b, $00, $81, $79, $28, $89, $00, $81, $76, $28, $8b, $00, $81
	.byte $7b, $21, $8b, $00, $81, $77, $21, $89, $00, $81, $79
@song2ref931:
	.byte $26, $ad, $00, $81, $25, $9d, $00, $81, $25, $9b, $00, $81, $7b, $21, $8b, $00, $81, $77, $21, $8b, $00, $81, $7b
@song2ref954:
	.byte $20, $e1, $00, $81, $21, $ff, $87, $9f, $00, $81, $20, $e1, $00, $81, $1c, $ff, $83, $00, $81, $1c, $9d, $00, $81, $20
	.byte $e1, $00, $81, $21, $ff, $87, $23, $ff, $89
@song2ref987:
	.byte $79
@song2ref988:
	.byte $2c, $81, $2d, $9b, $2c, $9b, $00, $81, $28, $9d, $00, $81, $7b, $23, $9f, $9f, $00, $81
	.byte $41, $20
	.word @song2ref954
	.byte $85, $00, $81
	.byte $41, $0d
	.word @song2ref987
	.byte $9b, $21, $81, $9d, $00, $ff, $f5
@song2ref1022:
	.byte $ff, $ff, $95, $ff, $ff, $95, $ff, $ff, $95, $ff, $ff, $95, $ff, $ff, $95, $ff, $ff, $95, $ff, $ff, $95, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref1047:
	.byte $00, $a1, $7e, $80, $05
@song2ref1052:
	.byte $8d, $00, $a1, $7a, $05, $8d, $7e, $0d, $8f, $00, $8f, $05, $8d, $00, $b1, $78, $82, $10, $a1, $7e, $80, $0d, $8d, $00
	.byte $8f, $91, $7a, $0d, $8f, $7e, $05
@song2ref1083:
	.byte $8d, $00
@song2ref1085:
	.byte $8f, $05, $8f, $00, $8d, $0d, $8f, $00, $8f, $05, $8d, $00, $b1, $05, $8f, $00, $8f, $78, $82, $10, $9f
	.byte $41, $19
	.word @song2ref1047
	.byte $78, $07, $8d, $00, $a1, $79, $0d, $8d, $07, $8f, $00, $9f, $7a, $0d, $8f, $78, $07, $8f, $00, $8d, $7e, $07, $8f, $00
	.byte $8f, $78, $82, $10, $9f
	.byte $41, $2f
	.word @song2ref1047
	.byte $41, $1c
	.word @song2ref1047
	.byte $a1, $7a, $05, $8d, $7e, $0d, $8f, $00, $8f, $05, $8d, $00, $b1, $05, $8f, $7a, $05, $8f, $0d, $8d, $00, $8f, $91, $0d
	.byte $8f, $78, $82, $10, $9f, $00, $8f, $7a, $80, $05, $8d, $7e, $0d, $8f, $00, $8f, $05, $8d, $00, $8f, $78, $07, $8f, $00
	.byte $8d, $82, $10, $a1, $80, $0d, $8d, $00, $8f, $91, $7a, $0d, $8f, $7e, $07
	.byte $41, $0e
	.word @song2ref1083
@song2ref1210:
	.byte $8f, $78, $07, $8f, $00, $8d, $07, $8f, $00, $8f, $82, $10, $9f, $80, $07, $8f, $00, $8f, $7e, $07
	.byte $41, $0c
	.word @song2ref1052
@song2ref1233:
	.byte $8f, $78, $07, $8f, $00, $8d, $82, $10, $a1, $7e, $80, $0d, $8d, $00, $8f, $91, $7a, $0d, $8f, $7e, $07, $8d, $00, $a1
	.byte $79, $0d, $8d, $78, $07, $8f, $00, $9f, $7a, $0d, $8f, $7e, $07, $8f, $00, $8d, $07, $8f, $00, $8f, $78, $82, $10, $9f
	.byte $80, $07, $8f, $00, $8f, $07, $8d, $00, $a1, $7a, $05, $8d, $78, $0d, $8f, $00, $8f, $7e, $05, $8d, $00
	.byte $41, $11
	.word @song2ref1233
	.byte $41, $0c
	.word @song2ref1085
	.byte $41, $10
	.word @song2ref1210
	.byte $41, $0c
	.word @song2ref1052
	.byte $8f, $78, $07, $8f, $00, $8d, $82, $10, $a1, $7e, $80, $0d, $8d, $00, $8f, $78, $07, $8f, $7a, $0d, $8f, $7e, $07, $8d
	.byte $00, $a1, $7a, $07, $8d, $7e, $0d, $8f, $00, $8f, $07, $8d, $00, $8f, $78, $07, $8f, $00, $8d, $07, $8f, $7a, $07, $8f
	.byte $78, $82, $10, $9f, $80
@song2ref1367:
	.byte $07, $8f, $7d, $0d, $8f, $78, $07, $8d, $00, $8f, $7c, $07, $8f, $7a, $05, $8d, $7c, $0d, $8f, $00, $8f, $7e, $07, $8d
	.byte $00, $8f, $78, $07, $8f, $00, $8d, $82, $10, $a1, $7e, $80, $0d, $8d, $00, $8f, $7c, $07, $8f, $7a, $0d, $8f, $7e, $07
	.byte $8d, $00, $8f, $78, $07, $8f, $7a, $05, $8d, $78, $0d, $8f, $00, $8f, $07, $8d, $00, $8f, $07, $8f, $00, $8d, $7e, $07
	.byte $8f, $00, $8f, $78, $82, $10, $9f, $80, $07, $8f
@song2ref1449:
	.byte $07, $8f, $07, $8d, $00, $8f, $7c, $07, $8f, $7a, $05, $8d, $78, $0d, $8f, $00, $8f, $7e, $07, $8d, $00, $8f, $78, $07
	.byte $8f, $07, $8d, $82, $10, $a1, $80, $07, $8d, $07, $8f, $79, $82, $10, $a1, $00, $9f, $7a, $10, $9f, $78, $80, $07, $8f
	.byte $07, $8f, $7a, $82, $10, $8d, $91, $7e, $80, $05, $8f, $00, $8d, $7a, $82, $10, $a1, $80, $0d, $8d, $00, $8f, $78
	.byte $41, $71
	.word @song2ref1367
	.byte $78
	.byte $41, $5a
	.word @song2ref1367
	.byte $07, $8f, $7d, $0d, $8f, $78, $07, $8d, $00, $8f, $7c, $07, $8f, $7a, $0d, $8d, $7c, $0d, $8f, $00, $8f, $7e, $07, $8d
	.byte $0d
	.byte $41, $0d
	.word @song2ref1210
	.byte $41, $1c
	.word @song2ref1449
	.byte $07, $8f, $7a, $0d, $8f, $78, $82, $10, $9f, $00, $9f, $10, $a1, $80, $0d, $8d, $7a, $0d, $8f, $00, $9f, $7e, $0d, $8f
	.byte $78, $07, $8f, $82, $10, $9f, $00, $a1, $10, $9f, $00, $9f, $10, $a1, $80, $0d, $8d, $0d, $8f, $82, $10, $9f, $80, $0d
	.byte $8f, $00, $8f, $82, $10, $9f, $7e, $80, $0d, $8f, $00, $8f, $78, $82, $10, $9f, $00, $9f, $10, $a1, $80, $07, $8d, $0d
	.byte $8f, $79, $0d, $8f, $7a, $0d, $8d, $7c, $0d, $8f, $7d, $0d, $8f, $7e, $82, $10, $9f, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $52, $ff
	.byte $41, $15
	.word @song2ref1022
	.byte $41, $15
	.word @song2ref1022
	.byte $41, $15
	.word @song2ref1022
	.byte $41, $15
	.word @song2ref1022
	.byte $41, $0c
	.word @song2ref1022
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $a3, $7f, $4f, $01, $84
@song2ref1677:
	.byte $17, $ad, $00, $81, $17, $89, $00, $a5, $19, $bd, $00, $81, $15, $9d, $00, $81, $17, $9b, $00, $81, $1c, $9d, $00, $81
@song2ref1701:
	.byte $21, $9b, $00, $81, $28, $9b, $00, $81, $2d, $8b, $00, $93, $21, $89, $00, $81, $28, $9d, $00, $81, $2d, $9b, $00, $81
@song2ref1725:
	.byte $21, $8b, $00, $81, $23, $9b, $00, $81, $21, $8b, $00, $93
	.byte $41, $15
	.word @song2ref1677
	.byte $8b, $00, $93
	.byte $41, $11
	.word @song2ref1701
@song2ref1746:
	.byte $8b, $00, $93, $2d, $9b, $00, $81, $21, $8b, $00, $81, $26, $9b, $00, $81, $25, $8b, $00, $93
	.byte $41, $15
	.word @song2ref1677
	.byte $8b, $00, $93
	.byte $41, $15
	.word @song2ref1701
	.byte $89, $00, $93
	.byte $41, $0c
	.word @song2ref1725
	.byte $41, $15
	.word @song2ref1677
	.byte $8b, $00, $93
	.byte $41, $15
	.word @song2ref1701
	.byte $89, $00, $93, $21, $8b, $00, $81, $26, $9b, $00, $81, $25, $9d, $00, $81
	.byte $41, $3c
	.word @song2ref1677
	.byte $41, $15
	.word @song2ref1677
	.byte $8b, $00, $93
	.byte $41, $11
	.word @song2ref1701
	.byte $41, $13
	.word @song2ref1746
	.byte $41, $15
	.word @song2ref1677
	.byte $8b, $00, $93
	.byte $41, $15
	.word @song2ref1701
	.byte $89, $00, $93
	.byte $41, $0c
	.word @song2ref1725
	.byte $41, $15
	.word @song2ref1677
	.byte $8b, $00, $93, $7c, $2c, $81, $7f, $2d, $89, $2c, $8b, $00, $93, $28, $89, $00, $93, $21, $8b, $00, $91
	.byte $41, $0c
	.word @song2ref931
	.byte $21, $8b, $00, $93
@song2ref1865:
	.byte $21, $9b, $00, $81, $23
@song2ref1870:
	.byte $8b, $00, $91, $23, $8b, $00, $81, $21, $8b, $00, $91, $23, $8b, $00, $93, $23, $9b, $00, $81, $21, $8b, $00, $81, $23
	.byte $89, $00, $93, $21, $8b, $00, $fb, $25, $81, $26, $9b, $25, $9b, $00, $81, $21, $9d, $00, $81, $1c, $9f, $9f, $00, $81
	.byte $41, $20
	.word @song2ref1865
	.byte $23, $8b, $00, $fb
	.byte $41, $0c
	.word @song2ref988
	.byte $23, $9f, $9f, $00, $81
	.byte $41, $35
	.word @song2ref1865
	.byte $41, $20
	.word @song2ref1865
	.byte $23, $8b, $00, $fb
	.byte $41, $0c
	.word @song2ref988
	.byte $23, $9b, $00, $81, $21, $9d, $00, $81
@song2ref1954:
	.byte $1c, $89, $00, $93, $21, $8b, $00, $91, $28, $8b, $00, $93, $1c, $89, $00, $81, $21, $9d, $00, $81, $28, $9b, $00, $81
	.byte $1c, $8b, $00, $81, $21, $89, $00, $93, $28, $8b, $00, $93
	.byte $41, $14
	.word @song2ref1954
	.byte $21, $89, $00, $93, $26, $8b, $00, $81, $25, $89, $00, $93, $21, $8b, $00, $93
	.byte $41, $24
	.word @song2ref1954
	.byte $41, $11
	.word @song2ref1954
	.byte $8b, $00, $93, $28, $9b, $00, $81, $23, $8b, $00, $81, $23, $89, $00, $93, $21, $8b, $00, $93
	.byte $41, $24
	.word @song2ref1954
	.byte $1c, $89, $00, $93, $21, $8b, $00, $91, $28, $8b, $00, $d7, $28, $8b, $00, $93, $28, $9f, $9f, $00, $a3, $21
	.byte $41, $1e
	.word @song2ref1870
	.byte $b5, $21
	.byte $41, $1b
	.word @song2ref1870
	.byte $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $7a, $4f, $02, $88
@song2ref2075:
	.byte $25, $8b, $00, $81, $26, $8b, $00, $81, $28, $ad, $00, $81, $28, $89, $00, $a5, $21, $ad, $00, $91, $77, $24, $81, $7a
	.byte $25, $9d, $23, $9b, $00, $81, $21, $9d, $00, $81, $20, $9b, $00, $81, $21, $9b, $00, $81, $23, $8b, $00, $93, $21, $e1
	.byte $00, $a3, $4f, $02
	.byte $41, $20
	.word @song2ref2075
@song2ref2130:
	.byte $23, $ad, $00, $81, $28, $89, $00, $a5, $25, $e1, $00, $a3, $4f, $02
	.byte $41, $30
	.word @song2ref2075
	.byte $41, $10
	.word @song2ref2075
	.byte $2d, $ad, $00, $81, $25, $81, $26, $9b, $25, $ad, $00, $81, $21, $9d, $00, $81
@song2ref2166:
	.byte $1c, $9b, $00, $81, $21, $9b, $00, $81, $20, $9d, $00, $81, $21, $e1, $00, $a3, $4f, $02
	.byte $41, $30
	.word @song2ref2075
	.byte $4f, $02
	.byte $41, $20
	.word @song2ref2075
	.byte $41, $0c
	.word @song2ref2130
	.byte $4f, $02
	.byte $41, $30
	.word @song2ref2075
	.byte $41, $10
	.word @song2ref2075
	.byte $2d, $ad, $00, $91, $21, $c3, $9d, $00, $83
	.byte $41, $0d
	.word @song2ref2166
	.byte $ff, $87, $9d, $00, $83, $28, $ab, $00, $83
@song2ref2224:
	.byte $28, $89, $00, $a5, $28, $bd, $00, $81, $25, $81, $26, $9d, $25, $9b, $00, $81, $23, $8b, $00, $81, $21, $8b, $00, $81
	.byte $23, $ab, $00, $83, $25, $89, $00, $a5, $21, $9b, $00, $81, $23, $bf, $00, $81, $25, $9f, $9f, $00, $81, $28, $ab, $00
	.byte $83
@song2ref2273:
	.byte $28, $89, $00, $a5, $2c, $81, $2d, $bd, $21, $bf, $00, $81, $25, $81, $26, $bb, $00, $81, $25, $bf, $00, $81, $21, $bd
	.byte $00, $81, $23, $bf, $00, $81, $25, $8b, $00, $81, $26, $8b, $00, $81, $26, $81, $28, $ad
	.byte $41, $2d
	.word @song2ref2224
	.byte $26, $81, $28, $ad
	.byte $41, $1e
	.word @song2ref2273
	.byte $21, $8b, $00, $81, $23, $8b, $00, $81, $78, $51, $fe, $40, $21, $e5, $21, $ff, $87, $9f, $00, $81, $21
@song2ref2346:
	.byte $e1, $00, $81, $21, $ff, $87, $9f, $00, $81, $1f, $e1, $00, $81, $21, $ff, $87, $9f, $00, $81, $1c
	.byte $41, $0d
	.word @song2ref2346
	.byte $1f, $ff, $87, $9f, $00, $81, $1f, $89, $00, $81, $72, $1f, $8b, $00, $a3, $74, $1f, $8b, $00, $81, $72, $1f, $8b, $00
	.byte $c5, $74, $1f, $8b, $00, $81, $72, $1f, $8b, $00, $81, $74, $1f, $9f, $9f, $00, $81, $51, $ff, $00, $1c, $ff, $ef, $ff
	.byte $ff, $00, $93, $42
	.word @song2ch6loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $8f, $77, $4f, $00, $8a, $2f, $95, $75, $2f, $95, $73
	.byte $2f, $95, $00, $ff, $a5
@song3ref22:
	.byte $48, $ff, $8f
@song3ref25:
	.byte $77, $4f, $00, $2f, $95, $75, $2f, $95, $73, $2f, $95, $00, $ff, $a5, $48, $ff, $8f, $77, $2c, $95, $75, $2c, $95, $73
	.byte $2c, $95, $00, $ff, $a5, $48, $df, $77, $2d, $95, $75, $2d, $95, $73, $2d, $95, $00, $f5, $77, $2f, $95, $75, $2f, $95
	.byte $73, $2f, $95, $00, $95
	.byte $41, $0d
	.word @song3ref22
	.byte $41, $25
	.word @song3ref25
	.byte $41, $0d
	.word @song3ref22
	.byte $41, $25
	.word @song3ref25
	.byte $48, $97, $71, $4f, $01
@song3ref95:
	.byte $27, $95, $28, $95, $27, $95, $28, $95, $73
@song3ref104:
	.byte $27, $95, $28, $95, $27, $95, $28, $95, $75, $27, $95, $28, $95, $27, $95, $28, $95, $27, $95, $77, $28, $95, $27, $95
	.byte $48, $28, $95
	.byte $41, $10
	.word @song3ref104
@song3ref134:
	.byte $73, $23, $95, $27, $95, $23, $95, $27, $95, $71, $23, $95, $27, $95, $23, $95, $48, $27, $95, $25, $95, $27, $95, $25
	.byte $95, $27, $95, $73
@song3ref162:
	.byte $25, $95, $27, $95, $25, $95, $27, $95, $75, $25, $95, $27, $95, $25, $95, $27, $95, $25, $95, $77, $27, $95, $25, $95
	.byte $48, $27, $95
	.byte $41, $10
	.word @song3ref162
@song3ref192:
	.byte $73, $20, $95, $27, $95, $20, $95, $27, $95, $71, $20, $95, $27, $95, $20, $95, $48, $27, $95
	.byte $41, $20
	.word @song3ref95
	.byte $41, $10
	.word @song3ref104
	.byte $41, $30
	.word @song3ref134
	.byte $41, $10
	.word @song3ref162
	.byte $41, $0e
	.word @song3ref192
	.byte $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $9f, $70, $51, $04, $c0, $4f, $02, $8e, $1c, $dd, $ff, $ff, $ff
	.byte $ff, $b7, $00, $85, $1b, $d5, $00, $85, $17, $d5, $00, $85, $19, $ff, $ff, $f5, $00, $85, $1c, $ff, $b5, $00, $85, $1b
	.byte $ff, $b5, $00, $85, $1c, $ff, $ff, $fd, $ff, $87, $00, $85, $1c, $8d, $00, $85, $78, $1c, $8d, $00, $85, $7c, $1e, $a5
	.byte $00, $85, $1c, $a5, $00, $85, $1b, $a5, $00, $85, $17, $a5, $00, $85, $19, $ff, $ff, $f1, $50, $d0, $25, $2c, $89, $7a
	.byte $20, $ff, $af, $50, $0a, $2c, $2a, $8b, $79, $1e, $ff, $b5, $00, $85
@song3ref340:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $70, $51, $03, $80, $2c, $dd, $ff, $ff, $9f, $d7, $00, $85
	.byte $76, $2f, $d5, $00, $85, $78, $2d, $d5, $00, $85, $2c, $d5, $00, $85, $2c, $ff, $b5, $00, $85, $2a, $d5, $00, $85, $28
	.byte $d5, $00, $85, $28, $ff, $b5, $00, $85, $27, $ff, $b5, $00, $85, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $88
@song3ref406:
	.byte $19, $ff, $ff, $fd, $19, $ff, $ff, $9d, $17, $dd, $16, $ff, $ff, $fd, $15, $ff, $bd, $17, $ff, $bd
	.byte $41, $14
	.word @song3ref406
	.byte $19, $ff, $ff, $fd, $19, $ff, $ed, $1b, $ad, $1c, $ad, $17, $ad, $16, $ff, $ff, $fd, $15, $ff, $bd, $17, $ff, $bd, $19
	.byte $ff, $ff, $fd, $ff, $bf, $1c, $ff, $bd, $15, $ff, $ff, $fd, $ff, $bf, $18, $ff, $bd, $19, $ff, $ff, $fd, $ff, $8f, $17
	.byte $95, $19, $95, $1c, $ad, $1e, $ad, $17, $ad, $14, $ad, $15, $ff, $ff, $fd, $12, $ff, $bd, $18, $ff, $bd, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $52, $ff
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $41, $0c
	.word @song3ref340
	.byte $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $4f, $02, $84, $0d, $ad, $7e, $14, $ad
@song3ref550:
	.byte $7d, $19, $ad
@song3ref553:
	.byte $14, $ad, $1c, $ad, $14, $ad, $7c, $10, $ad, $7a, $14, $a5, $00, $85, $7f, $0d, $ad, $7e, $14, $ad, $7d, $19, $ad, $14
	.byte $ad, $1b, $ad, $14, $ad, $7c, $0b, $ad, $7a, $14, $a5, $00, $85, $7f, $0a, $ad, $7e, $11, $ad, $7d, $16, $ad, $11, $ad
	.byte $19, $ad, $11, $ad, $7c, $0d, $ad, $7a, $11, $a5, $00, $85, $7f, $09, $ad, $7e, $10, $ad, $7d, $15, $ad, $10, $a5, $00
	.byte $85, $7e, $0b, $ad, $7d, $12, $ad, $7b, $19, $ad, $7a, $12, $a5, $00, $85, $7f, $0d, $ad, $7e, $14, $ad, $7c, $19, $ad
	.byte $7d
	.byte $41, $48
	.word @song3ref553
	.byte $41, $4a
	.word @song3ref550
@song3ref656:
	.byte $7d, $1b, $ad, $1c, $ff, $e5, $00, $85, $af, $7e, $14, $ad, $7b, $1b, $ad, $7d, $1c, $ff, $85, $00, $85, $7c, $10, $ad
	.byte $7b, $17, $a5, $00, $85, $7f, $09, $ad, $7e, $10, $ad, $7d, $17, $ad, $19, $ff, $e5, $00, $85, $af, $7e, $10, $ad, $7d
	.byte $17, $ad, $1c, $ad, $0c, $dd, $7b, $1b, $d5, $00, $85, $7f, $0d, $ad, $7e, $14, $ad
	.byte $41, $22
	.word @song3ref656
	.byte $7f, $06, $ad, $7e, $0d, $ad, $7d, $15, $ad, $1c, $ad, $0c, $dd, $7b, $1b, $cf, $00, $8b, $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $77, $4f, $01, $8a, $19, $ad, $79, $20, $ad, $7b, $27, $ad
@song3ref758:
	.byte $28, $dd, $27, $ad, $79, $28, $ad, $77, $23, $ad
@song3ref768:
	.byte $19, $ad, $79, $20, $ad, $7b, $27, $ad, $28, $ff, $8d, $79, $27, $ad, $77, $23, $ad, $19, $ad, $79, $20, $ad, $7b, $27
	.byte $ad, $25, $dd, $79, $2a, $dd, $77, $28, $95, $27, $95
	.byte $41, $13
	.word @song3ref768
	.byte $41, $23
	.word @song3ref758
	.byte $41, $13
	.word @song3ref768
	.byte $41, $23
	.word @song3ref758
	.byte $19, $ad, $79, $20, $ad, $7b, $27, $ad, $7c, $28, $ff, $8d, $79, $27, $ad, $77, $23, $ad, $75
@song3ref834:
	.byte $27, $8d, $00, $85, $28, $8d, $00, $85, $27, $8d, $00, $85, $28, $8d, $00, $85, $77
	.byte $41, $10
	.word @song3ref834
	.byte $79
	.byte $41, $10
	.word @song3ref834
	.byte $7b
	.byte $41, $10
	.word @song3ref834
	.byte $41, $10
	.word @song3ref834
	.byte $79
	.byte $41, $10
	.word @song3ref834
@song3ref869:
	.byte $77
@song3ref870:
	.byte $23, $8d, $00, $85, $27, $8d, $00, $85, $23, $8d, $00, $85, $27, $8d, $00, $85, $75
	.byte $41, $10
	.word @song3ref870
@song3ref890:
	.byte $25, $8d, $00, $85, $27, $8d, $00, $85, $25, $8d, $00, $85, $27, $8d, $00, $85, $77
	.byte $41, $10
	.word @song3ref890
	.byte $79
	.byte $41, $10
	.word @song3ref890
	.byte $7b
	.byte $41, $10
	.word @song3ref890
	.byte $41, $10
	.word @song3ref890
	.byte $79
	.byte $41, $10
	.word @song3ref890
@song3ref925:
	.byte $77
@song3ref926:
	.byte $20, $8d, $00, $85, $27, $8d, $00, $85, $20, $8d, $00, $85, $27, $8d, $00, $85, $75
	.byte $41, $10
	.word @song3ref926
	.byte $41, $10
	.word @song3ref834
	.byte $77
	.byte $41, $10
	.word @song3ref834
	.byte $79
	.byte $41, $10
	.word @song3ref834
	.byte $7b
	.byte $41, $10
	.word @song3ref834
	.byte $41, $10
	.word @song3ref834
	.byte $79
	.byte $41, $10
	.word @song3ref834
	.byte $41, $10
	.word @song3ref869
	.byte $75
	.byte $41, $10
	.word @song3ref870
	.byte $41, $10
	.word @song3ref890
	.byte $77
	.byte $41, $10
	.word @song3ref890
	.byte $79
	.byte $41, $10
	.word @song3ref890
	.byte $7b
	.byte $41, $10
	.word @song3ref890
	.byte $41, $10
	.word @song3ref890
	.byte $79
	.byte $41, $10
	.word @song3ref890
	.byte $41, $10
	.word @song3ref925
	.byte $75
	.byte $41, $10
	.word @song3ref926
	.byte $42
	.word @song3ch6loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $78, $4f, $02, $86
@song4ref9:
	.byte $19, $ff, $f9, $48, $bf, $17, $bb, $19, $fb, $48, $51, $ff, $00, $ff, $fb, $48, $fd, $78, $1e, $fb, $48, $ff, $bd, $1c
	.byte $bb, $48, $19, $fb, $51, $ff, $00, $fd, $48, $ff, $fb, $48, $78
	.byte $41, $16
	.word @song4ref9
	.byte $48, $78, $00, $ff, $f9, $48, $fd, $1b, $fb, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $78, $4f, $02, $86
@song4ref66:
	.byte $20, $ff, $f9, $bf, $1e, $bb, $20, $fb, $51, $ff, $00, $ff, $fb, $fd, $78, $23, $fb, $ff, $bd, $1e, $bb, $20, $fb, $51
	.byte $ff, $00, $fd, $ff, $fb, $78, $4f, $02
	.byte $41, $16
	.word @song4ref66
	.byte $78, $00, $ff, $f9, $fd, $1e, $fb, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $88
@song4ref113:
	.byte $19, $ff, $f9, $bf, $17, $bb, $15, $fb, $ff, $fb, $bf, $00, $bb, $19, $fb, $ff, $bd, $17, $bb, $15, $ff, $f9, $ff, $bd
	.byte $00, $bb
	.byte $41, $1a
	.word @song4ref113
	.byte $ff, $fb, $fd, $18, $fb, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $78, $80, $05, $ff, $f9, $df, $76, $05, $9b, $78, $05, $fb, $ff, $fb, $fd, $05, $fb, $ff, $dd, $76, $05, $9b, $78, $05
	.byte $ff, $f9, $ff, $dd, $76, $0e, $8d, $75, $0d
@song4ref184:
	.byte $8b, $78, $05, $9d, $76, $05, $9d, $75, $0e
@song4ref193:
	.byte $db, $78, $05, $9d, $76, $0e, $bb, $78, $05, $9d, $76, $05, $9d, $75, $0e
@song4ref208:
	.byte $bb
@song4ref209:
	.byte $78, $05, $9d, $76, $05, $9d, $75, $0e, $bb, $9f, $78, $05, $9d, $76, $0e, $ad, $74, $0e, $8b
	.byte $41, $0a
	.word @song4ref209
	.byte $41, $0b
	.word @song4ref208
	.byte $bb, $78, $05, $9d, $76, $05, $9d, $75, $0e, $9d, $76, $05, $8d, $75, $0e
	.byte $41, $10
	.word @song4ref184
	.byte $41, $0a
	.word @song4ref193
	.byte $db, $78, $05, $9d, $76, $0e, $bb, $78, $05, $9d, $74, $0e, $8d, $75, $0d, $8d, $76, $0e, $ad, $74, $0e, $ab, $78, $05
	.byte $9d, $76, $0e, $bb, $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $52, $80
@song4ref289:
	.byte $ff, $fb, $ff, $fb, $fd
@song4ref294:
	.byte $52, $80, $8b, $52, $88, $8d, $52, $90, $89, $52, $98, $8b, $52, $a0, $8d, $52, $a8, $8b, $52, $b0, $89, $52, $b8, $8b
	.byte $52, $c0, $8d, $52, $c8, $89, $52, $d0, $85, $83
@song4ref328:
	.byte $52, $d8, $8b, $52, $e0, $8d, $52, $e8, $8b, $52, $f0, $89, $52, $f8, $8b, $52, $ff, $83, $52, $f8, $85, $52, $f0, $83
	.byte $52, $e6, $81, $52, $e0, $83, $52, $d8, $85, $52, $d0, $83, $52, $c6, $81, $52, $c0, $83, $52, $b8, $85, $52, $b0, $83
	.byte $52, $a6, $81, $52, $a0, $83, $52, $98, $83, $52, $90, $83, $52, $88, $81, $52, $80, $fd, $ff, $fb, $ff, $fb
	.byte $41, $0a
	.word @song4ref294
	.byte $52, $d0, $89
	.byte $41, $13
	.word @song4ref328
	.byte $52, $90, $81, $52, $88, $81, $52, $80, $81
	.byte $41, $2b
	.word @song4ref289
	.byte $41, $0a
	.word @song4ref294
	.byte $52, $d0, $89
	.byte $41, $13
	.word @song4ref328
	.byte $52, $90, $81, $52, $88, $81, $52, $80, $81, $ff, $fb, $ff, $fb, $42
	.word @song4ch4loop
@song4ch5:
@song4ch5loop:
	.byte $79, $4f, $02, $84
@song4ref449:
	.byte $19, $9d, $20, $9d, $25, $9d, $20, $9b, $78, $28, $9d, $79, $20, $9d, $78, $27, $9d, $79, $20, $9b, $19, $9d, $20, $9d
	.byte $23, $9d, $1e, $9b, $15, $9d, $1c, $9d, $21, $9d, $1c, $9b, $25, $9d, $1c, $9d, $21, $9d, $1c, $9b, $15, $fb, $bf, $00
	.byte $bb
	.byte $41, $20
	.word @song4ref449
@song4ref501:
	.byte $78, $28, $9d, $79, $1c, $9d, $25, $9d, $1c, $9b, $15, $ff, $bb, $00, $bb, $4f, $02
	.byte $41, $2d
	.word @song4ref449
	.byte $41, $20
	.word @song4ref449
	.byte $41, $0d
	.word @song4ref501
	.byte $ff, $fb, $ff, $fb, $42
	.word @song4ch5loop
@song4ch6:
@song4ch6loop:
	.byte $7f, $4f, $01, $84
@song4ref539:
	.byte $19, $9d, $1c, $9d, $1b, $9d, $1c, $9b, $1e, $9d, $1c, $9d, $1b, $9d, $1c, $9b, $19, $9d, $1c, $9d, $1b, $9d, $17, $9b
	.byte $78, $19, $9d, $1c, $9d, $1b, $9d, $17, $9b, $77, $19, $9d, $76, $1c, $9d, $75, $1b, $9d, $74, $17, $9b, $72, $19, $9d
	.byte $00, $db, $fd, $7f
	.byte $41, $2b
	.word @song4ref539
	.byte $ff, $d9, $7f, $4f, $01
	.byte $41, $2d
	.word @song4ref539
	.byte $7f
	.byte $41, $2b
	.word @song4ref539
	.byte $ff, $d9, $ff, $fb, $ff, $fb, $42
	.word @song4ch6loop
@song5ch0:
@song5ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $72, $51, $02, $90, $4e, $02, $4f, $01, $84
@song5ref14:
	.byte $19, $9b, $00, $83, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $14, $91, $89, $00, $83
@song5ref31:
	.byte $1c, $9b, $00, $83, $1e, $9b, $00, $83, $17, $8f, $51, $fe, $20, $8b, $00, $83, $1c, $9b, $00, $83, $48
@song5ref52:
	.byte $1b, $9b, $00, $83, $1c
@song5ref57:
	.byte $9b, $00, $83, $19, $9b, $00, $83, $51, $02, $90, $1c, $9b, $00, $83
@song5ref71:
	.byte $1e, $9b, $00, $83, $14, $9b, $00, $83, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $48
@song5ref88:
	.byte $18, $8f, $51, $fe, $20, $8b, $00, $83, $1c, $9b, $00, $83, $1b, $9b, $00, $83, $18
	.byte $41, $13
	.word @song5ref57
	.byte $48
	.byte $41, $11
	.word @song5ref31
	.byte $41, $10
	.word @song5ref52
	.byte $48
	.byte $41, $10
	.word @song5ref71
	.byte $41, $0e
	.word @song5ref88
	.byte $9b, $00, $83, $48, $51, $02, $90, $4e, $02, $4f, $01
	.byte $41, $50
	.word @song5ref14
	.byte $41, $13
	.word @song5ref57
	.byte $48
	.byte $41, $11
	.word @song5ref31
	.byte $41, $10
	.word @song5ref52
	.byte $48
	.byte $41, $10
	.word @song5ref71
	.byte $41, $0e
	.word @song5ref88
	.byte $9b, $00, $83, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $78, $4f, $01
@song5ref163:
	.byte $88
@song5ref164:
	.byte $19, $ff, $d5, $14, $c5, $c7, $15, $ff, $d5, $18, $ff, $8d, $19, $ff, $8d, $c7, $14, $ff, $8d, $15, $c5, $ff, $8f, $14
	.byte $ff, $8d
	.byte $41, $17
	.word @song5ref164
	.byte $18, $ff, $8d, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $41, $1a
	.word @song5ref163
	.byte $41, $17
	.word @song5ref164
	.byte $18, $ff, $8d, $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
@song5ref213:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0f
	.word @song5ref213
	.byte $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $52, $ff
	.byte $41, $0f
	.word @song5ref213
	.byte $41, $0f
	.word @song5ref213
	.byte $42
	.word @song5ch4loop
@song5ch5:
@song5ch5loop:
	.byte $78, $4f, $02, $88, $20, $ff, $d5, $1e, $c5, $c7, $1c, $ff, $d5, $1b, $ff, $8d, $1c, $ff, $8d, $c7, $1b, $ff, $8d, $17
	.byte $c5, $ff, $8f, $18, $ff, $8d, $20, $ff, $d5, $1e, $c5, $c7, $23, $ff, $d5, $21, $ff, $8d, $20, $ff, $8d, $c7, $1e, $ff
	.byte $8d, $1c, $c5, $ff, $8f, $1b, $ff, $8d, $42
	.word @song5ch5loop
@song5ch6:
@song5ch6loop:
	.byte $75, $51, $02, $c0, $84
@song5ref312:
	.byte $25, $9b, $00, $83, $28, $9b, $00, $83, $2a, $9b, $00, $83, $20, $91, $89, $00, $83, $28, $9b, $00, $83, $2a, $9b, $00
	.byte $83
@song5ref337:
	.byte $23, $8f, $51, $fe, $50, $8b, $00, $83, $28, $9b, $00, $83, $27, $9b, $00, $83, $28
@song5ref354:
	.byte $9b, $00, $83, $25, $9b, $00, $83, $51, $02, $c0, $28, $9b, $00, $83, $2a, $9b, $00, $83, $20, $9b, $00, $83, $28, $9b
	.byte $00, $83, $2a, $9b, $00, $83, $24, $8f, $51, $fe, $50, $8b, $00, $83, $28, $9b, $00, $83, $27, $9b, $00, $83, $24
	.byte $41, $1b
	.word @song5ref354
	.byte $41, $37
	.word @song5ref337
	.byte $9b, $00, $83, $51, $02, $c0
	.byte $41, $50
	.word @song5ref312
	.byte $41, $1b
	.word @song5ref354
	.byte $41, $37
	.word @song5ref337
	.byte $9b, $00, $83, $42
	.word @song5ch6loop
