; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.
; DPCM Delta Counter effect is used, you must set FAMISTUDIO_USE_DELTA_COUNTER = 1.
; Project has DPCM bank-switching enabled in the project settings, you must set FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1 and implement bank switching.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_pwaa_music_v2_4=music_data_pwaa_music_v2_4
.endif

music_data_pwaa_music_v2_4:
	.byte 8
	.word @instruments
	.word @samples-5
; 00 : Questioning - Moderato
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Telling the Truth
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Detention Center
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Heartbroken Maya
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word @song3ch5
	.word @song3ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Marvin Grossberg
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word @song4ch5
	.word @song4ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 05 : The DL-6 Incident
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word @song5ch5
	.word @song5ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 06 : Class Trial
	.word @song6ch0
	.word @song6ch1
	.word @song6ch2
	.word @song6ch3
	.word @song6ch4
	.word @song6ch5
	.word @song6ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 07 : Victory
	.word @song7ch0
	.word @song7ch1
	.word @song7ch2
	.word @song7ch3
	.word @song7ch4
	.word @song7ch5
	.word @song7ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_pwaa_music_v2_4
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env6,@env7,@env0 ; 00 : Fade
	.word @env3,@env6,@env7,@env0 ; 01 : Lead 2
	.word @env1,@env6,@env7,@env2 ; 02 : Lead 1
	.word @env10,@env6,@env7,@env0 ; 03 : Kick
	.word @env8,@env6,@env7,@env0 ; 04 : Long Fade
	.word @env9,@env6,@env7,@env0 ; 05 : Arc In

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ce,$cd,$cc,$00,$04
@env2:
	.byte $00,$c0,$c1,$c2,$02,$c1,$c0,$bf,$be,$02,$bf,$00,$01
@env3:
	.byte $00,$cb,$cd,$cf,$cc,$00,$04
@env4:
	.byte $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env5:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$1d
@env9:
	.byte $00,$c7,$c8,$c9,$c9,$ca,$ca,$cb,$02,$cc,$03,$cd,$03,$ce,$05,$cf,$00,$0f
@env10:
	.byte $00,$cf,$ca,$c6,$c3,$c1,$c0,$00,$06

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7c, $4f, $01, $80
@song0ref9:
	.byte $22, $d3, $24, $d3, $25, $b5, $48, $9d, $24, $d1, $27, $b7, $24, $b5, $48, $25, $d3, $24, $d3, $20, $b5, $48, $9d, $1d
	.byte $d1, $20, $b7, $24, $b5, $48, $4f, $01
	.byte $41, $14
	.word @song0ref9
	.byte $1b, $d1, $1d, $b7, $24, $b5, $48, $4f, $01
	.byte $41, $1a
	.word @song0ref9
	.byte $48, $4f, $01
	.byte $41, $14
	.word @song0ref9
	.byte $1b, $d1, $1d, $b7, $24, $b5, $48, $4f, $01
	.byte $41, $1a
	.word @song0ref9
	.byte $48, $4f, $01
	.byte $41, $14
	.word @song0ref9
	.byte $1b, $d1, $1d, $b7, $24, $b5, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $7c
@song0ref91:
	.byte $4e, $01, $4f, $01, $80, $2e
@song0ref97:
	.byte $9b, $82, $0a, $93, $00, $83, $0a, $93, $00, $83, $80, $30, $99, $82, $0a, $95, $00, $83, $0a, $93, $00, $83, $80, $31
	.byte $99, $82, $0a, $93, $00, $83, $0a, $95, $00, $83, $80, $30, $99, $82, $0a, $93, $00, $83, $0a, $93, $00, $83, $80, $33
@song0ref145:
	.byte $9b, $82, $0a, $93, $00, $83, $80, $30, $99, $82, $0a, $93, $00, $83, $80, $31
	.byte $41, $13
	.word @song0ref97
@song0ref164:
	.byte $80, $2c, $99, $82, $0a, $93, $00, $83, $0a, $95, $00, $83, $80, $29, $99, $82, $0a, $93, $00, $83, $0a, $93, $00, $83
	.byte $80, $2c
	.byte $41, $0b
	.word @song0ref145
	.byte $41, $35
	.word @song0ref91
	.byte $41, $13
	.word @song0ref97
	.byte $80, $2c, $99, $82, $0a, $93, $00, $83, $0a, $95, $00, $83, $80, $27, $99, $82, $0a, $93, $00, $83, $0a, $93, $00, $83
	.byte $80, $29
	.byte $41, $0b
	.word @song0ref145
	.byte $41, $35
	.word @song0ref91
	.byte $41, $13
	.word @song0ref97
	.byte $41, $15
	.word @song0ref164
@song0ref237:
	.byte $9b, $82, $0a, $93, $00, $83, $80, $30, $99, $82, $08, $93, $00, $83, $80, $2e, $9b, $82, $06, $93, $00, $83, $06, $93
	.byte $00, $83, $80, $30, $99, $82, $06, $95, $00, $83, $06, $93, $00, $83, $80, $31, $99, $82, $06, $93, $00, $83, $06, $95
	.byte $00, $83, $80, $30, $99, $82, $06, $93, $00, $83, $06, $93, $00, $83, $80, $33, $9b, $82, $06, $93, $00, $83, $80, $30
	.byte $99, $82, $06, $93, $00, $83, $80, $31, $9b, $82, $08, $93, $00, $83, $08, $93, $00, $83, $80, $30, $99, $82, $08, $95
	.byte $00, $83, $08, $93, $00, $83, $80, $2c, $99, $82, $08, $93, $00, $83, $08, $95, $00, $83, $80, $27, $99, $82, $08, $93
	.byte $00, $83, $08, $93, $00, $83, $80, $29, $9b, $82, $08, $93, $00, $83, $80, $30, $99, $82, $08, $93, $00, $83
	.byte $41, $35
	.word @song0ref91
	.byte $41, $13
	.word @song0ref97
	.byte $41, $15
	.word @song0ref164
	.byte $41, $73
	.word @song0ref237
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $9d, $82
@song0ref397:
	.byte $16, $93, $00, $83, $16, $93, $00, $9f, $16, $95, $00, $83, $16, $93, $00, $9f, $16, $93, $00, $83, $16, $95, $00, $9f
	.byte $16, $93, $00, $83, $16, $93, $00, $a1, $16, $93, $00, $9f, $16, $93, $00, $83, $9d
	.byte $41, $29
	.word @song0ref397
	.byte $41, $29
	.word @song0ref397
	.byte $41, $29
	.word @song0ref397
	.byte $41, $29
	.word @song0ref397
	.byte $41, $24
	.word @song0ref397
@song0ref453:
	.byte $14, $93, $00, $83, $9d, $12, $93, $00, $83, $12, $93, $00, $9f, $12, $95, $00, $83, $12, $93, $00, $9f, $12, $93, $00
	.byte $83, $12, $95, $00, $9f, $12, $93, $00, $83, $12, $93, $00, $a1, $12, $93, $00, $9f, $12, $93, $00, $83, $9d, $14, $93
	.byte $00, $83, $14, $93, $00, $9f, $14, $95, $00, $83, $14, $93, $00, $9f, $14, $93, $00, $83, $14, $95, $00, $9f, $14, $93
	.byte $00, $83, $14, $93, $00, $a1, $14, $93, $00, $9f, $14, $93, $00, $83, $9d
	.byte $41, $29
	.word @song0ref397
	.byte $41, $24
	.word @song0ref397
	.byte $41, $56
	.word @song0ref453
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref553:
	.byte $ff, $e3, $ff, $e3, $ff, $e3, $ff, $e3, $ff, $e3, $ff, $e3
	.byte $41, $0c
	.word @song0ref553
	.byte $41, $0c
	.word @song0ref553
	.byte $41, $0c
	.word @song0ref553
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $52, $80
	.byte $41, $0c
	.word @song0ref553
	.byte $41, $0c
	.word @song0ref553
	.byte $41, $0c
	.word @song0ref553
	.byte $41, $0c
	.word @song0ref553
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $41, $0c
	.word @song0ref553
	.byte $ff, $e3, $ff, $e3, $72, $51, $03, $70, $4f, $01, $82, $1d, $b7, $ff, $a9, $72, $51, $03, $70, $24
@song0ref619:
	.byte $b7, $ff, $a9, $72, $51, $03, $70, $25, $b7, $ff, $a9, $72, $51, $03, $70, $24, $b7, $ff, $a9, $72, $51, $03, $70, $1d
	.byte $b7, $ff, $a9, $72, $51, $03, $70, $22
	.byte $41, $0b
	.word @song0ref619
	.byte $72, $51, $03, $70, $22
	.byte $41, $0b
	.word @song0ref619
	.byte $72, $51, $03, $70, $20, $b7, $ff, $a7, $00, $72, $51, $03, $70, $22
	.byte $41, $0b
	.word @song0ref619
	.byte $72, $51, $03, $70, $20, $b7, $ff, $a7, $00, $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $0c
	.word @song0ref553
	.byte $ff, $e3, $ff, $e3, $72, $51, $05, $b0, $4f, $01, $82
@song0ref706:
	.byte $16, $b7, $ff, $a9, $71, $51, $03, $60, $1d, $b7, $ff, $a9, $71, $51, $04, $70, $22, $b7, $ff, $a9, $71, $51, $03, $60
	.byte $1d, $b7, $ff, $a9, $72, $51, $04, $80, $1e, $b7, $ff, $a9, $ff, $e3, $72, $51, $05, $a0, $14, $b7, $ff, $a9, $72, $51
	.byte $04, $90, $1b, $b7, $ff, $a9, $72, $51, $05, $b0
	.byte $41, $1a
	.word @song0ref706
	.byte $72, $51, $04, $90, $18, $b7, $ff, $a7, $00, $42
	.word @song0ch6loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $01
	.byte $80
@song1ref13:
	.byte $22, $83, $75, $22
@song1ref17:
	.byte $8b, $7a, $1d, $83, $75, $1d, $8b, $7a, $24, $83, $75, $24, $8b, $7a
@song1ref31:
	.byte $1d, $83, $75, $1d, $8b
@song1ref36:
	.byte $7a, $25, $83, $75, $25, $8b, $7a, $1d, $83, $75, $1d, $8b, $7a, $24, $83, $75, $24, $8b, $7a, $1d, $83, $75, $1d, $8b
	.byte $7a, $27, $83, $75, $27
	.byte $41, $1d
	.word @song1ref17
@song1ref68:
	.byte $48
@song1ref69:
	.byte $7a, $20, $83, $75, $20, $8b, $7a, $1d, $83, $75, $1d, $8b, $7a, $22, $83, $75, $22, $8b, $7a, $1d, $83, $75, $1d, $8b
	.byte $7a
	.byte $41, $23
	.word @song1ref13
	.byte $8b, $7a, $1d, $83, $75, $1d, $8b, $7a, $24, $83, $75, $24, $8b, $7a, $1d, $83, $75, $1d, $8b, $48
	.byte $41, $10
	.word @song1ref36
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $20
	.word @song1ref13
	.byte $48, $7a, $27, $83, $75, $27
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $10
	.word @song1ref13
	.byte $48
	.byte $41, $13
	.word @song1ref36
	.byte $41, $1d
	.word @song1ref17
@song1ref150:
	.byte $7a, $25, $83, $75, $25, $8b, $7a, $1d, $83, $75, $1d, $8b, $7a, $2c, $83, $75, $2c, $8b, $7a, $1d, $83, $75, $1d, $8b
	.byte $48, $7a
	.byte $41, $23
	.word @song1ref13
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref68
	.byte $7a
	.byte $41, $23
	.word @song1ref13
	.byte $8b, $7a, $1d, $83, $75, $1d, $8b, $7a, $24, $83, $75, $24, $8b, $7a, $1d, $83, $75, $1d, $8b, $48
	.byte $41, $10
	.word @song1ref36
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $20
	.word @song1ref13
	.byte $48, $7a, $27, $83, $75, $27
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $10
	.word @song1ref13
	.byte $48
	.byte $41, $13
	.word @song1ref36
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref150
	.byte $48, $00, $ff, $ff, $bd, $48, $ff, $9f, $71, $51, $01, $60, $49, .lobyte(@env4), .hibyte(@env4), $8a, $24, $ff, $9d
	.byte $48, $ff, $9d, $00, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $78, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $01
@song1ref279:
	.byte $84
@song1ref280:
	.byte $22, $ff, $ff, $bd, $20, $cd, $1e, $ff, $ed, $cf, $20, $cd, $22, $ff, $9d, $ff, $9f, $1d, $cd, $1e, $cd, $ff, $ef, $20
	.byte $cd
	.byte $41, $16
	.word @song1ref280
	.byte $c7, $72, $51, $05, $f0, $4f, $00, $01, $e1, $93, $00, $ff, $ff, $bd, $ff, $9f, $71, $51, $01, $60, $49, .lobyte(@env4)
	.byte .hibyte(@env4), $8a, $1e, $ff, $9d, $ff, $9d, $00, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $4e, $02
	.byte $41, $19
	.word @song1ref279
	.byte $22, $ff, $ff, $b5, $00, $85, $20, $c5, $00, $85, $1e, $ff, $ed, $c7, $00, $85, $20, $c5, $00, $85, $22, $ff, $9d, $ff
	.byte $97, $00, $85, $1d, $c5, $00, $85, $1e, $cd, $ff, $e7, $00, $d5, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref396:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $ff, $ff, $bf, $ff, $c7, $72, $51, $05, $f0, $84, $07, $e1, $93, $86
@song1ref434:
	.byte $05, $91, $00, $91, $05, $91, $00, $91, $10, $91, $00, $ff, $89, $10, $91, $00, $b9, $a7, $05, $91, $10, $91
	.byte $41, $10
	.word @song1ref434
	.byte $91, $05, $91, $05, $91, $80, $11, $a5, $00, $a5, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $52, $ff
	.byte $41, $1c
	.word @song1ref396
	.byte $ff, $bf, $52, $80, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f, $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $78, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $01, $84, $16, $ff, $ff, $bd, $14, $cd, $12, $ff, $ed, $cf, $14
	.byte $cd, $16, $ff, $9d, $ff, $9f, $11, $cd, $12, $cd, $ff, $ef, $14, $cd, $7f, $80, $0a, $91, $78, $84, $16, $91, $7f, $80
	.byte $0a, $91, $78, $84, $16, $ff, $c5
@song1ref544:
	.byte $7f, $80, $0c, $91, $0d, $91, $0f, $91, $0c, $91, $0d, $91, $0c, $91, $08, $91, $06, $91, $78, $84, $12, $91, $7f, $80
	.byte $06, $91, $78, $84, $12, $ff, $b1, $93, $7f, $80, $0a, $91, $08, $91, $78, $84, $12, $91, $7f, $80, $0a, $91, $0d, $91
	.byte $0c, $91, $0f, $91, $0a, $91, $78, $84, $16, $91, $7f, $80, $0a, $91, $78, $84, $16, $e1, $e3, $7f, $80, $11, $91, $0f
	.byte $91, $0d, $91, $0c, $91, $78, $84, $11, $91, $7f, $80, $08, $91, $78, $84, $11, $91, $7f, $80, $06, $91, $78, $84, $12
	.byte $91, $7f, $80, $06, $91, $78, $84, $12, $91, $ff, $c7, $7f, $80, $08, $9b, $00, $87, $08, $91, $0c, $91, $0d, $a5
@song1ref663:
	.byte $0a, $9b, $00, $87, $0a, $a5, $00, $ff, $ed, $a7, $08, $a5, $0a, $9b, $00, $87, $0a, $a5, $71, $51, $01, $60, $49, .lobyte(@env4)
	.byte .hibyte(@env4), $8a, $16, $ff, $9d, $ff, $9d, $00, $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $7a, $4e, $01, $49, .lobyte(@env0), .hibyte(@env0), $4a, $4f, $01, $84
	.byte $41, $23
	.word @song1ref13
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $23
	.word @song1ref13
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $23
	.word @song1ref13
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref69
	.byte $7a
	.byte $41, $23
	.word @song1ref13
	.byte $41, $1d
	.word @song1ref17
	.byte $41, $10
	.word @song1ref150
	.byte $7f, $80, $0a, $91, $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $0a, $91, $7a, $84
	.byte $41, $17
	.word @song1ref31
	.byte $41, $11
	.word @song1ref17
	.byte $41, $10
	.word @song1ref544
	.byte $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $06, $91, $7a, $84
	.byte $41, $17
	.word @song1ref31
	.byte $41, $11
	.word @song1ref17
	.byte $7f, $80, $0a, $91, $08, $91, $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $0a, $91, $0d, $91, $0c, $91, $0f, $91, $0a
	.byte $91, $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $0a, $91, $7a, $84
	.byte $41, $17
	.word @song1ref31
	.byte $41, $11
	.word @song1ref17
	.byte $7f, $80, $11, $91, $0f, $91, $0d, $91, $0c, $91, $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $08, $91, $7a, $84, $1d
	.byte $83, $75, $1d, $8b, $7f, $80, $06, $91, $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $06, $91, $7a, $84
	.byte $41, $17
	.word @song1ref31
	.byte $41, $15
	.word @song1ref17
	.byte $7f, $80, $08, $91, $7a, $84, $1d, $83, $75, $1d, $8b, $7f, $80, $08, $91, $0c, $91, $0d, $91, $7a, $84, $1d, $83, $75
	.byte $1d, $8b, $7f, $80
	.byte $41, $12
	.word @song1ref663
	.byte $71, $51, $01, $60, $49, .lobyte(@env4), .hibyte(@env4), $8a, $19, $ff, $9d, $ff, $9d, $00, $42
	.word @song1ch6loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $79, $4f, $01, $80
@song2ref9:
	.byte $23, $dd, $00, $85, $26, $ff, $a9, $00, $9f, $24, $a9, $00, $85, $26, $a7
@song2ref24:
	.byte $00, $85, $48, $24, $dd, $00, $85, $23, $ff, $a9, $00, $9f, $21, $db, $00, $85, $48, $23, $dd, $00, $85, $1c, $db, $00
	.byte $85, $1f, $dd, $00, $85, $1e, $db, $00, $85, $48, $1e, $ff, $c3, $00, $85, $1f, $ff, $b3, $00, $95, $48
	.byte $41, $09
	.word @song2ref9
	.byte $2a, $db
	.byte $41, $24
	.word @song2ref24
	.byte $1c, $ff, $c3, $00, $85
@song2ref82:
	.byte $48
@song2ref83:
	.byte $28, $97, $26, $97, $28, $b1, $00, $b1, $26, $97, $00, $95
	.byte $41, $08
	.word @song2ref83
	.byte $2a, $af, $48, $2b, $b1, $2a, $b1, $26, $b1, $21, $af, $23, $ff, $99, $26, $af
	.byte $41, $0c
	.word @song2ref82
	.byte $41, $08
	.word @song2ref83
	.byte $2a, $af, $48, $2b, $b1, $2a, $b1, $21, $b1, $26, $af, $23, $ff, $99, $21, $af, $48, $23, $e5, $1c, $e3, $21, $e5, $1f
	.byte $a9, $00, $85, $21, $a7, $00, $85, $48, $1e, $ff, $ff, $ff, $81, $00, $95, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $77, $4f, $01, $80
@song2ref167:
	.byte $1c, $ff, $cb, $1e
@song2ref171:
	.byte $ff, $cb, $1c, $ff, $ff, $e7, $75, $1c, $97, $72, $1c, $95, $77, $1c, $ff, $cb, $15, $ff, $cb, $17, $ff, $ff, $e7, $75
	.byte $17, $97, $72, $17, $95, $77
	.byte $41, $1c
	.word @song2ref167
@song2ref204:
	.byte $77, $15, $97, $75, $15, $97, $77, $1c, $97, $75, $1c, $97, $77, $23, $97, $75, $23, $97, $77, $24, $af
@song2ref225:
	.byte $75, $24, $97, $72, $24, $97, $77, $23, $97, $75, $23, $97, $77, $1c, $97, $75, $1c, $97, $77, $15, $97, $75, $15, $95
@song2ref249:
	.byte $77, $1a, $97, $75, $1a
@song2ref254:
	.byte $97, $77, $21, $97, $75, $21, $97, $77, $26, $97, $75, $26, $97, $77, $28, $af
@song2ref270:
	.byte $75, $28, $97, $72, $28, $97, $77, $26, $97, $75, $26, $97, $77, $1f, $97, $75, $1f, $97, $77, $17, $97, $75, $17, $95
	.byte $41, $22
	.word @song2ref204
	.byte $77, $1e, $97, $75, $1e
	.byte $41, $08
	.word @song2ref254
	.byte $95
@song2ref306:
	.byte $77, $13, $97, $75, $13, $97, $77, $1a, $97, $75, $1a, $97, $77, $1f, $97, $75, $1f, $97, $77, $21, $97, $75, $21, $95
	.byte $77, $1c, $ff, $ff, $ff, $99, $73, $1e, $ff, $ff, $e7, $72, $1e, $97, $71, $1e, $95, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $84
@song2ref352:
	.byte $1c, $ff, $cb, $1b, $ff, $cb, $1a, $ff, $cb, $19, $ff, $cb, $18, $ff, $cb, $1a, $ff, $cb, $1c, $ff, $ff, $ff, $81, $00
	.byte $95
	.byte $41, $16
	.word @song2ref352
	.byte $99, $15, $ff, $ff, $ff, $99, $1c, $ff, $ff, $ff, $99, $15, $ff, $ff, $ff, $99, $1a, $ff, $cb, $1f, $ff, $cb, $18, $ff
	.byte $ff, $ff, $99, $1b, $ff, $ff, $ff, $81, $00, $95, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref418:
	.byte $77, $1f, $ff, $cb, $21, $ff, $cb, $1f, $ff, $ff, $e7, $75, $1f, $97, $72, $1f, $95, $77, $1f, $ff, $cb, $1c
	.byte $41, $0a
	.word @song2ref171
	.byte $41, $12
	.word @song2ref418
	.byte $41, $0a
	.word @song2ref171
	.byte $00, $b1
	.byte $41, $0b
	.word @song2ref204
	.byte $95, $77, $24, $b1
	.byte $41, $0b
	.word @song2ref225
	.byte $95, $77, $15, $97, $75, $15, $97
	.byte $41, $0b
	.word @song2ref249
	.byte $95, $77, $28, $b1
	.byte $41, $0b
	.word @song2ref270
	.byte $95, $77, $17, $97, $75, $17, $97
	.byte $41, $0b
	.word @song2ref204
	.byte $95, $77, $24, $b1
	.byte $41, $0b
	.word @song2ref225
	.byte $95, $77, $15, $97, $75, $15, $97, $77, $1a, $97, $75, $1a, $97, $77, $1e, $97, $75, $1e, $97, $77, $21, $97, $75, $21
	.byte $95, $77, $26, $97, $75, $26, $97
	.byte $41, $0b
	.word @song2ref306
	.byte $95, $77, $1f, $ff, $ff, $ff, $99, $1b, $ff, $ff, $e7, $75, $1b, $97, $72, $1b, $95, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $52, $ff
@song2ref552:
	.byte $ff, $ff, $ff, $9b, $ff, $ff, $ff, $9b
	.byte $41, $08
	.word @song2ref552
	.byte $41, $08
	.word @song2ref552
	.byte $41, $08
	.word @song2ref552
	.byte $41, $08
	.word @song2ref552
	.byte $41, $08
	.word @song2ref552
	.byte $41, $08
	.word @song2ref552
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $7b, $4f, $01, $80
@song2ref586:
	.byte $1f, $b1, $78, $1c, $b1, $23, $db, $00, $85, $21, $ff, $c3, $00, $85, $7b, $1c, $b1, $78, $1a, $b1, $1c
@song2ref607:
	.byte $db, $00, $85, $1f, $ff, $c3, $00, $85, $7b, $1c, $b1, $78, $18, $b1, $13
@song2ref622:
	.byte $db, $00, $85, $15, $e5, $1a, $db, $00, $85, $7b, $17, $b1, $78, $13, $b1, $17, $b1, $13, $af, $1c, $ff, $ab, $00, $9d
	.byte $7b
	.byte $41, $11
	.word @song2ref586
	.byte $1f
	.byte $41, $0c
	.word @song2ref607
	.byte $1c
	.byte $41, $11
	.word @song2ref622
	.byte $17, $ff, $ab, $00, $9d, $18, $ff, $ff, $ff, $91, $00, $85, $17, $ff, $ff, $ff, $91
@song2ref675:
	.byte $00, $85, $1c, $ff, $ff, $ff, $91, $00, $85, $1e, $ff, $cb, $79, $1f, $ff, $c3
	.byte $41, $09
	.word @song2ref675
	.byte $1b, $ff, $ff, $f9, $00, $9d, $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $78, $4f, $02, $80
@song2ref708:
	.byte $1c, $ff, $c3, $00, $85, $1b, $e5, $76, $1e, $db, $00, $85, $78, $1a, $e5, $76, $1f, $db, $00, $85, $78, $19, $ff, $c3
	.byte $00, $85, $18, $ff, $c3, $00, $85, $1a, $e5, $76, $1e, $db, $00, $85, $78, $1c, $e5, $76, $1f, $db, $00, $85, $78, $1c
	.byte $ff, $ab, $00, $9d
	.byte $41, $2c
	.word @song2ref708
	.byte $76, $15, $b1, $75
@song2ref767:
	.byte $1c, $b1, $73, $23, $a9, $00, $85, $24, $db, $00, $85, $75, $23, $b1, $1c, $db, $00, $85, $76, $1a, $b1, $21, $b1, $73
	.byte $26, $b1, $72, $28, $e3, $73, $26, $b1, $76, $1f, $db, $00, $85, $15, $b1
	.byte $41, $0a
	.word @song2ref767
	.byte $23, $b1, $76, $1c, $db, $00, $85, $1a, $b1, $1e, $b1, $75, $21, $b1, $73, $26, $a7, $00, $85, $76, $13, $b1, $1a, $b1
	.byte $1f, $b1, $21, $a7, $00, $85, $78, $18, $e5, $76, $1c, $db, $00, $85, $78, $18, $ff, $c3, $00, $85, $1b, $ff, $ff, $f9
	.byte $00, $9d, $42
	.word @song2ch6loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $77, $4f, $01, $88, $19, $ad, $79, $20, $ad, $7b, $27, $ad
@song3ref17:
	.byte $28, $dd, $27, $ad, $79, $28, $ad, $77, $23, $ad
@song3ref27:
	.byte $48, $19, $ad, $79, $20, $ad, $7b, $27, $ad, $28, $ff, $8d, $79, $27, $ad, $77, $23, $ad, $48, $19, $ad, $79, $20, $ad
	.byte $7b, $27, $ad, $25, $dd, $79, $2a, $dd, $77, $28, $95, $27, $95
	.byte $41, $13
	.word @song3ref27
	.byte $41, $23
	.word @song3ref17
	.byte $41, $13
	.word @song3ref27
	.byte $41, $23
	.word @song3ref17
	.byte $48, $19, $ad, $79, $20, $ad, $7b, $27, $ad, $7c, $28, $ff, $8d, $79, $27, $ad, $77, $23, $ad, $48, $75
@song3ref97:
	.byte $27, $8d, $00, $85, $28, $8d, $00, $85, $27, $8d, $00, $85, $28, $8d, $00, $85, $77
	.byte $41, $10
	.word @song3ref97
	.byte $79
	.byte $41, $10
	.word @song3ref97
	.byte $7b
	.byte $41, $10
	.word @song3ref97
	.byte $48
	.byte $41, $10
	.word @song3ref97
	.byte $79
	.byte $41, $10
	.word @song3ref97
@song3ref133:
	.byte $77
@song3ref134:
	.byte $23, $8d, $00, $85, $27, $8d, $00, $85, $23, $8d, $00, $85, $27, $8d, $00, $85, $75
	.byte $41, $10
	.word @song3ref134
@song3ref154:
	.byte $48
@song3ref155:
	.byte $25, $8d, $00, $85, $27, $8d, $00, $85, $25, $8d, $00, $85, $27, $8d, $00, $85, $77
	.byte $41, $10
	.word @song3ref155
	.byte $79
	.byte $41, $10
	.word @song3ref155
	.byte $7b
	.byte $41, $10
	.word @song3ref155
	.byte $41, $10
	.word @song3ref154
	.byte $79
	.byte $41, $10
	.word @song3ref155
@song3ref190:
	.byte $77
@song3ref191:
	.byte $20, $8d, $00, $85, $27, $8d, $00, $85, $20, $8d, $00, $85, $27, $8d, $00, $85, $75
	.byte $41, $10
	.word @song3ref191
	.byte $48
	.byte $41, $10
	.word @song3ref97
	.byte $77
	.byte $41, $10
	.word @song3ref97
	.byte $79
	.byte $41, $10
	.word @song3ref97
	.byte $7b
	.byte $41, $10
	.word @song3ref97
	.byte $48
	.byte $41, $10
	.word @song3ref97
	.byte $79
	.byte $41, $10
	.word @song3ref97
	.byte $41, $10
	.word @song3ref133
	.byte $75
	.byte $41, $10
	.word @song3ref134
	.byte $41, $10
	.word @song3ref154
	.byte $77
	.byte $41, $10
	.word @song3ref155
	.byte $79
	.byte $41, $10
	.word @song3ref155
	.byte $7b
	.byte $41, $10
	.word @song3ref155
	.byte $41, $10
	.word @song3ref154
	.byte $79
	.byte $41, $10
	.word @song3ref155
	.byte $41, $10
	.word @song3ref190
	.byte $75
	.byte $41, $10
	.word @song3ref191
	.byte $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $4f, $02, $80, $0d, $ad, $7e, $14, $ad
@song3ref283:
	.byte $7d, $19, $ad
@song3ref286:
	.byte $14, $ad, $1c, $ad, $14, $ad, $7c, $10, $ad, $7a, $14, $a5, $00, $85, $7f, $0d, $ad, $7e, $14, $ad, $7d, $19, $ad, $14
	.byte $ad, $1b, $ad, $14, $ad, $7c, $0b, $ad, $7a, $14, $a5, $00, $85, $7f, $0a, $ad, $7e, $11, $ad, $7d, $16, $ad, $11, $ad
	.byte $19, $ad, $11, $ad, $7c, $0d, $ad, $7a, $11, $a5, $00, $85, $7f, $09, $ad, $7e, $10, $ad, $7d, $15, $ad, $10, $a5, $00
	.byte $85, $7e, $0b, $ad, $7d, $12, $ad, $7b, $19, $ad, $7a, $12, $a5, $00, $85, $7f, $0d, $ad, $7e, $14, $ad, $7c, $19, $ad
	.byte $7d
	.byte $41, $48
	.word @song3ref286
	.byte $41, $4a
	.word @song3ref283
@song3ref389:
	.byte $7d, $1b, $ad, $1c, $ff, $e5, $00, $85, $af, $7e, $14, $ad, $7b, $1b, $ad, $7d, $1c, $ff, $85, $00, $85, $7c, $10, $ad
	.byte $7b, $17, $a5, $00, $85, $7f, $09, $ad, $7e, $10, $ad, $7d, $17, $ad, $19, $ff, $e5, $00, $85, $af, $7e, $10, $ad, $7d
	.byte $17, $ad, $1c, $ad, $0c, $dd, $7b, $1b, $d5, $00, $85, $7f, $0d, $ad, $7e, $14, $ad
	.byte $41, $22
	.word @song3ref389
	.byte $7f, $06, $ad, $7e, $0d, $ad, $7d, $15, $ad, $1c, $ad, $0c, $dd, $7b, $1b, $cf, $00, $8b, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $82
@song3ref480:
	.byte $19, $ff, $ff, $fd, $19, $ff, $ff, $9d, $17, $dd, $16, $ff, $ff, $fd, $15, $ff, $bd, $17, $ff, $bd
	.byte $41, $14
	.word @song3ref480
	.byte $19, $ff, $ff, $fd, $19, $ff, $ed, $1b, $ad, $1c, $ad, $17, $ad, $16, $ff, $ff, $fd, $15, $ff, $bd, $17, $ff, $bd, $19
	.byte $ff, $ff, $fd, $ff, $bf, $1c, $ff, $bd, $15, $ff, $ff, $fd, $ff, $bf, $18, $ff, $bd, $19, $ff, $ff, $fd, $ff, $8f, $17
	.byte $95, $19, $95, $1c, $ad, $1e, $ad, $17, $ad, $14, $ad, $15, $ff, $ff, $fd, $12, $ff, $bd, $18, $ff, $bd, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
@song3ref576:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $52, $80
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $41, $0c
	.word @song3ref576
	.byte $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $9f, $70, $51, $04, $c0, $4f, $01, $8a, $1c, $dd, $ff, $ff, $ff
	.byte $ff, $b7, $00, $85, $1b, $d5, $00, $85, $17, $d5, $00, $85, $19, $ff, $ff, $f5, $00, $85, $1c, $ff, $b5, $00, $85, $1b
	.byte $ff, $b5, $00, $85, $1c, $ff, $ff, $fd, $ff, $87, $00, $85, $1c, $8d, $00, $85, $78, $1c, $8d, $00, $85, $7c, $1e, $a5
	.byte $00, $85, $1c, $a5, $00, $85, $1b, $a5, $00, $85, $17, $a5, $00, $85, $19, $ff, $ff, $f1, $50, $d0, $25, $2c, $89, $7a
	.byte $20, $ff, $af, $50, $0a, $2c, $2a, $8b, $79, $1e, $ff, $b5, $00, $85
	.byte $41, $0c
	.word @song3ref576
	.byte $70, $51, $03, $80, $2c, $dd, $ff, $ff, $9f, $d7, $00, $85, $76, $2f, $d5, $00, $85, $78, $2d, $d5, $00, $85, $2c, $d5
	.byte $00, $85, $2c, $ff, $b5, $00, $85, $2a, $d5, $00, $85, $28, $d5, $00, $85, $28, $ff, $b5, $00, $85, $27, $ff, $b5, $00
	.byte $85, $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $ff, $8f, $77, $4f, $00, $88, $2f, $95, $75, $2f, $95, $73, $2f, $95, $00, $ff, $a5
@song3ref808:
	.byte $ff, $8f
@song3ref810:
	.byte $77, $4f, $00, $2f, $95, $75, $2f, $95, $73, $2f, $95, $00, $ff, $a5, $ff, $8f, $77, $2c, $95, $75, $2c, $95, $73, $2c
	.byte $95, $00, $ff, $a5, $df, $77, $2d, $95, $75, $2d, $95, $73, $2d, $95, $00, $f5, $77, $2f, $95, $75, $2f, $95, $73, $2f
	.byte $95, $00, $95
	.byte $41, $0d
	.word @song3ref808
	.byte $41, $25
	.word @song3ref810
	.byte $41, $0d
	.word @song3ref808
	.byte $41, $25
	.word @song3ref810
	.byte $97, $71, $4f, $01
@song3ref877:
	.byte $27, $95, $28, $95, $27, $95, $28, $95, $73
@song3ref886:
	.byte $27, $95, $28, $95, $27, $95, $28, $95, $75, $27, $95, $28, $95, $27, $95, $28, $95, $27, $95, $77, $28, $95, $27, $95
	.byte $28, $95
	.byte $41, $10
	.word @song3ref886
@song3ref915:
	.byte $73, $23, $95, $27, $95, $23, $95, $27, $95, $71, $23, $95, $27, $95, $23, $95, $27, $95, $25, $95, $27, $95, $25, $95
	.byte $27, $95, $73
@song3ref942:
	.byte $25, $95, $27, $95, $25, $95, $27, $95, $75, $25, $95, $27, $95, $25, $95, $27, $95, $25, $95, $77, $27, $95, $25, $95
	.byte $27, $95
	.byte $41, $10
	.word @song3ref942
@song3ref971:
	.byte $73, $20, $95, $27, $95, $20, $95, $27, $95, $71, $20, $95, $27, $95, $20, $95, $27, $95
	.byte $41, $20
	.word @song3ref877
	.byte $41, $10
	.word @song3ref886
	.byte $41, $30
	.word @song3ref915
	.byte $41, $10
	.word @song3ref942
	.byte $41, $0e
	.word @song3ref971
	.byte $42
	.word @song3ch6loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $00, $cd, $4f, $00, $80
@song4ref10:
	.byte $27, $97, $00, $ff, $83, $23, $97, $00, $97, $22, $99, $48, $00, $cd, $7e, $4f, $01, $14
@song4ref28:
	.byte $97, $16, $97, $17, $99, $16, $b1, $14, $99, $11, $b1, $0f, $99, $48, $00, $cd, $4f, $00
	.byte $41, $0d
	.word @song4ref10
	.byte $4f, $01, $14, $97, $16, $97, $14, $99, $17, $b1, $16, $b3, $14, $ab, $00, $85, $48, $00, $cd, $4f, $00
	.byte $41, $0d
	.word @song4ref10
	.byte $14, $4f, $01
	.byte $41, $0f
	.word @song4ref28
	.byte $4f, $00
	.byte $41, $0d
	.word @song4ref10
	.byte $4f, $01, $11, $97, $14, $97, $17, $99, $16, $b1, $14, $b3, $16, $b3
@song4ref98:
	.byte $48, $00, $cd, $7b, $1d, $97, $7c, $20, $97, $7b, $1d, $99, $20, $97, $22, $97, $7c, $23, $99, $79, $21, $83, $7c, $22
	.byte $ab, $20, $99, $48, $00, $cd, $27, $97, $28, $97, $29, $95, $79, $22, $83, $7c, $23, $95, $22, $97, $20, $99, $1b, $b1
	.byte $1d, $99, $48, $00, $cd, $7b, $20, $97, $7c, $22, $97, $7b, $20
@song4ref159:
	.byte $99, $79, $22, $83, $7b, $23, $91, $22, $97, $7c, $20, $99, $1d, $b1, $1b, $99, $48, $cf, $1d, $cd, $00, $cd, $79, $1f
	.byte $cd
	.byte $41, $1b
	.word @song4ref98
	.byte $99, $23, $b1, $22, $b3, $20, $b3, $48, $00, $cd, $7b, $1d, $97, $7c, $20, $97, $7b, $1d
	.byte $41, $0f
	.word @song4ref159
	.byte $ff, $9d, $79, $1f, $cb, $00, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $79, $4f, $01, $82, $11, $cd, $00, $b1, $76, $11, $99, $79, $14, $cd, $00, $b1, $78, $16, $99, $00, $ff, $9d
@song4ref240:
	.byte $0c, $cd
@song4ref242:
	.byte $0f, $cd, $79, $11, $cd, $00, $b1, $76, $11, $99, $79, $14, $cd, $00, $b1, $16, $99, $00, $ff, $ed, $78
	.byte $41, $10
	.word @song4ref242
	.byte $9d, $78
	.byte $41, $13
	.word @song4ref240
	.byte $78, $0f
@song4ref273:
	.byte $cd
@song4ref274:
	.byte $79, $11, $cd, $00, $b1, $76, $11, $99, $78, $0c, $cd, $00, $b1, $76, $0c, $99, $79, $0d, $cd, $00, $b1, $76, $0d, $99
	.byte $78, $0a, $cd, $0c
	.byte $41, $0e
	.word @song4ref273
	.byte $ff, $ed, $78, $0f, $cb, $00
	.byte $41, $15
	.word @song4ref274
	.byte $41, $0e
	.word @song4ref273
	.byte $ff, $ed, $78, $0f, $cb, $00, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $82
@song4ref328:
	.byte $11, $cd, $00, $b1, $11, $99, $14, $cd, $00, $b1, $16, $99, $00, $ff, $9d, $0c, $cd, $0f, $cd
	.byte $41, $0e
	.word @song4ref328
	.byte $ed, $0f, $cd
	.byte $41, $13
	.word @song4ref328
	.byte $41, $0e
	.word @song4ref328
	.byte $ed, $0f
@song4ref361:
	.byte $cd
@song4ref362:
	.byte $11, $cd, $00, $b1, $11, $99, $0c, $cd, $00, $b1, $0c, $99, $0d, $cd, $00, $b1, $0d, $99, $0a, $cd, $0c
	.byte $41, $0e
	.word @song4ref361
	.byte $ff, $ed, $0f, $cb, $00
	.byte $41, $15
	.word @song4ref362
	.byte $41, $0e
	.word @song4ref361
	.byte $ff, $ed, $0f, $cb, $00, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
@song4ref406:
	.byte $cf, $7c, $86
@song4ref409:
	.byte $0f, $b9, $00, $e1, $0f, $b9, $00, $91, $cf, $0f, $b9, $00, $e1, $0f, $b9, $00, $91, $cf
	.byte $41, $0c
	.word @song4ref409
	.byte $c5, $0f, $8b, $78, $0f, $8b, $79, $80, $13, $b9, $00, $91
	.byte $41, $13
	.word @song4ref406
	.byte $41, $0c
	.word @song4ref409
	.byte $c5, $0f, $8b, $78, $0f, $8b
@song4ref454:
	.byte $79, $80, $13, $b9, $00, $91
@song4ref460:
	.byte $13, $b9, $00, $91, $7a, $86, $0f, $91, $00, $9d, $0f, $91, $00, $85, $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $0f, $91, $00, $9d, $78, $0f, $91, $00, $85
	.byte $41, $10
	.word @song4ref454
	.byte $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $0f, $b9, $00, $91, $0f, $91, $00, $9d, $0f, $91, $00, $85, $0f, $91, $00, $9d, $0f, $91, $00, $85
	.byte $41, $10
	.word @song4ref454
	.byte $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $0f, $91, $00, $9d, $78, $0f, $91, $00, $85
	.byte $41, $10
	.word @song4ref454
	.byte $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $79, $80
	.byte $41, $0c
	.word @song4ref460
	.byte $0f, $91, $00, $b9, $79, $80, $13, $b9, $00, $91, $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $52, $80
@song4ref572:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song4ref572
	.byte $41, $0c
	.word @song4ref572
	.byte $41, $0c
	.word @song4ref572
	.byte $42
	.word @song4ch4loop
@song4ch5:
@song4ch5loop:
	.byte $cf, $4f, $01, $80
@song4ref601:
	.byte $20, $97, $00, $ff, $83, $1d, $97, $00, $97, $1b, $99, $00, $ff, $ff, $bd, $cf, $4f, $01
	.byte $41, $10
	.word @song4ref601
	.byte $4f, $01
	.byte $41, $10
	.word @song4ref601
	.byte $4f, $01
	.byte $41, $0f
	.word @song4ref601
	.byte $41, $0c
	.word @song4ref572
	.byte $cf, $7b, $84
@song4ref638:
	.byte $18, $89, $76, $18, $8b, $7b, $1b, $8b, $76, $1b, $89, $7b, $18, $8b, $76, $18, $8b, $7b, $1b, $89, $76, $1b, $8b, $7b
	.byte $1d, $8b, $76, $1d, $89, $7b, $1e, $8b, $76, $1e, $8b, $78, $1c, $83, $7b, $1d, $8b, $78, $1d, $89, $76, $1d, $87, $71
	.byte $1d, $87, $7b, $1b, $8b, $76, $1b, $8b, $71, $1b, $89, $00, $c1, $7b, $22, $89, $76, $22, $8b, $7b, $23, $8b, $76, $23
	.byte $89, $7b, $24, $8b, $76, $24, $8b, $7b, $1e, $a5, $76, $1e, $89, $7b, $1d, $a5, $76, $1d, $8b, $7b, $1b, $a5, $76, $1b
	.byte $8b, $71, $1b, $89, $00, $c1, $7b
	.byte $41, $0c
	.word @song4ref638
	.byte $78, $1d, $83, $7b, $1e, $87, $76, $1e, $87, $7b, $1d, $8b, $76, $1d, $89, $7b, $1b, $8b, $76, $1b, $8b, $7b, $18, $89
	.byte $78, $18, $8b, $76, $18, $8b, $71, $18, $89, $7b, $16, $8b, $78, $16, $8b, $76, $16, $91, $71, $16, $89, $00, $ad, $7b
	.byte $18, $f5, $76, $18, $91, $71, $18, $89, $00, $85, $7b, $19, $a5, $76, $19, $91, $71, $19, $89, $00, $85, $42
	.word @song4ch5loop
@song4ch6:
@song4ch6loop:
	.byte $cf, $7c, $4f, $01, $80
@song4ref822:
	.byte $24, $89, $77, $24, $8b, $00, $ff, $83, $7c, $20, $89, $77, $20, $8b, $00, $97, $7c, $20, $8b, $77, $20, $8b, $00, $ff
	.byte $ff, $bd, $cf, $7c
	.byte $41, $16
	.word @song4ref822
	.byte $7c
	.byte $41, $16
	.word @song4ref822
	.byte $7c
	.byte $41, $16
	.word @song4ref822
@song4ref861:
	.byte $4f, $01, $1b, $ff, $99, $00, $81, $1b, $af, $00, $1b, $95, $00, $81, $cf, $7c, $17, $af, $00, $79, $17, $95, $00, $81
	.byte $19, $c7, $00, $83, $1b, $c7, $00, $83, $cf
	.byte $41, $0d
	.word @song4ref861
	.byte $19, $c7, $00, $b7, $19, $95, $00, $81, $1b, $c7, $00, $83, $cf
	.byte $41, $1d
	.word @song4ref861
	.byte $41, $0d
	.word @song4ref861
	.byte $7c, $18, $c7, $00, $b7, $79, $18, $95, $00, $81, $7b, $1b, $c3, $00, $87, $42
	.word @song4ch6loop
@song5ch0:
@song5ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $bb, $7c, $4f, $01, $88, $19, $b3, $00, $83, $1c, $b3, $00
	.byte $83
@song5ref18:
	.byte $23, $ef
@song5ref20:
	.byte $00, $83, $21, $b3
@song5ref24:
	.byte $00, $83, $20, $b3, $00, $83, $1c, $b3, $00, $83, $48, $1b, $b3, $00, $83, $1e, $b3, $00, $83, $23, $ff, $ab
	.byte $41, $0a
	.word @song5ref20
@song5ref49:
	.byte $1e
@song5ref50:
	.byte $b3, $00, $83, $48, $bb, $19, $b3, $00, $83, $1c, $b3, $00, $83, $21, $ef
	.byte $41, $0a
	.word @song5ref24
@song5ref68:
	.byte $19, $b3, $00, $83, $48, $19, $b3, $00, $83, $1b, $b3, $00, $83, $17, $ff, $ab, $00, $83, $17, $b3, $00, $83, $1b, $b3
	.byte $00, $83, $17
	.byte $41, $0c
	.word @song5ref50
	.byte $41, $1b
	.word @song5ref18
	.byte $00, $83, $25, $b3, $00, $83, $20, $b3, $00, $83
	.byte $41, $0f
	.word @song5ref49
	.byte $41, $0a
	.word @song5ref24
	.byte $41, $0e
	.word @song5ref68
	.byte $e5, $00, $85, $14, $ed, $00, $85, $48, $1b, $ed, $00, $85, $19, $ff, $ff, $db, $00, $87, $48, $1c, $ff, $e3, $00, $87
	.byte $1b, $ff, $e3, $00, $87, $48, $7a, $80
@song5ref152:
	.byte $1c, $8b, $78, $1c, $8d, $79, $14, $8b, $76, $14, $8d, $7a, $1b, $8b, $78, $1b, $8d, $79, $14, $8b, $76, $14, $8d, $00
	.byte $b9, $7a, $1e, $8b, $78, $1e
@song5ref182:
	.byte $8d, $79, $14, $8b, $76, $14, $8d, $7a, $1c, $8b, $78, $1c, $8d, $79, $14, $8b, $76, $14, $8d, $00, $b9, $7a, $1b, $8b
	.byte $78, $1b
	.byte $41, $0d
	.word @song5ref182
	.byte $48, $7a
	.byte $41, $27
	.word @song5ref152
	.byte $8d, $7a, $1c, $8b, $78, $1c, $8d, $7a, $23, $8b, $78, $23, $8d, $75, $23, $8b, $00, $8d, $48, $7a
	.byte $41, $27
	.word @song5ref152
	.byte $41, $0d
	.word @song5ref182
	.byte $48, $7a
	.byte $41, $24
	.word @song5ref152
	.byte $79, $14, $8b, $76, $14, $8d, $74, $14, $8b, $00, $8d, $7a, $1b, $8b, $78, $1b, $8d, $75, $1b, $8b, $00, $8d, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $7c, $4f, $01, $88
@song5ref277:
	.byte $0d, $f5, $0d, $f5, $0d, $f5, $0d, $f5, $0c, $f5, $0c, $f5, $0c, $f5, $0c, $f5, $06, $f5, $06, $f5, $06, $f5, $06, $f5
	.byte $08, $f5, $08, $f5, $08, $f5, $08, $f5
	.byte $41, $20
	.word @song5ref277
	.byte $09, $f5, $09, $f5, $09, $f5, $09, $f5, $0b, $f5, $0b, $f5, $0b, $f5, $0b, $f5, $00, $b9, $77, $4f, $02, $80
@song5ref334:
	.byte $25, $8b, $75, $25, $8d, $77, $20, $8b, $75, $20, $8d
@song5ref345:
	.byte $77, $23, $8b, $75, $23
@song5ref350:
	.byte $8d, $77, $20, $8b, $75, $20, $8d, $00, $b9, $77, $25, $8b, $75, $25
@song5ref364:
	.byte $8d, $77, $20, $8b, $75, $20, $8d, $77, $25, $8b, $75, $25, $8d, $77, $20, $8b, $75, $20, $8d, $00, $b9, $77, $23, $8b
	.byte $75, $23
	.byte $41, $0d
	.word @song5ref364
	.byte $77
	.byte $41, $24
	.word @song5ref334
	.byte $77, $27, $8b, $75, $27
	.byte $41, $0f
	.word @song5ref350
	.byte $41, $1f
	.word @song5ref345
	.byte $41, $0d
	.word @song5ref364
	.byte $77
	.byte $41, $22
	.word @song5ref334
	.byte $77, $27, $8b, $75, $27, $8d, $77, $20, $8b, $75, $20, $8d, $77, $27, $8b, $75, $27, $8d, $73, $27, $8b, $00, $8d, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $7c, $84, $19
@song5ref445:
	.byte $f1, $00, $81, $19, $f1, $00, $81, $19, $f1, $00, $81
@song5ref456:
	.byte $19, $f1, $00, $81, $18, $f1, $00, $81, $18, $f1, $00, $81, $18, $f1, $00, $81, $18, $f1, $00, $81, $12, $f1, $00, $81
	.byte $12, $f1, $00, $81, $12, $f1, $00, $81, $12, $f1, $00, $81, $14, $f1, $00, $81, $14, $f1, $00, $81, $14, $f1, $00, $81
	.byte $14
	.byte $41, $0f
	.word @song5ref445
	.byte $41, $31
	.word @song5ref456
	.byte $f1, $00, $81, $15, $f1, $00, $81, $15, $f1, $00, $81, $15, $f1, $00, $81, $15, $f1, $00, $81, $17, $f1, $00, $81, $17
	.byte $f1, $00, $81, $17, $f1, $00, $81, $17, $f1, $00, $81
@song5ref546:
	.byte $19
@song5ref547:
	.byte $ff, $ff, $ff, $9d, $00, $81, $17, $b5, $00, $81, $15
	.byte $41, $0a
	.word @song5ref547
	.byte $41, $0c
	.word @song5ref546
	.byte $41, $0a
	.word @song5ref547
	.byte $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
@song5ref571:
	.byte $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
	.byte $41, $0c
	.word @song5ref571
	.byte $41, $0c
	.word @song5ref571
	.byte $41, $0c
	.word @song5ref571
	.byte $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $52, $80
	.byte $41, $0c
	.word @song5ref571
	.byte $41, $0c
	.word @song5ref571
	.byte $41, $0c
	.word @song5ref571
	.byte $41, $0c
	.word @song5ref571
	.byte $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $42
	.word @song5ch4loop
@song5ch5:
@song5ch5loop:
	.byte $bb, $79, $4e, $01, $4f, $02, $82
@song5ref637:
	.byte $25, $9b, $76, $25, $9b, $79, $28, $9b, $76, $28
@song5ref647:
	.byte $9b, $79, $2f, $9b, $76, $2f, $9b, $74, $2f, $9b, $72, $2f, $9b, $79, $2d, $9b, $76
@song5ref664:
	.byte $2d, $9b, $79, $2c, $9b, $76, $2c, $9b, $79, $28, $9b, $76, $28, $9b, $79, $27, $9b, $76, $27, $9b, $79, $2a, $9b, $76
	.byte $2a
	.byte $41, $09
	.word @song5ref647
	.byte $00, $b9, $79, $2d, $9b, $76, $2d
@song5ref699:
	.byte $9b, $79, $2c, $9b, $76, $2c, $9b, $79, $2a, $9b, $76, $2a, $9b, $74, $2a, $9b, $72, $2a, $9b, $79, $25, $9b, $76, $25
	.byte $9b, $79, $28, $9b, $76, $28, $9b, $79, $2d, $9b, $76, $2d, $9b, $74, $2d, $9b, $72
	.byte $41, $0a
	.word @song5ref664
@song5ref743:
	.byte $79, $25, $9b, $76, $25, $9b, $79, $25, $9b, $76, $25
@song5ref754:
	.byte $9b, $79, $27, $9b, $76, $27, $9b, $79, $23, $9b, $76, $23, $9b, $74, $23, $9b, $72, $23, $9b, $00, $b9, $79, $23, $9b
	.byte $76, $23
	.byte $41, $0d
	.word @song5ref754
	.byte $79
	.byte $41, $23
	.word @song5ref637
	.byte $41, $09
	.word @song5ref647
	.byte $00, $b9, $79, $31, $9b, $76, $31
	.byte $41, $1b
	.word @song5ref699
	.byte $72
	.byte $41, $0a
	.word @song5ref664
	.byte $41, $15
	.word @song5ref743
	.byte $f5, $79, $20, $9b, $76, $20, $9b, $74, $20, $9b, $72, $20, $9b, $79, $23, $f5, $25, $ff, $b1, $76, $25, $9b, $74, $25
	.byte $9b, $72, $25, $9b, $71, $25, $9b, $00, $b9, $79, $25, $ff, $b1, $76, $25, $9b, $74, $25, $9b, $79, $23, $ff, $b1, $76
	.byte $23, $9b, $74, $23, $9b, $7a, $4f, $01, $80
@song5ref864:
	.byte $25, $8b, $79, $25, $8d, $7a, $20, $8b, $79, $20, $8d, $7a, $23, $8b, $79, $23, $8d, $7a, $20, $8b, $79, $20, $8d, $00
	.byte $b9, $7a, $25, $8b, $79, $25
@song5ref894:
	.byte $8d, $7a, $20, $8b, $79, $20, $8d, $7a, $25, $8b, $79, $25, $8d, $7a, $20, $8b, $79, $20, $8d, $00, $b9, $7a, $23, $8b
	.byte $79, $23
	.byte $41, $0d
	.word @song5ref894
	.byte $7a
	.byte $41, $23
	.word @song5ref864
	.byte $d7, $7a, $20, $8b, $79, $20, $8d, $7a, $27, $8b, $79, $27, $8d, $77, $27, $8b, $27, $8d, $7a, $4f, $01
	.byte $41, $27
	.word @song5ref864
	.byte $41, $0d
	.word @song5ref894
	.byte $7a
	.byte $41, $24
	.word @song5ref864
	.byte $7a, $1b, $8b, $79, $1b, $8d, $7a, $1b, $8b, $79, $1b, $8d, $7a, $20, $8b, $79, $20, $8d, $77, $20, $8b, $20, $8d, $42
	.word @song5ch5loop
@song5ch6:
@song5ch6loop:
	.byte $41, $0c
	.word @song5ref571
	.byte $ff, $ff, $e7, $78, $4f, $02, $84, $20, $ef, $00, $83, $25, $ff, $ff, $ff, $a1, $00, $b9, $20, $ef, $00, $83, $27, $ef
	.byte $00, $83, $2a, $ef, $00, $83, $28, $b3, $00, $83, $27, $b3, $00, $83, $27, $ef, $00, $83, $25, $ff, $ed, $00, $b9, $23
	.byte $b3, $00, $83, $20, $ef, $00, $83, $27, $ff, $e5, $00, $85, $23, $ef, $00, $83, $23, $ef, $00, $83, $25, $ff, $ff, $a9
	.byte $00, $b9, $28, $ff, $e7, $00, $83, $27, $ff, $e7, $00, $83, $4f, $01, $88
@song5ref1075:
	.byte $1c, $b9, $1b, $ef, $00, $83, $1e, $b9, $1c, $ef, $00, $83, $1b, $b9, $1c, $b9
	.byte $41, $0d
	.word @song5ref1075
	.byte $9b, $1c, $9b, $23, $b9
	.byte $41, $10
	.word @song5ref1075
	.byte $41, $0c
	.word @song5ref1075
	.byte $14, $b9, $1b, $b9, $42
	.word @song5ch6loop
@song6ch0:
@song6ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $75, $51, $02, $c0, $80
@song6ref10:
	.byte $25, $9b, $00, $83, $28, $9b, $00, $83, $2a, $9b, $00, $83, $20, $91, $89, $00, $83
@song6ref27:
	.byte $28, $9b, $00, $83, $2a, $9b, $00, $83, $23, $8f, $51, $fe, $50, $8b, $00, $83, $28, $9b, $00, $83, $48
@song6ref48:
	.byte $27, $9b, $00, $83, $28
@song6ref53:
	.byte $9b, $00, $83, $25, $9b, $00, $83, $51, $02, $c0, $28, $9b, $00, $83
@song6ref67:
	.byte $2a, $9b, $00, $83, $20, $9b, $00, $83, $28, $9b, $00, $83, $2a, $9b, $00, $83, $48
@song6ref84:
	.byte $24, $8f, $51, $fe, $50, $8b, $00, $83, $28, $9b, $00, $83, $27, $9b, $00, $83, $24
	.byte $41, $13
	.word @song6ref53
	.byte $48
	.byte $41, $11
	.word @song6ref27
	.byte $41, $10
	.word @song6ref48
	.byte $48
	.byte $41, $10
	.word @song6ref67
	.byte $41, $0e
	.word @song6ref84
	.byte $9b, $00, $83, $48, $51, $02, $c0
	.byte $41, $50
	.word @song6ref10
	.byte $41, $13
	.word @song6ref53
	.byte $48
	.byte $41, $11
	.word @song6ref27
	.byte $41, $10
	.word @song6ref48
	.byte $48
	.byte $41, $10
	.word @song6ref67
	.byte $41, $0e
	.word @song6ref84
	.byte $9b, $00, $83, $42
	.word @song6ch0loop
@song6ch1:
@song6ch1loop:
	.byte $78, $4f, $02, $82, $20, $ff, $d5, $1e, $c5, $c7, $1c, $ff, $d5, $1b, $ff, $8d, $1c, $ff, $8d, $c7, $1b, $ff, $8d, $17
	.byte $c5, $ff, $8f, $18, $ff, $8d, $20, $ff, $d5, $1e, $c5, $c7, $23, $ff, $d5, $21, $ff, $8d, $20, $ff, $8d, $c7, $1e, $ff
	.byte $8d, $1c, $c5, $ff, $8f, $1b, $ff, $8d, $42
	.word @song6ch1loop
@song6ch2:
@song6ch2loop:
@song6ref212:
	.byte $82
@song6ref213:
	.byte $19, $ff, $d5, $14, $c5, $c7, $15, $ff, $d5, $18, $ff, $8d, $19, $ff, $8d, $c7, $14, $ff, $8d, $15, $c5, $ff, $8f, $14
	.byte $ff, $8d
	.byte $41, $17
	.word @song6ref213
	.byte $18, $ff, $8d, $42
	.word @song6ch2loop
@song6ch3:
@song6ch3loop:
@song6ref249:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $0f
	.word @song6ref249
	.byte $42
	.word @song6ch3loop
@song6ch4:
@song6ch4loop:
	.byte $52, $80
	.byte $41, $0f
	.word @song6ref249
	.byte $41, $0f
	.word @song6ref249
	.byte $42
	.word @song6ch4loop
@song6ch5:
@song6ch5loop:
	.byte $78, $4f, $01
	.byte $41, $1a
	.word @song6ref212
	.byte $41, $17
	.word @song6ref213
	.byte $18, $ff, $8d, $42
	.word @song6ch5loop
@song6ch6:
@song6ch6loop:
	.byte $72, $51, $02, $90, $4e, $02, $4f, $01, $80
@song6ref308:
	.byte $19, $9b, $00, $83, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $14, $91, $89, $00, $83, $1c, $9b, $00, $83, $1e, $9b, $00
	.byte $83
@song6ref333:
	.byte $17, $8f, $51, $fe, $20, $8b, $00, $83, $1c, $9b, $00, $83, $1b, $9b, $00, $83, $1c
@song6ref350:
	.byte $9b, $00, $83, $19, $9b, $00, $83, $51, $02, $90, $1c, $9b, $00, $83, $1e, $9b, $00, $83, $14, $9b, $00, $83, $1c, $9b
	.byte $00, $83, $1e, $9b, $00, $83, $18, $8f, $51, $fe, $20, $8b, $00, $83, $1c, $9b, $00, $83, $1b, $9b, $00, $83, $18
	.byte $41, $1b
	.word @song6ref350
	.byte $41, $37
	.word @song6ref333
	.byte $9b, $00, $83, $51, $02, $90, $4e, $02, $4f, $01
	.byte $41, $50
	.word @song6ref308
	.byte $41, $1b
	.word @song6ref350
	.byte $41, $37
	.word @song6ref333
	.byte $9b, $00, $83, $42
	.word @song6ch6loop
@song7ch0:
	.byte $78, $4f, $01, $80, $2c, $d7, $7a, $2a, $d7
@song7ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song7ref14:
	.byte $7c, $80
@song7ref16:
	.byte $29, $ab, $79, $25, $a9, $7b, $27, $ab, $7c, $29, $a9, $2a, $ab, $29, $a9, $25, $ab, $7b, $27, $a9, $48, $7c, $29, $ab
	.byte $25, $a9, $7b, $27, $ab, $7c, $2c, $a9, $2a, $ab, $29, $a9, $25, $ab, $7b, $27, $a9, $48, $7c
	.byte $41, $10
	.word @song7ref16
@song7ref62:
	.byte $48, $7c, $25, $95, $7b, $20, $93, $25, $93, $27, $93, $7c, $2c, $95, $79, $25, $93, $7b, $27, $93, $2c, $93, $7c, $88
	.byte $25, $c1, $7b, $24, $85, $79, $22, $8b, $7b, $24, $ab, $7c, $20, $93, $79, $20, $93, $48
	.byte $41, $20
	.word @song7ref14
	.byte $48, $7c
	.byte $41, $10
	.word @song7ref16
	.byte $41, $1c
	.word @song7ref62
	.byte $48, $7f
@song7ref117:
	.byte $25, $ff, $a7, $00, $87, $27, $fb, $00, $87, $20, $8b, $00, $85, $27, $8b, $00, $85, $48, $29, $a3, $00, $85, $2a, $a1
	.byte $00, $85, $29, $a3, $00, $85, $25, $a1, $00, $85, $25, $b9, $00, $9b, $27, $cf, $00, $85, $48, $25, $fb, $00, $87, $20
	.byte $8b, $00, $85, $25, $8b, $00, $85, $27, $cf, $00, $85, $2c, $cf, $00, $85, $48, $29, $ff, $ff, $83, $00, $df, $48
	.byte $41, $22
	.word @song7ref117
	.byte $cf, $00, $85, $2c, $cf, $00, $85, $48, $2c, $ff, $ff, $83, $00, $85, $25, $cf, $00, $85, $48, $25, $fb, $00, $87, $24
	.byte $8b, $00, $85, $22, $8b, $00, $85, $24, $ab, $00, $ff, $83, $42
	.word @song7ch0loop
@song7ch1:
	.byte $78, $4f, $00, $80, $18, $d7, $7a, $1b, $d7
@song7ch1loop:
	.byte $7b
@song7ref241:
	.byte $14, $95, $19, $93, $1b, $93, $19, $93, $20, $95, $19, $93, $1b, $93, $1d, $93
	.byte $41, $0e
	.word @song7ref241
	.byte $20, $93
	.byte $41, $10
	.word @song7ref241
	.byte $41, $0e
	.word @song7ref241
	.byte $20, $93
	.byte $41, $10
	.word @song7ref241
@song7ref273:
	.byte $14, $95, $19, $93, $1b, $93, $14, $93, $1e, $95, $1d, $93, $19, $93, $14, $93, $14, $95, $19, $93, $20, $93, $18, $93
	.byte $19, $95, $14, $93, $18, $93, $19, $93, $88, $1e, $d7, $77, $1b, $95, $75, $1b, $93, $7b, $1b, $93, $77, $1b, $93, $7b
	.byte $80
	.byte $41, $10
	.word @song7ref241
	.byte $41, $0e
	.word @song7ref241
	.byte $20, $93
	.byte $41, $10
	.word @song7ref241
	.byte $41, $0e
	.word @song7ref241
	.byte $20, $93
	.byte $41, $10
	.word @song7ref241
	.byte $41, $20
	.word @song7ref273
	.byte $88, $1b, $d7, $77, $1b, $95, $75, $1b, $93, $7b, $1b, $93, $77, $1b, $93, $7b, $80
@song7ref361:
	.byte $22, $ab, $1e, $a9, $22, $ab, $1e, $a1, $00, $85, $24, $ab, $20
@song7ref374:
	.byte $a9, $24, $ab, $20, $a1, $00, $85, $20, $ab, $1d, $a9, $20, $ab, $1d, $a1, $00, $85, $20, $a3, $00, $85, $20, $93, $27
	.byte $93, $2c, $95, $25, $93, $27, $93, $1d, $8b, $00, $85, $1e, $ab, $19, $a9, $22, $ab, $19, $a1, $00, $85, $20, $ab, $1b
	.byte $41, $15
	.word @song7ref374
@song7ref425:
	.byte $7f, $19, $93, $20, $93, $25, $95, $24, $93, $20, $93, $19, $8b, $00, $85, $7b
	.byte $41, $14
	.word @song7ref361
	.byte $1d, $ab, $19, $a1, $00, $85, $22, $ab, $19, $a1, $00, $85, $1d, $a3, $00, $85, $19, $93, $20, $93, $25, $ab, $20, $a1
	.byte $00, $85, $1e, $95, $22, $93, $25, $93, $2a, $ab, $25, $93, $22, $93, $2a, $93, $25, $d7, $22, $cf, $00, $85, $20, $95
	.byte $25, $93, $27, $93, $2c, $ed, $20, $ab
	.byte $41, $0e
	.word @song7ref425
	.byte $42
	.word @song7ch1loop
@song7ch2:
	.byte $80, $38, $d7, $36, $d7
@song7ch2loop:
	.byte $82
@song7ref513:
	.byte $19, $ff, $ff, $8b, $18, $d7, $16, $ff, $ff, $8b, $14, $d7, $12, $ff, $ff, $e5, $14, $ff, $b1, $14, $d7, $14, $d7
	.byte $41, $17
	.word @song7ref513
@song7ref539:
	.byte $84
@song7ref540:
	.byte $1e, $ff, $a7, $00, $87, $20, $ff, $a7, $00, $87, $25, $ff, $ff, $81, $00, $87, $1d, $cf, $00, $85
	.byte $41, $14
	.word @song7ref540
@song7ref563:
	.byte $1e, $ff, $a7, $00, $87, $20, $ff, $a7, $00, $87, $22, $ff, $ff, $81, $00, $87, $1d, $cf, $00, $85, $1e, $ff, $ff, $dd
	.byte $00, $85, $20, $ff, $df, $00, $ff, $83, $42
	.word @song7ch2loop
@song7ch3:
	.byte $ff, $b3
@song7ch3loop:
@song7ref601:
	.byte $ff, $ff, $e7, $ff, $ff, $e7, $ff, $ff, $e7, $ff, $ff, $e7, $ff, $ff, $e7, $ff, $ff, $e7, $ff, $ff, $e7, $ff, $ff, $e7
	.byte $7b, $86
@song7ref627:
	.byte $0f, $85, $00, $a3, $78
@song7ref632:
	.byte $0f
@song7ref633:
	.byte $85, $00, $8b, $76, $0f, $85, $00, $8b, $7b, $0f, $85, $00, $a3, $78, $0f, $85, $00, $8b, $76, $0f, $85, $00, $8b, $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b
	.byte $41, $18
	.word @song7ref627
@song7ref664:
	.byte $7b, $0f, $85, $00, $a3, $78, $0f, $85, $00, $a1, $80, $0f, $a3, $00, $85, $86, $0f, $00, $91, $76, $0f, $00, $91, $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b, $80, $0f, $a3, $00, $85, $78, $86
	.byte $41, $14
	.word @song7ref632
	.byte $41, $0d
	.word @song7ref664
	.byte $41, $13
	.word @song7ref633
	.byte $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b
	.byte $41, $13
	.word @song7ref627
	.byte $a1, $80, $0f, $a3, $00, $85, $86
	.byte $41, $14
	.word @song7ref632
	.byte $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b
	.byte $41, $18
	.word @song7ref627
	.byte $7b
	.byte $41, $0f
	.word @song7ref627
	.byte $fd, $78, $0f, $85, $00, $8b, $7b, $0f, $85, $00, $8b, $42
	.word @song7ch3loop
@song7ch4:
	.byte $52, $ff, $ff, $b3
@song7ch4loop:
	.byte $41, $18
	.word @song7ref601
	.byte $52, $80
	.byte $41, $18
	.word @song7ref601
	.byte $42
	.word @song7ch4loop
@song7ch5:
	.byte $ff, $b3
@song7ch5loop:
	.byte $7f, $51, $fb, $80, $4f, $01, $82
@song7ref786:
	.byte $0d, $ab, $ff, $df, $7f, $51, $fb, $80, $0c, $ab, $ab, $7f, $51, $fb, $80, $0a, $ab, $ff, $df, $7f, $51, $fb, $80, $08
	.byte $ab, $ab, $7f, $51, $fb, $80, $06, $ab, $ff, $ff, $b9, $7f, $51, $fb, $80, $08, $ab, $ff, $85, $7f, $51, $fb, $80, $08
	.byte $ab, $ab, $7f, $51, $fb, $80, $08, $ab, $ab, $7f, $51, $fb, $80, $4f, $01
	.byte $41, $1d
	.word @song7ref786
	.byte $79, $4f, $01, $88
@song7ref856:
	.byte $16, $ff, $85, $77, $16, $93, $75, $16, $93, $79, $18, $ff, $85, $77, $18, $93, $75, $18, $93, $79, $20, $ff, $df, $7b
	.byte $14, $93, $1b, $93, $7c, $20, $ab, $7b, $14, $a9, $79, $4f, $01
	.byte $41, $0e
	.word @song7ref856
	.byte $7b, $20, $ff, $b1, $00, $ab, $4f, $00, $19, $93, $20, $93, $7c, $25, $95, $24, $93, $7b, $20, $93, $19, $93, $79, $4f
	.byte $01
	.byte $41, $19
	.word @song7ref856
	.byte $79, $16, $ff, $85, $77, $16, $93, $75, $16, $93, $79, $16, $ff, $85, $77, $16, $93, $75, $16, $93, $79, $1b, $ff, $b1
	.byte $00, $ab, $7b, $4f, $00, $19, $93, $20, $93, $7c, $25, $95, $24, $93, $7b, $20, $93, $19, $93, $42
	.word @song7ch5loop
@song7ch6:
	.byte $74, $51, $01, $80, $4f, $02, $84, $25, $ff, $b1
@song7ch6loop:
	.byte $78, $51, $ff, $00, $ff, $ff, $bb, $00, $a9, $ff, $ff, $e7, $ff, $ff, $e7, $ff, $b3, $78, $88, $35, $c1, $33, $85, $31
	.byte $8b, $33, $ab, $30, $a9, $4f, $02, $84, $1d, $ff, $ff, $83, $00, $85, $1b, $a3, $00, $85, $20, $a1, $00, $85, $19, $ff
	.byte $d5, $00, $87, $18, $a1, $00, $85, $19, $a3, $00, $85, $20, $a1, $00, $85, $20, $ff, $ff, $83, $00, $85, $19, $cf, $00
	.byte $85, $1b, $ff, $b1, $88, $35, $c1, $33, $85, $31, $8b, $33, $ab, $30, $a9
	.byte $41, $14
	.word @song7ref539
	.byte $41, $14
	.word @song7ref540
	.byte $41, $20
	.word @song7ref563
	.byte $42
	.word @song7ch6loop
