; X = char
exec_char:
    ; - - - - - - - -
    ; switch (c)
    ; - - - - - - - -
    ; push return adr
    LDA #>(@ret-1)
    PHA
    LDA #<(@ret-1)
    PHA
    ; push jump adr
    LDA @switch_hi, X
    PHA
    LDA @switch_lo, X
    PHA
    ; jump
    @ret:
    RTS

    @switch_lo:
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
        .byte <(@ret-1)
    
    @switch_hi:
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)
        .byte >(@ret-1)

    ; @switch_hi:
        ; .byte >(END_char-1)
        ; .byte >(LB-1)
        ; .byte >(DB-1)
        ; .byte >(FDB-1)
        ; .byte >(TD-1)
        ; .byte >(SET-1)
        ; .byte >(CLR-1)
        ; .byte >(SAK-1)
        ; .byte >(SPD-1)
        ; .byte >(DL-1)
        ; .byte >(NAM-1)
        ; .byte >(FLH-1)
        ; .byte >(FAD-1)
        ; .byte >(SAV-1)
        ; .byte >(COL-1)
        ; .byte >(RET-1)
        ; .byte >(BIP-1)
        ; .byte >(MUS-1)
        ; .byte >(SND-1)
        ; .byte >(PHT-1)
        ; .byte >(CHR-1)
        ; .byte >(ANI-1)
        ; .byte >(BKG-1)
        ; .byte >(FNT-1)
        ; .byte >(JMP_char-1)
        ; .byte >(ACT-1)
        ; .byte >(BP-1)
        ; .byte >(SP-1)
        ; .byte >(default-1)
        ; .byte >(default-1)
        ; .byte >(EVT-1)
        ; .byte >(EXT-1)
