name: NES ROM builder
on: [push]
jobs:
  build_nes_rom:
    runs-on: ubuntu-latest
    steps:
      # Pull project files
      - name: Checkout repo
        uses: actions/checkout@v4
      # Install compiler
      - name: Install CC65
        run: sudo apt install cc65
      # Build project
      - name: Build NES file
        run: make
      # Upload binary file
      - name: Upload NES file
        uses: actions/upload-artifact@v3
        with:
          name: tuto
          path: tuto.nes
      # Upload binary file
      - name: Upload NES file (Ines 1.0)
        uses: actions/upload-artifact@v3
        with:
          name: tuto_ines1
          path: tuto_ines1.nes
